intermediate_source/model_parallel_tutorial.py 번역
9bow/PyTorch-tutorials-kr pull request #107
Opened 2020-08-08 11:34 UTC by Justin-A

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)
#95 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

intermediate_source/model_parallel_tutorial.py 번역

2020-08-11 13:39 UTC, jjeamin commented
번역 리뷰 진행하겠습니다.

2020-08-11 13:43 UTC, jjeamin commented on intermediate_source/model_parallel_tutorial.py
> +이 방법은 각 GPU에 력 데이터를 부분적으로 할당하고 동일한 신경망 모델을 복제하여 이용하는 방식이었습니다.
력 -> 입력 오타가 있습니다.

2020-08-11 13:54 UTC, jjeamin commented on intermediate_source/model_parallel_tutorial.py
> +이 방법은 신경망 모델을 상당히 빠르게 학습시킬 수 있는 장점이 있지만, 신경망 모델이 하나의 GPU에 할당될 수 있도록 모델 크기가 제한되는 단점이 있습니다.
"이 방법은 모델을 빠르게 학습시킬 수 있지만, 모델이 너무 커서 단일 GPU에 할당 되지 않는 경우에는 동작하지 않습니다." 
라는 형식으로 번역되는게 좋지않을까요?

2020-08-12 02:20 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +이 방법은 각 GPU에 력 데이터를 부분적으로 할당하고 동일한 신경망 모델을 복제하여 이용하는 방식이었습니다.
네, 수정하겠습니다. 감사합니다.

2020-08-12 02:21 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +이 방법은 신경망 모델을 상당히 빠르게 학습시킬 수 있는 장점이 있지만, 신경망 모델이 하나의 GPU에 할당될 수 있도록 모델 크기가 제한되는 단점이 있습니다.
뒷 부분은 말씀해주신대로 번역되는게 좋지만 앞 부분은 그대로 유지해도 괜찮을 것 같습니다. 감사합니다.

2020-08-12 04:15 UTC, 9bow commented
@jjeamin 님, 리뷰 감사합니다!
혹시 괜찮으시면 이 PR과 관련된 이슈(#95)에 리뷰를 진행하시겠다는 취지의 덧글을 남겨주실 수 있으실까요? (예. `컨트리뷰톤 - 리뷰 진행합니다.` 등)
다른 분들께서 어떠한 이슈가 더 리뷰가 필요한지 보실 수 있도록 하려는 것이니 번거로우시더라도 모쪼록 부탁드립니다. (_ _)
감사합니다! ^^

2020-08-15 11:39 UTC, ajin-jng commented
리뷰 진행하겠습니다 :)

2020-08-15 11:39 UTC, ajin-jng commented on intermediate_source/model_parallel_tutorial.py
> +이 방법은 신경망 모델을 상당히 빠르게 학습시킬 수 있는 장점이 있지만, 신경망 모델이 너무 커서 단일 GPU에 할당 되지 않는 경우에는 동작하지 않습니다.
```suggestion
이 방법은 신경망 모델을 상당히 빠르게 학습시킬 수 있는 장점이 있지만, 신경망 모델이 너무 커서 단일 GPU에 할당되지 않는 경우에는 동작하지 않습니다.
```

2020-08-15 11:43 UTC, ajin-jng commented on intermediate_source/model_parallel_tutorial.py
> +구체적으로, 10개의 층으로 구성된 ''m'' 신경망 모델에 대해서 ''데이터 병렬 처리'' 방법은 10개의 층을 전부 복제하여 각 GPU에 할당한다면,
```suggestion
구체적으로, 10개의 층으로 구성된 ''m'' 신경망 모델에 대해서 ''데이터 병렬 처리'' 방법은 10개의 층을 전부 복제하여 각 GPU에 할당한다고 가정합니다.
```

2020-08-15 11:46 UTC, ajin-jng commented on intermediate_source/model_parallel_tutorial.py
> +# 프로세스를 실행하는 쓰레드를 여러개 생성할 필요가 없습니다.
```suggestion
# 프로세스를 실행하는 thread 를 여러개 생성할 필요가 없습니다.
```
/
```suggestion
# 프로세스를 실행하는 스레드를 여러개 생성할 필요가 없습니다.
```

2020-08-17 03:14 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +이 방법은 신경망 모델을 상당히 빠르게 학습시킬 수 있는 장점이 있지만, 신경망 모델이 너무 커서 단일 GPU에 할당 되지 않는 경우에는 동작하지 않습니다.
'할당이 되지 않은 경우' 로 수정하겠습니다. 감사합니다.

2020-08-17 03:16 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +구체적으로, 10개의 층으로 구성된 ''m'' 신경망 모델에 대해서 ''데이터 병렬 처리'' 방법은 10개의 층을 전부 복제하여 각 GPU에 할당한다면,
뒷 문장과 문맥을 고려하였을 때, '할당하여 처리하지만' 으로 수정하겠습니다. 감사합니다.

2020-08-17 03:16 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +# 프로세스를 실행하는 쓰레드를 여러개 생성할 필요가 없습니다.
수정하겠습니다. 감사합니다.

2020-09-07 15:42 UTC, 9bow requested changes
번역 감사합니다. :)
오랜 기간 PR이 열려진 상태로 머물러 있어 빠르게 살펴보며 리뷰를 하였습니다.

* 전체적으로 backtick(`)에 대한 부분을 살펴봐주시기를 부탁드립니다. (홑따옴표로 표기하거나 생략하신 부분 등)
* 번역하신 문체에 대해서는 따로 리뷰를 하지 않았지만, 문장들을 읽어보시면서 조금 더 개선해주시면 좋을 것 같습니다. 
  (예를 들어, 161줄의 `그리고나서,` 는 앞 문장에 `그리고,` 가 있어서 `그 뒤,` 또는 `이후,` 등과 같이 적어주셔도 좋을 것 같습니다.)
* 전체적으로 쉼표(,)가 원문보다 많이 눈에 띄는데 혹시나 보시면서 생략 가능하신 부분이 있다면 생략 부탁드립니다.
  (제가 번역한 문서도 비슷한데요 시간 괜찮으실 때 확인 부탁드립니다.)
* 원문에 없는 주석을 달아주신 것은 정말 좋았습니다! 다만 원문에서 상세히 설명하고 있는 부분이 있다면 가급적 번역 시에도 포함시켜 주시기를 부탁드립니다.

감사합니다!

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +**번역** : 안상준 <https://github.com/Justin-A>
외부 사이트로의 링크는 `(backtick)으로 감싸주시고, 마지막에 밑줄(_)을 추가해주시면 빌드 시 링크로 표기됩니다. :)
(기존의 5번째 줄을 참고 부탁드립니다.)

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +이전 튜토리얼에서는 'DataParallel <https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html>'
여기에서도 링크는 홑따옴표가 아닌, backtick(`)으로 감싸주시기를 부탁드립니다.
(마지막에 밑줄도 부탁드립니다!)

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +이번 튜토리얼에서는 ''데이터 병렬 처리'' 가 아닌 **모델 병렬 처리** 문제를 해결하는 방법을 소개합니다.
문서에 전체적으로 backtick이 잘못 표기되어 있는데요, 이후로는 별도 리뷰는 덧붙이지 않겠지만 문서 전체적으로 요 부분 확인 부탁드립니다~
(pruning 튜토리얼과 같이 개선 부탁드립니다. :) )

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +데이터 병렬 처리 기술을 통해 여러 GPU를 이용하여 신경망 모델을 학습시키는 방법을 설명하였습니다.
링크는 튜토리얼을 가르키고 있지만, 문맥 상으로 DataParallel는 nn.DataParallel을 가르키는 것으로 보입니다.
따라서 전체적인 번역은 `이전 튜토리얼들에서는 여러 GPU를 사용하여 신경망 모델을 학습 시킬 때 어떻게 DataParallel을 사용하는지에 대해서 살펴보았습니다`와 같은 식은 어떨까요?

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +# 여러분은 레이블값과 신경망 모델의 최종 출력 텐서값을 이용하여 오차를 계산할 수 있도록 동일한 GPU에 할당하는 것만 주의하면 됩니다.
생략된 코드 부분들도 함께 추가해주시면 코드와 함께 보기에 좋을 것 같습니다. :)

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +        self.net1 = torch.nn.Linear(10, 10).to('cuda:0') # 첫 번째 층을 첫 번째 GPU에 할당
👍

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +# .. 실험 결과 파일 :: /_static/img/model-parallel-images/mp_vs_rn.png
여기서의 figure는 이미지 표기를 위한 부분으로, 다시 원문으로 표기해주시기를 부탁드립니다.

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +# .. 실험 결과 파일 :: /_static/img/model-parallel-images/mp_vs_rn_vs_pp.png
위에서와 동일하게 figure는 이미지 표기를 위한 부분으로, 다시 원문으로 표기해주시기를 부탁드립니다.
이후로는 별도 리뷰는 덧붙이지 않겠지만 문서 전체적으로 요 부분 확인 부탁드립니다~

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +"""
Note 블럭으로 감싸주셔서 감사합니다! (내용 상으로도 Note 블럭이 좀 더 적절해보이긴 합니다.)
하지만 문서의 양식은 (원문을 참고할 때 직관적으로 찾아볼 수 있게) 최대한 원문을 따라가려고 하고 있는데요, 이 경우에는 문서의 마지막 부분이라 예외적으로 그냥 두어도 괜찮을 것 같기는 합니다.
확인 부탁드립니다.

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +# 실험 결과, 모델 병렬 철리하여 학습하는 시간이 단일 GPU로 학습하는 시간보다 약 7%정도
backtick 내의 부분들은 가급적 원문을 유지해주시는 것은 어떨까요?
여기에서도 사용자가 7%라는 수치의 도출 방법(`4.02/3.75-1=7%`)을 위와 비교하여 궁금해 할 수도 있을 것 같습니다.

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
>  Basic Usage
번역이 누락되었습니다. :)

2020-09-07 15:42 UTC, 9bow commented on intermediate_source/model_parallel_tutorial.py
> +# 학습 시간이 약 49% 정도 단축된 것을 이번 실험을 통해 확인할 수 있습니다. 하지만, 이상적으로
위와 동일하게, 계산 과정을 원문에서 표시한 경우 번역 시에도 유지해주시는 것을 부탁드립니다. :)
이후로는 별도 리뷰는 덧붙이지 않겠지만 문서 전체적으로 요 부분 확인 부탁드립니다~

2020-09-15 05:39 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +**번역** : 안상준 <https://github.com/Justin-A>
확인하였습니다, 반영하도록 하겠습니다!

2020-09-15 05:40 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +이전 튜토리얼에서는 'DataParallel <https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html>'
확인하였습니다, 반영하도록 하겠습니다!

2020-09-15 05:42 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +이번 튜토리얼에서는 ''데이터 병렬 처리'' 가 아닌 **모델 병렬 처리** 문제를 해결하는 방법을 소개합니다.
확인하였습니다, 반영하도록 하겠습니다!

2020-09-15 05:43 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +데이터 병렬 처리 기술을 통해 여러 GPU를 이용하여 신경망 모델을 학습시키는 방법을 설명하였습니다.
제시해주신 의견이 더 좋은 것 같습니다. 반영하도록 하겠습니다!

2020-09-15 05:51 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +# 여러분은 레이블값과 신경망 모델의 최종 출력 텐서값을 이용하여 오차를 계산할 수 있도록 동일한 GPU에 할당하는 것만 주의하면 됩니다.
확인하였습니다, 반영하도록 하겠습니다!

2020-09-15 05:52 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +# .. 실험 결과 파일 :: /_static/img/model-parallel-images/mp_vs_rn.png
수정하였습니다!

2020-09-15 05:53 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +# .. 실험 결과 파일 :: /_static/img/model-parallel-images/mp_vs_rn_vs_pp.png
수정하였습니다!

2020-09-15 05:53 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +"""
이 부분은 유지해도 될 것 같습니다. 감사합니다.

2020-09-15 05:54 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +# 실험 결과, 모델 병렬 철리하여 학습하는 시간이 단일 GPU로 학습하는 시간보다 약 7%정도
약 7% ``4.02/3.75-1=7%``정도

이런 식으로 수정하면 될 것 같습니다.

2020-09-15 05:57 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
>  Basic Usage
`분산 프레임워크 RPC 시작해보기 <rpc_tutorial.html>`__ 로 수정하겠습니다.

2020-09-15 05:58 UTC, Justin-A commented on intermediate_source/model_parallel_tutorial.py
> +# 학습 시간이 약 49% 정도 단축된 것을 이번 실험을 통해 확인할 수 있습니다. 하지만, 이상적으로
확인하였습니다! :)

2020-09-19 15:19 UTC, 9bow approved these changes
고생 많으셨습니다.
이전 리뷰에서 놓친 문법 이슈들이 있는데, 우선 병합하고 제가 추가 커밋을 하도록 하겠습니다.
감사합니다!

2020-09-19 15:19 UTC, merged