recipes/custom_dataset_transforms_loader.py 번역 (#86)
9bow/PyTorch-tutorials-kr pull request #108
Opened 2020-08-08 11:50 UTC by JaeLee18

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #86 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
Custom Dataset & Transformation 번역되지않은 레시피를 번역하였습니다.

2020-08-29 09:38 UTC, JaeLee18 commented on recipes_source/recipes/custom_dataset_transforms_loader.py
> +더 좋은 가독성을 가진 코드를 만들기위해 많은 도구들을 제공합니다. 이 Recipe에서는 다음 세 가지를 배울 수 있습니다.
네 제가 한번에 했으면 좋은데 이런 디테일 신경을 못썼네요 ㅎㅎ.. 감사합니다!

2020-08-29 09:40 UTC, JaeLee18 commented on recipes_source/recipes_index.rst
> +   :card_description: PyTorch 데이터셋 API를 이용하여 어떻게 쉽게 사용자 정의 데이터셋과 dataloader를 만드는지 배워봅시다.
감사합니다. 다음에 진행할때는 기존 레시피 문서의 번역 톤을 따라가야겠어요 ㅎㅎ

2020-08-29 09:42 UTC, JaeLee18 commented on recipes_source/recipes/custom_dataset_transforms_loader.py
> +# 필요할때마다 불러오게 됩니다.
감사합니다. 띄어쓰기 정말 어렵네요 ㅜㅜ..

2020-08-29 09:43 UTC, JaeLee18 commented on recipes_source/recipes/custom_dataset_transforms_loader.py
> +plt.ion()   # 반응형 모드 설정
감사합니다 :)

2020-08-29 09:43 UTC, JaeLee18 commented on recipes_source/recipes/custom_dataset_transforms_loader.py
> +# 데이터셋을 다운 받아 이미지들이 ‘data/faces/’ 의 경로에 위치하게 해주세요.
네 알겠습니다 :)

2020-09-09 13:02 UTC, 9bow requested changes
@JaeLee18 님, PR 감사합니다! 
리뷰드린 문법 상의 이슈들의 확인 부탁드립니다.

더불어, 튜토리얼에서 전체적으로 (we 또는 our를) `우리`로 번역해주셨는데요, 개인적으로는 읽다보니 좀 과한 느낌을 받았습니다.
괜찮으시다면 이 부분도 한 번 같이 검토 부탁드립니다~ (_ _)

2020-09-09 13:32 UTC, 9bow approved these changes
감사합니다!

(혹시 나중에라도 `우리` 부분 관련해서 변경이 있으시면 추가 PR 부탁드립니다. :) )

2020-09-09 13:32 UTC, merged