Recipes/tensorboard with pytorch
9bow/PyTorch-tutorials-kr pull request #113
Opened 2020-08-09 14:56 UTC by hy21116

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #91 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
recipes/tensorboard_with_pytorch.py 번역되지 않은 파일을 번역하였습니다.

2020-08-10 07:30 UTC, Justin-A commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +Anaconda�� ���� PyTorch 1.4+�� ��ġ�ϴ� ���� ����� ����ϴ�.(����):
통헤 -> 통해로 수정하면 좋을 것 같습니다.

2020-08-10 07:32 UTC, Justin-A commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# ��� PyTorch�� TensorBoard�� ����غ��ô�! � ��� ����ϱ� ��,
어떤 것을 기록하기 전에는 조금 추상적이여서, 조금 구체적으로 수정하면 어떨까요?
예를 들어, '''TensorBoard를 사용하기 위해 인스턴스를 먼저 생성합니다.''' 이런식으로요

2020-08-10 07:33 UTC, Justin-A commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# Writer�� �⺻����� ``./runs/`` ���͸��� ����մϴ�.
디렉터리를 파일 경로로 수정하면 좋을 것 같습니다. 
보통 디렉토리, 디렉터리 등으로 작성하는데 한글로 통일감을 주기 위한 의견입니다.

2020-08-10 07:34 UTC, Justin-A commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# ���, ����� ����� ��Ʈ �α� ���͸��� ����Ͽ� TensorBoard�� �����մϴ�.
40번 라인과 동일하게, 디렉터리를 파일 경로로 수정하면 좋을 것 같습니다.

2020-08-10 07:34 UTC, Justin-A commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# �����ϰ� ��ε��ϰ� ����� �� �ֽ�ϴ�. TensorBoard.dev�� ����Ͽ�
누구하고나보단 누구나가 더 자연스러울 것 같습니다!

2020-08-10 14:46 UTC, 9bow commented
안녕하세요, @Justin-A 님.
괜찮으시면 이 PR과 관련된 이슈(#91)에 리뷰를 진행하시겠다는 취지의 덧글을 남겨주실 수 있으실까요? (예. `컨트리뷰톤 - 리뷰 진행합니다.` 등)
다른 분들께서 어떠한 이슈가 더 리뷰가 필요한지 보실 수 있도록 하려는 것이니 번거로우시더라도 모쪼록 부탁드립니다. (_ _)
감사합니다! ^^

2020-08-10 22:18 UTC, Justin-A commented
> 안녕하세요, @Justin-A 님.
> 괜찮으시면 이 PR과 관련된 이슈(#91)에 리뷰를 진행하시겠다는 취지의 덧글을 남겨주실 수 있으실까요? (예. `컨트리뷰톤 - 리뷰 진행합니다.` 등)
> 다른 분들께서 어떠한 이슈가 더 리뷰가 필요한지 보실 수 있도록 하려는 것이니 번거로우시더라도 모쪼록 부탁드립니다. (_ _)
> 감사합니다! ^^

네! 작성하였습니다ㅎㅎ

2020-08-10 23:17 UTC, 9bow commented
감사합니다! (_ _)

2020-08-15 09:16 UTC, ajin-jng commented
컨트리뷰톤 리뷰 진행하겠습니다 :)

2020-08-15 09:18 UTC, ajin-jng commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +TensorBoard UI�� ����� �����͸� �ð�ȭ �ϴ� ���� �ٷ� ���Դϴ�.
```suggestion
TensorBoard UI에 기록한 데이터를 시각화하는 방법을 다룰 것 입니다.
```

2020-08-15 09:21 UTC, ajin-jng commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# `TensorBoard.dev <https://tensorboard.dev/>`_�� ����ϸ� ML ���� ���
```suggestion
# `TensorBoard.dev <https://tensorboard.dev/>`_를 사용하면 ML 실험 결과를 업로드하고 누구하고나 공유할 수 있습니다. 
```

2020-08-24 12:39 UTC, hy21116 commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +설치
Nice catch!! 좋은 의견 감사합니다. :)

2020-08-24 13:59 UTC, hy21116 commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# Writer�� �⺻����� ``./runs/`` ���͸��� ����մϴ�.
(**glossary** 채널 참고) `파일 경로` 로 수정하여 반영하겠습니다. :)

2020-08-24 14:00 UTC, hy21116 commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# ���, ����� ����� ��Ʈ �α� ���͸��� ����Ͽ� TensorBoard�� �����մϴ�.
(glossary 채널 참고) 파일 경로 로 수정하여 반영하겠습니다. :)

2020-08-24 14:16 UTC, hy21116 commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# Writer�� �⺻����� ``./runs/`` ���͸��� ����մϴ�.
@Justin-A 님 의견 반영 및 **glossary** 채널 참고하여 `파일 경로`로 수정하던 도중 몇몇 문장에서 애매함을 느꼈는데요...!

> 모델과 측정 항목을 TensorBoard 로그 디렉터리에 기록하려면 

> logdir의 디렉터리 구조를 재귀적으로

이 부분들을 `파일 경로`로 대체하기에는 어려움이 있어 기존의 `디렉터리`로 유지하는 것이 낫겠다고 판단했습니다. ㅜ 

이 번역본에서는 `디렉터리`로 표현하겠지만 추후 논의가 필요해보입니다. 
좋은 의견 감사합니다. :)

2020-08-27 07:11 UTC, creduo submitted a review, later dismissed

2020-08-27 07:11 UTC, creduo commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# ��� PyTorch�� TensorBoard�� ����غ��ô�! � ��� ����ϱ� ��,
간단하게 표현하신것도 자연스럽게 읽히니까 괜찮을것 같습니다.

2020-08-27 07:11 UTC, creduo commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# �����ϰ� ��ε��ϰ� ����� �� �ֽ�ϴ�. TensorBoard.dev�� ����Ͽ�
의역하신것도 처음 말씀하신것도 괜찮아보입니다 원하시는대로 수정해보세요 :)

2020-08-28 09:10 UTC, hy21116 commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# �����ϰ� ��ε��ϰ� ����� �� �ֽ�ϴ�. TensorBoard.dev�� ����Ͽ�
수정하여 적용했습니다. 감사합니다. :)

2020-08-28 09:10 UTC, hy21116 commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# ��� PyTorch�� TensorBoard�� ����غ��ô�! � ��� ����ϱ� ��,
수정하여 적용했습니다. 감사합니다. :)

2020-09-08 15:34 UTC, 9bow requested changes
@hy21116 님 번역 감사합니다!
Sphinx 문법 중에 빌드 시 잘못 표현될 수 있는게 눈에 띄여 몇 가지 확인 요청드렸습니다.
(더불어 사소한 어투 리뷰도 추가하였는데요, 선택적으로 반영 부탁드립니다. :) )

2020-09-08 15:34 UTC, 9bow commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +Anaconda를 통해 PyTorch 1.4+를 설치하는 방법은 다음과 같습니다.(권장):
(매우 사소하지만) `1.4+` 보다는 `1.4 이상을` 과 같이 표현해주시는 것도 좋을 것 같습니다. :)

2020-09-08 15:34 UTC, 9bow commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# 을 사용해야 합니다. 예로, 간단한 선형 회귀 학습을 만들고 ``add_scalar``를 사용해
문법 뒤쪽의 공백을 놓치신 것 같습니다. :)

```suggestion
# 을 사용해야 합니다. 예로, 간단한 선형 회귀 학습을 만들고 ``add_scalar`` 를 사용해
```

2020-09-08 15:34 UTC, 9bow commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# `TensorBoard.dev <https://tensorboard.dev/>`_를 사용해 ML 실험 결과를
여기서도 공백을 빠트리신 부분이 있어보입니다. :)

```suggestion
# `TensorBoard.dev <https://tensorboard.dev/>`_ 를 사용해 ML 실험 결과를 
```

2020-09-08 15:34 UTC, 9bow commented on recipes_source/recipes/tensorboard_with_pytorch.py
>  #   --description "Simple comparison of several hyperparameters" # optional
사소하지만, 주석도 번역을 해주시는 것이 좋기는 합니다.
`선택 사항` 등과 같은 내용을 추가해주시는 것은 어떨까요?

2020-09-08 15:34 UTC, 9bow commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# 도움이 필요하면 ``$ tensorboard dev --help``를 실행하세요.
```suggestion
# 도움이 필요하면 ``$ tensorboard dev --help`` 를 실행하세요.
```

2020-09-08 15:34 UTC, 9bow commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# 민감한 데이터를 업로드하지 마세요.
`업로드된 TensorBoard는 공개되어 누구나 볼 수 있게 됩니다. 민감한 데이터가 있다면 업로드하지 마세요.` 같은 식은 어떨까요?

2020-09-08 15:34 UTC, 9bow commented on recipes_source/recipes/tensorboard_with_pytorch.py
> +# .. 참고::
Sphinx에서 블럭을 나타내는 지시자로, 원문을 그대로 사용해주시는게 좋을 것 같습니다. :)

2020-09-15 14:58 UTC, hy21116 commented
@9bow 답변이 늦어 죄송합니다.ㅜ 
제안해주신 의견에 모두 동의하며 수정하여 반영했습니다. 감사합니다. :)

2020-09-16 13:19 UTC, 9bow approved these changes
고생 많으셨습니다. 감사합니다!

2020-09-16 13:20 UTC, merged