recipes/loading data recipe 번역 (#94)
9bow/PyTorch-tutorials-kr pull request #125
Opened 2020-08-15 06:04 UTC by itsnamgyu

## 라이선스 동의

[x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호

- **이슈 번호**: #94 

## PR 종류

- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명

튜토리얼 번역

2020-08-20 08:54 UTC, kwonmha commented on recipes_source/recipes/loading_data_recipe.py
> +PyTorch 데이터 불러오기 기능의 핵심에는
```suggestion
PyTorch 데이터 불러오기 기능의 핵심은
```

2020-08-20 08:54 UTC, kwonmha commented on recipes_source/recipes/loading_data_recipe.py
> +클래스가 있습니다. 데어터를 파이썬 iterable로써 접근할 수 있게 해주는 클래스입니다.
```suggestion
클래스입니다. 데어터를 파이썬 iterable로써 접근할 수 있게 해주는 클래스입니다.
```
이렇게 하는 게 조금 더 자연스러운 것 같아 제안해봅니다.

2020-08-20 08:54 UTC, kwonmha commented on recipes_source/recipes/loading_data_recipe.py
> +# 1. 데이터를 불러오는데 필요한 라이버러리 import하기
```suggestion
# 1. 데이터를 불러오는데 필요한 라이브러리 import하기
```

2020-08-20 08:54 UTC, kwonmha commented on recipes_source/recipes/loading_data_recipe.py
> +# YesNo 안에 각각의 데이터 항목은 튜플 형태 (waveform, sample_rate, labels)를 가지며,
```suggestion
# YesNo 안에 각각의 데이터 항목은 튜플 형태 (파형, 샘플 속도, 라벨)를 가지며,
```
아래 133줄에서는 한글로 하셔서 여기도 바꿔서 통일하는게 좋은 것 같습니다.

2020-08-20 08:54 UTC, kwonmha commented on recipes_source/recipes/loading_data_recipe.py
> +# 각각의 데이터 항목 (data point)은 튜플 형태 (waveform: 파형, sample_rate: 샘플 속도, labels: 라벨)를 갖습니다.
```suggestion
# 각각의 데이터 항목 (item)은 튜플 형태 (waveform: 파형, sample_rate: 샘플 속도, labels: 라벨)를 갖습니다.
```
여기서는 원문에 data point라는 단어가 사용되지 않았는데 쓰신 이유가 따로 있으신가요?

2020-08-20 08:54 UTC, kwonmha commented on recipes_source/recipes/loading_data_recipe.py
> +# YesNo 데이터세을 불러올 때 ``root`` 매게변수는 꼭 지정해주셔야 합니다. ``root`` 는
```suggestion
# YesNo 데이터셋을 불러올 때 ``root`` 매게변수는 꼭 지정해주셔야 합니다. ``root`` 는
```

2020-08-27 07:08 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +PyTorch는 인공신경망을 만드는데 필요한 다양한 기본 요소를 제공하고 있고, 간단하고, 직관적이고,
- 인공신경망 -> 신경망 으로 번역해도 될 것 같습니다. 혹은 **인공 신경망** 으로 띄어쓰기 해야 할 것 같습니다.
- 굉장히 소소한 포인트인데, 콤마를 없애고 **간단하고 직관적이며** 따위로 바꾸면 좀 더 자연스럽게 느껴집니다.

2020-08-27 07:10 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +안정적인 API로 쉽게 이용할 수 있습니다. PyTorch에는 공용 데이터셋을 쉽게 사용할
문장 주술과 관견하여, 
1. PyTorch에는 -> PyTorch는 
2. 포함하고 있습니다 -> 포함되어 있습니다.
두 가지 중 한 방향으로 수정하면 좋겠습니다.

2020-08-27 07:11 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +소개
기존 번역에서 Introduction을 **개요**로 번역하고 있는데, 소개가 더 바람직할까요?

2020-08-27 07:12 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +소개
```suggestion
개요
```
기존 번역에서 Introduction을 개요로 번역하고 있는데, 소개가 더 바람직할까요?

2020-08-27 07:13 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +클래스가 있습니다. 데어터를 파이썬 iterable로써 접근할 수 있게 해주는 클래스입니다.
데어터 -> 데이터 typo도 확인 부탁드립니다 :)

2020-08-27 07:15 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +# 이번 레시피는 ``torch`` 와 ``torchaudio`` 을 사용합니다. 다른 내장 데이터셋이
```suggestion
# 이번 레시피는 ``torch`` 와 ``torchaudio`` 를 사용합니다. 다른 내장 데이터셋이
```
읽을 때 토치오디오 를 로 연결되는게 익숙해서 제안드립니다.

2020-08-27 07:18 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +# YesNo 데이터세을 불러올 때 ``root`` 매게변수는 꼭 지정해주셔야 합니다. ``root`` 는
```suggestion
# YesNo 데이터셋을 불러올 때 ``root`` 매개변수는 꼭 지정해주셔야 합니다. ``root`` 는
```

2020-08-27 07:20 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform
```suggestion
# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 변형입니다.
```
1. 종결어미를 통일하는 것을 제안합니다.
2. transform 을 그대로 유지한 이유가 따로 있으실까요?

2020-08-27 07:21 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +# 실제 데이터에 접근해서 yesno_data 형태를 확인합니다. 세번째 항목을 예시로 살펴봅니다.
```suggestion
# 실제 데이터에 접근해서 yesno_data의 형태를 확인합니다. 세 번째 항목을 예시로 살펴봅니다.
```

2020-08-27 07:44 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +# best practice로 권장됩니다. 모델의 성능을 제대로 평가하려면 학습에 쓰이지 않은 out-of-sample
```suggestion
# 권장됩니다. 모델의 성능을 제대로 평가하려면 학습에 쓰이지 않은 out-of-sample
```
best practice라는 말을 지우는 것은 어떨까요? 넣어야 한다면 **최선입니다** 따위로 쓰는 것도 괜찮을 것 같아요.

2020-08-27 07:45 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +# 데이터를 이용해야하기 때문입니다.
```suggestion
# 데이터를 이용해야 하기 때문입니다.
```

2020-08-27 07:49 UTC, codingbowoo requested changes
컨트리뷰톤 리뷰 완료했습니다.

2020-08-28 03:41 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +# 각각의 데이터 항목 (data point)은 튜플 형태 (waveform: 파형, sample_rate: 샘플 속도, labels: 라벨)를 갖습니다.
단어 번역 고민하는 과정에서 헷갈린것같습니다 ;-; 지적 감사합니다!

2020-08-28 03:50 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +PyTorch는 인공신경망을 만드는데 필요한 다양한 기본 요소를 제공하고 있고, 간단하고, 직관적이고,
```PyTorch는 인공 신경망을 만드는데 필요한 다양한 기본 요소를 간단하고, 직관적이고, 안정적인 API로 제공합니다.```

약간 번역투 느낌이 있는데 이렇게 번역하는건 어떨까요!

2020-08-28 03:51 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +소개
개요 좋아요!

2020-08-28 03:54 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +PyTorch는 인공신경망을 만드는데 필요한 다양한 기본 요소를 제공하고 있고, 간단하고, 직관적이고,
오 제공한다는 말을 뒤로 빼니까 훨씬 자연스럽네요! 다만 한 단어마다 쉼표가 찍힌게 조금 어색해보여요! ```간단하고 직관적이며 안정적인 API로 제공합니다. ``` 는 어떨까요?

2020-08-28 04:00 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform
@codingbowoo 파이토치 [`transform`](https://pytorch.org/docs/stable/torchvision/transforms.html) 오브젝트를 매개변수로 넘겨야한다는 의미를 좀더 확실하게 전달하기 위해서입니다!

자세히 확인해보니 `Transform` 클래스는 별도로 정의되어 있지 않지만, `CenterCrop`, `Pad` 등 파이토치에서 제공하는 전용 클래스를 사용하거나, 그것들을 조합시켜서 `Compose` 오브젝트를 만들어서 사용하는 방식인듯 합니다!

2020-08-28 04:00 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform
```suggestion
# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform입니다.
```

2020-08-28 04:08 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +PyTorch는 인공신경망을 만드는데 필요한 다양한 기본 요소를 제공하고 있고, 간단하고, 직관적이고,
좋습니당🙆‍♂️

2020-08-28 04:12 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +안정적인 API로 쉽게 이용할 수 있습니다. PyTorch에는 공용 데이터셋을 쉽게 사용할
1번으로 수정했습니다! 감사합니다!

2020-08-28 04:12 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform
1번 수정사항 먼저 반영했습니다!

2020-08-28 04:13 UTC, itsnamgyu commented
@codingbowoo @kwonmha 꼼꼼한 리뷰 감사합니다! 검토를 여러번 했는데 생각보다 자잘한 오타가 많네요 ;-;

2020-08-28 05:30 UTC, kwonmha approved these changes
수고하셨습니다~

2020-09-02 14:49 UTC, codingbowoo commented on recipes_source/recipes/loading_data_recipe.py
> +# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform
@itsnamgyu 아! 그러면 ```transform입니다.``` 로 종결어미만 통일해주시면 좋을 것 같습니다!

2020-09-03 03:21 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform
```suggestion
# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform입니다.
```

2020-09-03 03:22 UTC, itsnamgyu commented on recipes_source/recipes/loading_data_recipe.py
> +# * ``target_transform``: 타겟 데이터를 변환하기 위한 함수 혹은 transform
수정했습니다! 감사합니다

2020-09-08 14:52 UTC, 9bow approved these changes
번역하신 @itsnamgyu 님과 리뷰해주신 @kwonmha 님, @codingbowoo 님 모두 고생 많으셨습니다!
(특히 마지막의 내부 문서 링크 부분까지 신경써주셔서 대단히 감사합니다. 👍 )

감사합니다 (_ _)

2020-09-08 14:53 UTC, merged