intermediate_source/pruning_tutorials.py 번역
9bow/PyTorch-tutorials-kr pull request #137
Opened 2020-08-21 07:53 UTC by Justin-A

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)
#130 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

intermediate_source/pruning_tutorials.py 번역

2020-09-04 13:57 UTC, jjeamin reviewed
너무 번역이 잘되어있어서 오타만 살짝 수정했습니다 ㅎㅎ

2020-09-04 13:57 UTC, jjeamin commented on intermediate_source/pruning_tutorial.py
> +        1) 가지치기 기법에 의해 매개변수 `name`에 적용된 이진 마스크에 해당하는 명명된 버퍼 `name+_mask` 를 추가합니다.
```suggestion
        1) 가지치기 기법에 의해 매개변수 `name`에 적용된 이진 마스크에 해당하는 명명된 버퍼 `name+'_mask'` 를 추가합니다.
```

이 '' 부분이 빠진 것 같습니다

2020-09-04 13:57 UTC, jjeamin commented on intermediate_source/pruning_tutorial.py
> +# <http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf>` 모델 구조를 이용합니다.
```suggestion
# 이번 튜토리얼에서는, 얀 르쿤 교수님의 연구진들이 1998년도에 발표한 'LeNet 
# <http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf>` 의 모델 구조를 이용합니다.
```

오타 인것 같아 수정했습니다

2020-09-09 12:52 UTC, 9bow requested changes
@Justin-A 님, 고생 많으셨습니다!
번역하실 때 용어 선정에서 고민이 많으셨을 것 같습니다 ㅠ

주로 reST 문법들의 수정을 요청드렸는데요, 검토 부탁드립니다.

더불어 기존에 @kypark7 님께서 리뷰해주시고 해결된 것으로 표시해주신 내용들이 반영이 안된 것 같습니다.
@jjeamin 님 리뷰와 함께 검토하셔서 Commmit 추가 부탁드립니다~

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# <http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf>` 모델 구조를 이용합니다.
링크의 경우 backtick으로 감싸져야 하는데, 홑따옴표로 시작하는 부분이 수정이 필요할 것 같습니다. :)

![image](https://user-images.githubusercontent.com/9343724/92598320-9a648b80-f2e3-11ea-8277-183998fe6ce4.png)

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +
**번역**에 @Justin-A 님이 추가되면 어떨까요?

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +가지치기 기법 튜토리얼
`가지치기 기법(Pruning) 튜토리얼` 등과 같이 제목과 본문에서 처음 등장할 때 원문을 병기해주시는 것은 어떨까요?

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # Convolution 연산 결과 5x5 크기의 16 채널 수의 이미지
👍

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# <extending-torch-nn-utils-pruning-with-custom-pruning-functions> 내 존재하는 가지치기 기법을 선택합니다.
`<#extending-torch-nn-utils-pruning-with-custom-pruning-functions>` 부분은 문서 내의 링크로, 아래 `torch.nn.utils.prune에서 확장된 맞춤형 가지치기 기법`으로 번역된 제목으로 바로가는 부분입니다.
이 때, 한글은 무시되므로 `<#torch-nn-utils-prune>`을 링크로 걸어주시면 되는데요, 아래와 같은 식은 어떨까 싶습니다.

```suggestion
# 첫 번째로는, ``torch.nn.utils.prune`` (또는 ``BasePruningMethod`` 의 서브 클래스로 직접 `구현 <#torch-nn-utils-prune>`_ )
# 내 존재하는 가지치기 기법을 선택합니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# 이제 가중치값들은 ``module``의 매개변수가 아니라 하나의 속성값으로 취급되는 점을 주의하세요.
띄어쓰기가 필요할 것 같습니다. :)

```suggestion
# 이제 가중치값들은 ``module`` 의 매개변수가 아니라 하나의 속성값으로 취급되는 점을 주의하세요.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# 새로운 마스크와 이전의 마스크의 결합은 ``PruningContainer``의 ``compute_mask``메소드를 통해 처리할 수 있습니다.
띄어쓰기를 추가하면 좋을 것 같습니다.

```suggestion
# 새로운 마스크와 이전의 마스크의 결합은 ``PruningContainer`` 의 ``compute_mask`` 메소드를 통해 처리할 수 있습니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# 이 방식은 ``ln_structured`` 함수와 ``n=2`` 와 ``dim=0``의 인자값을 바탕으로 구현될 수 있습니다.
```suggestion
# 이 방식은 ``ln_structured`` 함수와 ``n=2`` 와 ``dim=0`` 의 인자값을 바탕으로 구현될 수 있습니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# 필요한 경우 모델의 ``state_dict```에 저장되기 떄문에, 쉽게 직렬화하여 저장할 수 있다.
```suggestion
# 필요한 경우 모델의 ``state_dict`` 에 저장되기 떄문에, 쉽게 직렬화하여 저장할 수 있다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# ``torch.nn.utils.prune``에서 확장된 맞춤형 가지치기 기법
```suggestion
# ``torch.nn.utils.prune`` 에서 확장된 맞춤형 가지치기 기법
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# 기본 클래스는 ``__call__``, ``apply_mask``,``apply``, ``prune``, ``remove`` 메소드들을 내포하고 있습니다.
```suggestion
# 기본 클래스는 ``__call__``, ``apply_mask``, ``apply``, ``prune``, ``remove`` 메소드들을 내포하고 있습니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# ``PruningContainer`` (마스크 가지치기 기법을 반복적으로 적용하는 것을 처리하는) 을 가능하게 합니다.
```suggestion
# ``PRUNING_TYPE`` 을 지정한다면, 가지치기 기법을 적용하기 위해 파라미터 값을 올바르게 제거하는 
# ``PruningContainer`` (마스크 가지치기 기법을 반복적으로 적용하는 것을 처리하는)를 가능하게 합니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# (``'전역 변수'``) 연결에는 작용하지 않기 때문에 ``PRUNING_TYPE='unstructured'`` 방식으로 진행됩니다.
홑따옴표 내의 unstructred와 global은 304번째 줄에서 명시한 `PRUNING _TYPE`의 값들로 보입니다.
해당 값들은 원문으로 표시하는게 낫지 않을까요?

```suggestion
# 한 층의 개별 연결에 작용하며 전체 유닛/채널 (``'structured'``), 또는 다른 파라미터 간 
# (``'global'``) 연결에는 작용하지 않기 때문에 ``PRUNING_TYPE='unstructured'`` 방식으로 진행됩니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +    텐서 내 다른 모든 항목들을 제거하여 `module`에서 `name` 이라는 파라미터에 대해 가자치기 기법을 적용
```suggestion
    텐서 내 다른 모든 항목들을 제거하여 `module` 에서 `name` 이라는 파라미터에 대해 가자치기 기법을 적용
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +# ``nn.Module``의 매개변수에 적용하기 위해 인스턴스화하고 적용하는 간단한 기능을 구현해봅니다.
```suggestion
# ``nn.Module`` 의 매개변수에 적용하기 위해 인스턴스화하고 적용하는 간단한 기능을 구현해봅니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +        1) 가지치기 기법에 의해 매개변수 `name`에 적용된 이진 마스크에 해당하는 명명된 버퍼 `name+_mask` 를 추가합니다.
```suggestion
        1) 가지치기 기법에 의해 매개변수 `name` 에 적용된 이진 마스크에 해당하는 명명된 버퍼 `name+'_mask'` 를 추가합니다.
```

2020-09-09 12:52 UTC, 9bow commented on intermediate_source/pruning_tutorial.py
> +        기존의 파라미터는 `name+'_orig'` 이름이라는 새로운 매개변수에 저장됩니다.
요렇게 고치면 조금 더 읽기 수월하지 않을까요?

```suggestion
        기존의 파라미터는 `name+'_orig'` 라는 이름의 새로운 매개변수에 저장됩니다.
```

2020-09-15 06:00 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +        1) 가지치기 기법에 의해 매개변수 `name`에 적용된 이진 마스크에 해당하는 명명된 버퍼 `name+_mask` 를 추가합니다.
9bow님의 의견으로 수정하겠습니다!

2020-09-15 06:01 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# <http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf>` 모델 구조를 이용합니다.
넵, 수정하였습니다!

2020-09-15 06:01 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +
네ㅎㅎ 추가하였습니다!

2020-09-15 06:02 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +가지치기 기법 튜토리얼
좋은 의견인 것 같습니다. 반영하겠습니다!

2020-09-15 06:03 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# <extending-torch-nn-utils-pruning-with-custom-pruning-functions> 내 존재하는 가지치기 기법을 선택합니다.
넵! 좋은 의견인 것 같습니다.

2020-09-15 06:04 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# 이제 가중치값들은 ``module``의 매개변수가 아니라 하나의 속성값으로 취급되는 점을 주의하세요.
네! 수정하겠습니다

2020-09-15 06:05 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# 새로운 마스크와 이전의 마스크의 결합은 ``PruningContainer``의 ``compute_mask``메소드를 통해 처리할 수 있습니다.
수정하겠습니다 :)

2020-09-15 06:05 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# 이 방식은 ``ln_structured`` 함수와 ``n=2`` 와 ``dim=0``의 인자값을 바탕으로 구현될 수 있습니다.
네! 감사합니다 :)

2020-09-15 06:05 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# 필요한 경우 모델의 ``state_dict```에 저장되기 떄문에, 쉽게 직렬화하여 저장할 수 있다.
네 감사합니다!

2020-09-15 06:06 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# ``torch.nn.utils.prune``에서 확장된 맞춤형 가지치기 기법
네! 수정하였습니다 :)

2020-09-15 06:06 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# 기본 클래스는 ``__call__``, ``apply_mask``,``apply``, ``prune``, ``remove`` 메소드들을 내포하고 있습니다.
네! 감사합니다 :)

2020-09-15 06:07 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# ``PruningContainer`` (마스크 가지치기 기법을 반복적으로 적용하는 것을 처리하는) 을 가능하게 합니다.
네! 감사합니다 :)

2020-09-15 06:08 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# (``'전역 변수'``) 연결에는 작용하지 않기 때문에 ``PRUNING_TYPE='unstructured'`` 방식으로 진행됩니다.
네! 감사합니다 :)

2020-09-15 06:08 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +    텐서 내 다른 모든 항목들을 제거하여 `module`에서 `name` 이라는 파라미터에 대해 가자치기 기법을 적용
네ㅎㅎ 수정하겠습니다!

2020-09-15 06:08 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +# ``nn.Module``의 매개변수에 적용하기 위해 인스턴스화하고 적용하는 간단한 기능을 구현해봅니다.
네 감사합니다!

2020-09-15 06:09 UTC, Justin-A commented on intermediate_source/pruning_tutorial.py
> +        기존의 파라미터는 `name+'_orig'` 이름이라는 새로운 매개변수에 저장됩니다.
네! 좋은 의견인 것 같습니다ㅎㅎ 수정하겠습니다!

2020-09-19 15:19 UTC, 9bow approved these changes
고생 많으셨습니다. 감사합니다!!

2020-09-19 15:23 UTC, merged