intermediate_source/memory_format_tutorial.py 번역 (#129)
9bow/PyTorch-tutorials-kr pull request #138
Opened 2020-08-22 05:42 UTC by potatochips178

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #129

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
intermediate_source/memory_format_tutorial.py 번역

2020-08-29 09:06 UTC, hy21116 commented
멘토님 두 분이 리뷰어로 지정되어 있으신 것 같은데 제가 추가로 리뷰를 해도 될까요? :0

2020-08-30 03:08 UTC, Gangsss reviewed
번역하느라 고생하셨습니다

2020-08-30 03:08 UTC, Gangsss commented on intermediate_source/memory_format_tutorial.py
> +# 모델 초기화(혹은 가져오기) 이후, 한 번 실행이 필요합니다.
```suggestion
# 모델 초기화(혹은 가져오기) 이후,  실행이 한 번 필요합니다. 
```

2020-09-04 13:40 UTC, jjeamin commented on intermediate_source/memory_format_tutorial.py
> +# 다음과 같이 많은 할 것들이 아직 남아있습니다:
`다음과 같이, 여전히 해야 할 일이 많이 남아있습니다.`  가 자연스럽지 않을까요??

2020-09-04 13:47 UTC, jjeamin reviewed
앞에 작성을 거의 해주셔서 마지막 부분을 초점을 두고 리뷰 했습니다 ㅎㅎ

2020-09-04 13:47 UTC, jjeamin commented on intermediate_source/memory_format_tutorial.py
> +# 다음과 같이 많은 할 것들이 아직 남아있습니다:
```suggestion
# 다음과 같이 여전히 해야 할 일이 많이 남아있습니다 :
```

가 자연스럽지 않을까요??

2020-09-04 13:47 UTC, jjeamin commented on intermediate_source/memory_format_tutorial.py
> +# 다음 개발자 안내서를 따르면 됩니다.
```suggestion
# 만약 Channels Last tensors를 지원하지 않는 연산자를 발견하고 기여하기를 원한다면,
# 다음 개발자 안내서를 자유롭게 사용하세요. 
```

가 약간 더 자연스럽지 않을까요?

2020-09-04 13:47 UTC, jjeamin commented on intermediate_source/memory_format_tutorial.py
> +# 그러나, 모든 연산자들이 Channels Last를 지원하도록 완전히 바뀐 것은 아닙니다(대신 보통 연속적인 출력을 반환합니다).
```suggestion
# 그러나, 모든 연산자들이 Channels Last를 지원하도록 완전히 바뀐 것은 아닙니다(보통 연속적인 출력을 반환합니다).
```

대신을 빼는게 좋지 않을까요??

2020-09-04 14:02 UTC, jjeamin reviewed
리뷰 추가합니다 ㅎㅎ

2020-09-04 14:02 UTC, jjeamin commented on intermediate_source/memory_format_tutorial.py
> +# - 분산 훈련을 지원하는 지 확인해보기;
```suggestion
# - 분산 훈련을 지원하는지 확인하기;
```

띄어쓰기랑 위에 문장이랑 유사하게 바꾸어보았습니다

2020-09-13 05:48 UTC, potatochips178 commented on intermediate_source/memory_format_tutorial.py
> +# 그러나, 모든 연산자들이 Channels Last를 지원하도록 완전히 바뀐 것은 아닙니다(대신 보통 연속적인 출력을 반환합니다).
영어 그대로 번역하다보니 그랬습니다. 대신을 빼도 의미가 바뀌지 않고 더 매끄러워지니 수정하도록 하겠습니다

2020-09-13 15:23 UTC, 9bow requested changes
@potatochips178 님, 고생 많으셨을 것 같습니다 ㅎㅎ

전체적으로 한 번 읽어보았는데요, 매끄럽지 않거나 이해가 어려운 문장들이 다소 있어보입니다.
번역해주신 튜토리얼을 (`make html-noplot` 등으로 html로 만드신 뒤에) 읽어보시면서 한 번씩만 다시 살펴봐주시기를 부탁드립니다. (_ _)

2020-09-13 15:23 UTC, 9bow commented on intermediate_source/memory_format_tutorial.py
> +# ``--channels-last true`` 를 지나가는 것은 22% 성능향상을 보이며 Channels Lasst 형식을 가진 모델을 실행시키는 것을 허용합니다.
문맥상 `--channels-last true` 인자를 `전달`하는 것이 조금 더 적절하지 않을까요?
```suggestion
# ``--channels-last true`` 인자를 전달하여 Channels Last 형식으로 모델을 실행하면 22%의 성능 향상을 보입니다.
```

2020-09-13 15:23 UTC, 9bow commented on intermediate_source/memory_format_tutorial.py
> +# 다음 모델의 리스트는 Channels Last를 전적으로 지원하고 Volta 기기에서 8%-35%의 성능 향상을 보입니다:
NVIDIA의 Volta를 지칭하는 것 같은데요, Volta GPU 또는 Volta 장비 등은 어떨까요?
```suggestion
# 아래 목록의 모델들은 Channels Last 형식을 전적으로 지원(full support)하고 Volta 장비에서 8%-35%의 성능 향상을 보입니다:
```

2020-11-15 12:22 UTC, 9bow commented
@potatochips178 님, 혹시 위 내용에 대해서 확인 / 반영해주실 수 있으신지요?
어려우시다면 제가 임의로 병합 후 변경하도록 하겠습니다. ^^

2020-11-22 13:24 UTC, 9bow commented
너무 오래 방치되어 있어 일단 임의로 병합 후 추가 커밋을 통해 변경토록 하겠습니다.

2020-11-22 13:24 UTC, 9bow approved these changes
너무 오래 방치되어 있어 일단 임의로 병합 후 추가 커밋을 통해 변경토록 하겠습니다.

2020-11-22 13:26 UTC, merged