Beginner source/dcgan faces tutorial.py 번역
9bow/PyTorch-tutorials-kr pull request #139
Opened 2020-08-22 17:25 UTC by JaeLee18

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #134

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
Beginner source/dcgan faces tutorial.py 번역

2020-08-25 07:53 UTC, kwonmha commented
컨트리뷰톤 리뷰 진행하겠습니다.

2020-08-25 09:57 UTC, kwonmha reviewed
gradient, layer를 한글로 다 통일해서 변환하는 것이 좋아 보입니다.

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# DCGAN은 위에 설명된 GAN의 확장개념이지만 다른점이라면 discriminator에는 convolutional 층을
```suggestion
# DCGAN은 위에 설명된 GAN의 확장개념이지만 다른 점이라면 discriminator에는 convolutional 계층을 
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# generator에는 convolutional-transpose 층이 각각 사용됩니다.
```suggestion
# generator에는 convolutional-transpose 계층이 각각 사용됩니다. 
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# generator에는 convolutional-transpose 층이 각각 사용됩니다.
용어집을 참고하여 고쳤습니다.

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# strided conv-transpose 층은 잠재 벡터가 같은 모양의 이미지로 변환되는것을 가능하게 합니다.
```suggestion
# strided conv-transpose 층은 잠재 벡터가 같은 모양의 이미지로 변환되는 것을 가능하게 합니다.
```
의역해서 `잠재 벡터를 같은 모양의 이미지로 변환합니다` 가 자연스러워 보입니다.

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# -  **image_size** - 훈련때 사용될 이미지의 크기입니다. 초기값은 64x64로 설정 되어있고,
```suggestion
# -  **batch_size** - 훈련 때 사용될 배치 크기 입니다. DCGAN 논문에서는 128로 사용했습니다.
# -  **image_size** - 훈련 때 사용될 이미지의 크기입니다. 초기값은 64x64로 설정 되어있고,
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# -  **nc** - 입력값으로 사용되는 이미지의 색상 채널 갯수입니다. 컬러 이미지들은 3으로 가지고있습니다.
```suggestion
# -  **nc** - 입력값으로 사용되는 이미지의 색상 채널 갯수입니다. 컬러 이미지들은 3입니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# -  **lr** - 훈련때 사용되는 러닝레이트 입니다. DCGAN에서 나와있는데로
```suggestion
# -  **num_epochs** - 훈련 때 실행되는 에포크의 수입니다. 더 좋은 결과를 위해선 많은 에포크가 필요하지만
#    그만큼 더 많은 시간이 필요합니다.
# -  **lr** - 훈련 때 사용되는 러닝레이트 입니다. DCGAN에서 나와있는 대로 
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# -  **beta1** - beta1 는 Adam 옵티마이저에 사용됩니다. 논문에 소개된대로
```suggestion
# -  **beta1** - beta1 는 Adam 옵티마이저에 사용됩니다. 논문에 소개된 대로
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +#    0보다 큰 수 일때는 해당하는 GPU갯수만큼 사용하게됩니다.
```suggestion
#    0보다 큰 수일 때는 해당하는 GPU개수만큼 사용하게됩니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# dataloader에 사용되는 worker 갯수
```suggestion
# dataloader에 사용되는 worker 개수
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 폴더 구조를 이렇게 만드는것은 중요한 과정이고 ImageFolder 데이터셋 class를 사용할 예정이라
```suggestion
# 폴더 구조를 이렇게 만드는 것은 중요한 과정이고 ImageFolder 데이터셋 class를 사용할 예정이라 
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# ImageFolder를 우리가 설정해놓은데로 사용할 수 있습니다.
```suggestion
# ImageFolder를 우리가 설정해놓은 대로 사용할 수 있습니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 데이터 셋은 *img_align_celeba.zip* 이라는 파일로 다운받아집니다.
```suggestion
# 데이터셋은 *img_align_celeba.zip* 이라는 파일로 다운받아집니다. 
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# generator인 :math:`G` 는 잠배 벡터 공간(:math:`z`)을  데이터 공간에 대응시키도록 고안되었습니다.
```suggestion
# generator인 :math:`G` 는 잠재 벡터 공간(:math:`z`)을  데이터 공간에 대응시키도록 고안되었습니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 왜냐하면 이 배치에 대한 구성은 DCGAN 논문의 핵심적인 기여이기 떄문입니다.
```suggestion
# 왜냐하면 이 배치에 대한 구성이 DCGAN 논문의 핵심적인 기여이기 때문입니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 이러한 층들은 훈련도중 gradient의 흐름에 대해 도움을 줍니다.
```suggestion
# 이러한 층들은 훈련도중 변화도의 흐름에 대해 도움을 줍니다.
```
[용어집](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md)에 번역이 있어 수정했습니다.

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# DCGAN 논문에서 generator 의 image는 아래와 같이 보여줍니다.
```suggestion
# DCGAN 논문에서 generator 의 이미지는 아래와 같이 보입니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 마지막 확률이 나오게 됩니다. 이 신경망 구조는 문제를 해결하는데 필요에 따라 더 많은 층을 추가하여
```suggestion
# 마지막으로 확률이 나오게 됩니다. 이 신경망 구조는 문제를 해결하는데 필요에 따라 더 많은 층을 추가하여
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 마지막 확률이 나오게 됩니다. 이 신경망 구조는 문제를 해결하는데 필요에 따라 더 많은 층을 추가하여
마지막 확률이 어색해서 으로 를 추가했습니다.

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# DCGAN 논문은 다운 샘플을 하기위해 pooling을 사용하는것 보다 trided convolution을
```suggestion
# DCGAN 논문은 다운 샘플을 하기위해 pooling을 사용하는것 보다 strided convolution을
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 이 부분은 곧 등장할 훈련 반복문에서 사용될것이지만 :math:`y` (예) GT 라벨)를 바꿈으로서
```suggestion
# 우리는 어떤 부분의  BCE 식이 :math:`y` 의 입력값으로 이용될지 지정할 수도 있습니다.
# 이 부분은 곧 등장할 훈련 반복문에서 사용될 것이지만 :math:`y` (예) GT 라벨)를 바꿈으로서
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 어떤 부분을 계산하기를 원하는지 정할 수 있다는것을 이해하는게 굉장히 중요합니다.
```suggestion
# 어떤 부분을 계산하기를 원하는지 정할 수 있다는 것을 이해하는 것이 굉장히 중요합니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 여기서 우리는 최고의 연습이라고 불리는 `ganhacks <https://github.com/soumith/ganhacks>`__
```suggestion
# 여기서 우리는 최고의 사례라고 불리는 `ganhacks <https://github.com/soumith/ganhacks>`__ 
```
여기서 practice 는 연습이라기 보다는 실제 사례 에 좀 더 가까운 느낌인 것 같습니다.

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +#  진짜 인지 가짜인지 분류하는 확률을 최대화 시키는것 입니다.
```suggestion
#  진짜인지 가짜인지 정확히 분류하는 확률을 최대화 시키는것 입니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 본래의 논문이 서술했듯, 우리는 :math:`log(1-D(G(z)))` 을 최소화를 이용하여
```suggestion
# 본래의 논문이 서술했듯, 우리는 :math:`log(1-D(G(z)))` 을 최소화 하도록
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 언급한 대로 이것은 Goodfellow가 초기 학습 단계에는 충분한 gradient를 제공하지 못한다는것을
```suggestion
# 언급한 대로 이것은 Goodfellow가 초기 학습 단계에는 충분한 gradient를 제공하지 못한다는 것을
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 코드에서 우리는 다음과 같은것을 달성하고자 합니다.
```suggestion
# 코드에서 우리는 다음과 같은 것을 달성하고자 합니다.
```

2020-08-25 09:57 UTC, kwonmha commented on beginner_source/dcgan_faces_tutorial.py
> +# 입력시킬수 있습니다.
```suggestion
# 입력시킬 수 있습니다.
```

2020-09-04 10:07 UTC, JaeLee18 commented on beginner_source/dcgan_faces_tutorial.py
> +# 이 튜토리얼은 예제를 해보면서 DCGAN에 대한 소개를 제공합니다.
감사합니다 ㅎㅎ 따라합니다가 훨씬 더 좋습니다.

2020-09-12 09:17 UTC, Gangsss reviewed
번역하느라 고생하셨습니다!

2020-09-13 14:50 UTC, 9bow requested changes
안녕하세요, @JaeLee18 님.
긴 문서 번역하시느랴 고생이 많으셨습니다 ㅠ
문서 전체를 리뷰하지는 못했지만, 공통적으로 변경을 검토해주셨으면 하는 부분들이 있어서 변경 요청을 먼저 드립니다.

* 용어의 번역: 기존 번역에 사용하였던 용어들이 [용어집](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md)과 #glossary 채널을 참고해 주시기를 부탁드립니다.
* reST 문법: 로컬 브랜치에서 `make html-noplot` 을 실행하시면 문서의 빌드 결과를 보실 수 있습니다. 띄어쓰기나 생략된 # 등으로 정상적이지 않게 보이는 부분들이 있어서 수정 요청드립니다.

그 외에도 문서 전체적으로 반영이 되었으면 하는 부분들을 리뷰에 추가한 곳들이 있으니 참고 부탁드립니다.

감사합니다!

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
>  # .. math:: \underset{G}{\text{min}} \underset{D}{\text{max}}V(D,G) = \mathbb{E}_{x\sim p_{data}(x)}\big[logD(x)\big] + \mathbb{E}_{z\sim p_{z}(z)}\big[log(1-D(G(z)))\big]
빌드 중 수식이 잘 표현되지 않는 문제가 있어 아래와 같이 띄어쓰기가 필요합니다.
```suggestion
# 논문에서,  GAN의 손실함수는 
#
# .. math:: \underset{G}{\text{min}} \underset{D}{\text{max}}V(D,G) = \mathbb{E}_{x\sim p_{data}(x)}\big[logD(x)\big] + \mathbb{E}_{z\sim p_{z}(z)}\big[log(1-D(G(z)))\big]
```

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +
위와 같은 문제로 아래와 같이 띄어쓰기 및 # 블럭 유지가 필요합니다.
```suggestion
# 로 정의하였습니다.
#
```

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# GAN은 *generator* 와 *discriminator* 라는 두개의 모델로 이루어져 있습니다.
문서 전반적으로 generator와 discriminator을 원문 그대로 남겨주셨는데요,
`생성자(Generator)`와 `구분자(Discriminator)`로 번역해주시는건 어떨지 한 번 검토 부탁드립니다. (_ _)

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# generator의 역할은 훈련용 이미지처럼 보이는 'fake' 이미지들을 만들어내는것입니다.
원문에서는 홑따옴표가 아닌 backtilt를 쓰고 있어 이 부분 반영 부탁드립니다.
더불어, 위 생성자와 구분자처럼 `가짜(fake)` 등과 같이 번역을 해주시길 검토 부탁드립니다. (_ _)

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# :math:`z` 는 잠재 공간 벡터로 일반적인 정규분포로부터 샘플되어집니다.
`잠재 공간 벡터(latent space vector)`과 같이 처음 등장하는 (일반적이지 않은) 용어에 대해서는 원문을 함께 표시해주시는 것도 좋지 않을까 싶습니다. :)

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# :math:`D(x)` 는 discriminator 신경망으로 :math:`x` 가  generator에서 온게 아닌 실제 훈련데이터일 확률을 반환합니다.
문서 전체적으로 띄어쓰기가 2번 반복되거나 생략된 경우(예. `훈련 데이터`)가 많은데요,
전체적으로 한 번 검토 부탁드립니다. (_ _)

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# generator에는 convolutional-transpose 계층이 각각 사용됩니다.
Convolution은 기존에 합성곱으로 많이 번역해서 `합성곱(convolutional)` 등과 같이 번역해주시면 어떨까 싶습니다.
`convolutional-transpose`는 마땅한 번역이 생각나지 않아 찾아봤는데, 전치 합성곱으로 번역한 곳이 있는데 뭔가 좀 어색한 느낌이네요;

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# `ReLU <https://pytorch.org/docs/stable/nn.html#relu>`__ 를 활성함수로 구성되어 있습니다.
```suggestion
# `ReLU <https://pytorch.org/docs/stable/nn.html#relu>`__ 활성함수로 구성되어 있습니다.
```
정도도 어색하지 않을 것 같습니다. :)

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# -  **lr** - 훈련 때 사용되는 러닝레이트 입니다. DCGAN에서 나와있는 대로
learning rate는 기존에 학습률로 번역을 했었는데요, 아래와 같은 식은 어떨까 싶습니다.
```suggestion
# -  **lr** - 학습 시 사용하는 학습률(learning rate)입니다. DCGAN에서 나와있는 대로 
```

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# 데이터를 이용합니다.
```suggestion
# 이번 튜토리얼에서 `Celeb-A Faces
# dataset <http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html>`__ 을 사용하게 되는데, 링크된 사이트에서 다운받거나 
# `Google
# Drive <https://drive.google.com/drive/folders/0B7EVK8r0v71pTUZsaXdaSnZBZzg>`__ 에서 다운받을 수 있습니다.
```

문서 전체적으로 외부 링크 뒤에 나오는 쉼표나 마침표가 그대로 반영되는 경우가 많은데요, 이 부분도 한 번 살펴봐주시면 좋을 것 같습니다.

2020-09-13 14:50 UTC, 9bow commented on beginner_source/dcgan_faces_tutorial.py
> +# 로 전파시킨다음 손실 (:math:`log(1-D(G(z)))`) 을 계산합니다. 그리고 * 축적된 * gradient
```suggestion
# 로 전파시킨다음 손실 (:math:`log(1-D(G(z)))`) 을 계산합니다. 그리고 *축적된* gradient
```

2020-11-15 12:20 UTC, 9bow commented
@JaeLee18 님, 혹시 위 내용에 대해서 확인 / 반영해주실 수 있으신지요?
어려우시다면 제가 임의로 병합 후 변경하도록 하겠습니다. ^^

2020-11-22 13:32 UTC, 9bow approved these changes
너무 오래 방치되어 있어 일단 임의로 병합 후 추가 커밋을 통해 변경토록 하겠습니다.

2020-11-22 13:33 UTC, merged

2021-04-11 11:36 UTC, 9bow commented
안녕하세요, @JaeLee18 님.
요 몇 달간 이 문서를 틈틈이 리뷰하고 있는데, 단어 및 문장 등에서 변경이 필요한 부분이 많고 v1.8 업데이트가 밀려있어 이 PR을 제외하고 되돌리려고 합니다. 이 문서에 계속적으로 기여를 하고 싶으시다면 추가적인 변경 사항을 적용하시어 다시금 PR 작성 부탁드립니다.
감사합니다.