Intermediate source/quantized transfer learning tutorial.rst
9bow/PyTorch-tutorials-kr pull request #143
Opened 2020-08-25 11:37 UTC by jjeamin

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [ ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #135

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

Intermediate source/quantized transfer learning tutorial.rst 번역

2020-08-28 00:39 UTC, hy21116 reviewed
문서가 길어 일단 중간까지만 리뷰 진행하고
추후 나머지 부분에 대해 다시 진행하도록 하겠습니다. :)

2020-08-28 00:39 UTC, hy21116 commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +   이는 네트워크가 이미 학습 되었기 때문에 수행되며 새로운 데이터셋으로 "미세조정(finetuning)"하려면 약간의 변경이 필요합니다.
```suggestion
   이는 네트워크가 이미 학습되었기 때문이며 새로운 데이터셋으로 "미세조정(finetuning)"하려면 약간의 변경만이 필요합니다.
```
아주 사소한 것이지만 `수행`이라는 말이 한국어로는 앞 문장과의 연결성을 해치는 것 같아 제안해보았습니다!
또, 저자가 이 문장을 쓴 이유가 '이미 학습된 모델에서 크게 벗어나지 않고 "미세"조정을 해야 하기 때문에 작은 learning rate를 사용해야 한다' 인 것 같아서 `only`를 강조하면 좋겠다고 생각했습니다. :)

2020-08-28 00:39 UTC, hy21116 commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +이번 파트에서는 양자화 된 모델을 사용하여 특징을 추출하는 첫번째 방법을 사용합니다.
```suggestion
이번 파트에서는 첫 번째 방법을 사용해 양자화 된 모델로 특징을 추출해봅시다.
```
`첫 번째 방법 == 양자화 된 모델로 특징 추출하기` 라는 오해의 소지가 생길 수 있어 보입니다. :)

2020-08-28 00:39 UTC, hy21116 commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>  ~~~~~~~~~
마찬가지로 위의 문장보다 더 길어야 합니다.  :)

2020-08-28 00:39 UTC, hy21116 commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +- 최적의 모델 저장합니다.
```suggestion
- 최적의 모델을 저장합니다.
```
오타인 것 같습니다 :)

2020-08-28 00:39 UTC, hy21116 commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>        Support function for model training.
이 부분은 의도적으로 남겨두신 건가요? :)

2020-08-28 00:39 UTC, hy21116 commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +      모델 학습을 위한 지원 함수
오 이 부분을 번역할 생각은 못했는데! 섬세하십니다.!! ㅎㅎ 👍

2020-08-28 00:39 UTC, hy21116 commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +일부 이미지에 대한 예측을 표시하는 일반 함수
```suggestion
일부 이미지에 대한 예측을 출력하는 일반 함수
```
`display`라는 단어가 이미지와 같이 쓰일 때는 `출력하다`로 표현되기도 해서 제안해봅니다. 
크게 의미를 해치지 않으니 안 바꾸셔도 됩니다. :)

2020-08-28 10:00 UTC, hy21116 reviewed
몇 가지 추가하였습니다.!!
저는 업무에서 주로 다루고 있는 분야인데도 막상 번역하려니 어렵네요 ㅜ
고생하셨습니다. :)

2020-08-29 07:56 UTC, codingbowoo reviewed
컨트리뷰톤 리뷰 하겠습니다 :)

2020-08-29 09:24 UTC, codingbowoo requested changes
컨트리뷰톤 리뷰 마쳤습니다. 오탈자나 띄어쓰기 오류 등에는 수정 제안만 적고 별도 코멘트를 적지는 않았습니다. 
긴 문서 번역하시느라 수고가 많으셨습니다!

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +학습합니다. 부동 소수점 모델과 다르게 양자화 된 모델에는 학습 가능한 매개 변수가 없으므로
```suggestion
학습합니다. 부동 소수점 모델과 다르게 양자화된 모델에는 학습 가능한 매개 변수가 없으므로
```
붙여야 하는지 띄어야 하는지보다는, 어떤 부분은 띄어쓰기를 하시고 어떤 부분은 하지 않으셔서 하나로 통일만 해주셔도 괜찮을 것 같습니다!

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +이 시점에서 미리 학습 된 모델을 수정해야합니다. 모델의 시작과 끝에는 양자화/역양자화 블록이 있습니다.
```suggestion
이 시점에서 미리 학습된 모델을 수정해야 합니다. 모델의 시작과 끝에는 양자화/역양자화 블록이 있습니다.
```

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +.. note:: 양자화 모델에서 특징 추출기를 분리할 때 양자화를 유지하려는 부분의 시작과 끝에 수동으로 양자화/역양자화를 배치해야합니다.
```suggestion
.. note:: 양자화 모델에서 특징 추출기를 분리할 때 양자화를 유지하려는 부분의 시작과 끝에 수동으로 양자화/역양자화를 배치해야 합니다.
```

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +아래 함수는 사용자 지정 헤드로 모델을 생성하는 함수 입니다.
```suggestion
아래 함수는 사용자 지정 헤드로 모델을 생성하는 함수입니다.
```

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +.. warning:: 현재 양자화 된 모델은 CPU에서만 실행할 수 있습니다.
양자화된/ 양자화 된 통일 확인 부탁드립니다 :)

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +얻을 수 있는 방법입니다. 특정한 예제에서는 학습용 셋은 매우 작기 때문에(120개의 이미지) 전체 모델을
```suggestion
미리 학습한 양자화 모델을 사용한다는 점입니다. 이번 파트에서, 우리는 관심있는 데이터셋으로 미세조정(Finetuning)한 후
양자화 된 특징 추출기를 생성하므로, 양자화의 장점을 가지면서 전이 학습(Transfer Learning)으로 더 나은 정확도를
얻을 수 있습니다. 특정한 예제에서는 학습용 셋은 매우 작기 때문에(120개의 이미지) 전체 모델을
```

마찬가지로 잔잔한 제안을 덧붙입니다.

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +미리 학습 된 특징 추출기는 양자화가 가능해야합니다.
```suggestion
미리 학습된 특징 추출기는 양자화가 가능해야 합니다.
```

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +(4) 단계로 모델을 "미세조정(Finetuning)"한 후 완전하게 양자화 된 버전(version)으로 변환 할 수 있습니다. (5 단계)
```suggestion
(4) 단계로 모델을 "미세조정(Finetuning)"한 후, 완전하게 양자화 된 버전으로 변환(5단계) 할 수 있습니다.
```
버전에 대해서는 version이라고 별도 표기하지 않아도 괜찮을 것 같습니다.
저 (Step 5)가 일관성이 없어서 고민하셨을 것 같습니다.. 나름의 수정 방안을 제안해봅니다.

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +미세조정(Finetuning) 모델을 양자화 된 모델로 변환하려면 ``torch.quantization.convert`` 함수를
양자화 된/ 양자화된

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +그러나 여기에 사용 된 작은 학습용 데이터셋으로 인해 학습용 셋에 과적합하게 됩니다.
```suggestion
그러나 여기서는 크기가 작은 학습용 데이터셋을 사용했기 때문에 결국 과적합하게 됩니다.
```
의미를 더 잘 전달하게끔 수정해 보았습니다!

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +    # 더 작은 Learning rate에 주목하세요
```suggestion
    # 더 작은 학습률을 사용함에 주목하세요.
```
learning rate를 학습률로 계속 사용하셔도 좋을 것 같습니다.

2020-08-29 09:24 UTC, codingbowoo commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +    # Learning rate를 매번 몇 에폭마다 0.3배 감소시키기
```suggestion
    # 학습률을 몇 에폭마다 0.3배 감소시키기
```
```마다```라는 보조사가 매번 이라는 의미도 포함하는 것 같습니다.

2020-08-31 03:07 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +(beta) 컴퓨터 비전(Vision)을 위한 양자화된 전이학습(Quantized Transfer Learning)
이건.. 일단 대기하겠습니다

2020-08-31 03:08 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +(beta) 컴퓨터 비전(Vision)을 위한 양자화된 전이학습(Quantized Transfer Learning)
`을 위한 양자화 전이학습`으로 수정해보겠습니다.

2020-08-31 03:09 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>  ========================================================================
네 감사합니다 튜토리얼 추가했습니다 ㅎㅎ

2020-08-31 03:10 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +   이는 네트워크가 이미 학습 되었기 때문에 수행되며 새로운 데이터셋으로 "미세조정(finetuning)"하려면 약간의 변경이 필요합니다.
좋은 수정 감사합니다 ㅎㅎ

2020-08-31 03:15 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>  ~~~~~~~~~
여기선 어떤 부분이 길어야하죠??

2020-08-31 03:16 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>        Support function for model training.
지우지를 못했네요 꼼꼼한 리뷰 감사합니다 ㅎㅎ

2020-08-31 03:18 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>  ---------------------------------------------------------------------------
여기선 어떤 부분이 길어야하죠??

2020-08-31 03:19 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +이 예제에서는 특징 추출기로 ``fc`` 를 사용해야하지만 실제로는 필요한 만큼 많은 부분을 사용할 수 있습니다.
네 맞습니다 ㅎㅎ 감사합니다

2020-08-31 03:23 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>  ---------------------------------------------------------------------------
여기서도 어떤 부분이 길어야하죠??

2020-08-31 03:24 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +1. **고정 된 특징 추출기로써 ConvNet**: 여기서는 마지막 몇개의 계층(일명 “헤드(the head)”, 일반적으로 완전히 연결된 계층(Fully Connected Layer))
애매한 부분은 일단 넣었는데 빼도 무방할 것 같습니다 ㅎㅎ

2020-08-31 03:24 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +   을 제외하고 네트워크의 모든 매개 변수 가중치를 `“고정(freeze)” <https://arxiv.org/abs/1706.04983>`_ 합니다.
네 맞습니다 ㅎㅎ 감사합니다

2020-08-31 03:25 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +2. **ConvNet 미세조정(Finetuning)**: 랜덤 초기화 대신에, 모델은 미리 학습된 네트워크를 사용하여 초기화 된 후,
좋은 코멘트 감사합니다 ㅎㅎ

2020-08-31 03:25 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +   마지막 계층은 임의의 가중치로 초기화된 새로운 계층으로 대체되며 오직 이 계층만 학습됩니다.
덕분에 번역을 자연스럽게 하는 것을 배워가는것 같습니다 ㅎㅎ

2020-08-31 03:26 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +    # Learning rate를 매번 몇 에폭마다 0.3배 감소시키기
네 감사합니다 ㅎㅎ

2020-08-31 03:27 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +    # 더 작은 Learning rate에 주목하세요
네 전부 그렇게 수정해야겠네요 ㅎㅎ

2020-08-31 03:27 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +미세조정(Finetuning) 모델을 양자화 된 모델로 변환하려면 ``torch.quantization.convert`` 함수를
감사합니다 ㅎㅎ

2020-08-31 03:30 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +   일반적으로 헤드(또는 그 일부)는 출력의 수가 다른 네트워크에서도 교체됩니다.
이부분은 저렇게하는게 자연스럽네요 ㅎㅎ

2020-08-31 03:31 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +.. warning:: 현재 양자화 된 모델은 CPU에서만 실행할 수 있습니다.
양자화된으로 통일하겠습니다

2020-08-31 03:35 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +.. note :: 이번 섹션은 원본 전이학습(Transfer Learning) 튜토리얼과 동일합니다.
네 맞습니다 1차 수정후 한번 쭉 훑어봐야겠습니다

2020-08-31 04:05 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +(beta) 컴퓨터 비전(Vision)을 위한 양자화된 전이학습(Quantized Transfer Learning)
`(beta) 컴퓨터 비전(Vision) 튜토리얼을 위한 양자화된 전이학습(Quantized Transfer Learning)`이 좋을 것 같네요

2020-08-31 04:06 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
> +데이터 불러오기 / 시각화와 같은 "전제 조건(prereqisites)"을 검토하겠습니다.
네 올려보겠습니다 ㅎㅎ

2020-09-01 15:33 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>  ~~~~~~~~~
일단 문제 없는 것 같아 닫겠습니다.

2020-09-01 15:34 UTC, jjeamin commented on intermediate_source/quantized_transfer_learning_tutorial.rst
>  ---------------------------------------------------------------------------
일단 문제 없는 것 같아 닫겠습니다.

2020-09-08 14:44 UTC, 9bow commented
고생 많으셨습니다! 👍

2020-09-08 14:44 UTC, 9bow approved these changes

2020-09-08 14:45 UTC, merged