Recipes/torchscript inference.rst 번역
9bow/PyTorch-tutorials-kr pull request #144
Opened 2020-08-26 11:36 UTC by hy21116

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [X] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #142 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
recipes/torchscript_inference.rst 를 번역하였습니다.

2020-08-28 18:24 UTC, codingbowoo reviewed
컨트리뷰톤 리뷰 하겠습니다.

2020-08-29 07:47 UTC, codingbowoo requested changes
컨트리뷰톤 리뷰입니다. 전반적으로 매끄럽고 읽기 편했습니다.

2020-08-29 07:47 UTC, codingbowoo commented on recipes_source/torchscript_inference.rst
> +두 모델에 똑같은 결과가 나오는 것을 확인할 수 있습니다:
```suggestion
두 모델의 결과가 동일함을 확인할 수 있습니다:
```
- '~한 것' 이라는 표현을 줄이기 위해 제안드립니다.
- 혹은 
```suggestion
두 모델이 같은 결과를 내는 것을 확인할 수 있습니다:
```
는 어떨까요?

2020-08-29 07:47 UTC, codingbowoo commented on recipes_source/torchscript_inference.rst
> +확인이 끝났으면 모델을 저장합니다:
```suggestion
검사가 끝났으면 모델을 저장합니다:
```
- sanity check의 check을 가리키는 것 같아서, 검사 라는 용어를 동일하게 사용하는 것이 어떨까요?
의미상으로는 확인이 끝나다도 자연스럽게 느껴지긴 합니다!

2020-08-29 08:35 UTC, hy21116 commented on recipes_source/torchscript_inference.rst
> +이 레시피에서는 다음과 같은 것들을 알아봅니다:
와우 좋네요. :+1: 감사합니다. 적용하겠습니다. :)

2020-08-29 08:35 UTC, hy21116 commented on recipes_source/torchscript_inference.rst
> +-  TorchScript란
동의합니다. 물음표를 붙이도록 하겠습니다. 감사합니다. :)

2020-08-29 08:36 UTC, hy21116 commented on recipes_source/torchscript_inference.rst
> +두 모델에 똑같은 결과가 나오는 것을 확인할 수 있습니다:
동의합니다.! 저도 모르게 `~것` 이라는 표현을 많이 쓰게 되더라구요ㅜ 
첫번째 표현으로 적용하도록 하겠습니다. 감사합니다. :)

2020-08-29 08:45 UTC, codingbowoo commented on recipes_source/torchscript_inference.rst
> +두 모델에 똑같은 결과가 나오는 것을 확인할 수 있습니다:
저도 그게 늘 고민스럽습니다 ㅎㅎ 감사합니다.

2020-08-29 08:49 UTC, hy21116 commented on recipes_source/torchscript_inference.rst
> +확인이 끝났으면 모델을 저장합니다:
좋은 의견이네요. :+1: @codingbowoo 님의 의견대로 더 자연스럽게 연결되려면 제가 `sanity check`를 `정밀 테스트`라고 표현한 부분도 `정밀 검사`라고 바꾸는게 좋겠습니다. 감사합니다. :)

2020-08-30 02:47 UTC, Gangsss reviewed
번역 고생하셨습니다!

2020-08-30 02:47 UTC, Gangsss commented on recipes_source/recipes_index.rst
> +   :header: TorchScript로 배포하기
```suggestion
   :header: 배포를 위한 TorchScript
```
두 말이 비슷해 보이는데 배포를 하기 위해 torchscript을 활용하는 것 같아 제안드렸습니다.

2020-09-08 00:49 UTC, creduo approved these changes
@hy21116 님 번역에 수고하셨습니다. @codingbowoo 님 @Gangsss 님 리뷰 감사드립니다.

2020-09-08 00:49 UTC, merged