recipes/zeroing out gradients.py 번역 (#120)
9bow/PyTorch-tutorials-kr pull request #146
Opened 2020-08-28 17:56 UTC by codingbowoo

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
- **이슈 번호**: #120 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
레시피 번역

2020-08-29 04:37 UTC, potatochips178 commented on recipes_source/recipes/zeroing_out_gradients.py
> +# 우리가 할 일은 데이터 이터레이터를 순회하면서, 신경망에 입력을 주고
'우리가'라는 말을 쓰지 않고 '해야할 일은'으로 번역하는 건 어떨가요? 다른 부분에서는 we를 딱히 번역하지 않았는데 여기서만 번역해서 전체적으로 비슷하게 맞춰 주려면 없어도 좋을 것 같습니다.

2020-08-29 04:37 UTC, potatochips178 commented on recipes_source/recipes/zeroing_out_gradients.py
> +        # 입력 받기; 데이터는 [inputs, labels] 형태의 리스트다.
'데이터는 [inputs, labels] 형태의 리스트' 라고 번역하는 건 어떨까요? 다른 주석은 명사형 어미로 끝나는데 여기만 종결어미로 끝나니까 살짝 어색해 보여서요.

2020-08-29 09:46 UTC, JaeLee18 commented
컨트리뷰톤 리뷰 진행하겠습니다.

2020-09-02 15:02 UTC, codingbowoo commented on recipes_source/recipes/zeroing_out_gradients.py
> +# 우리가 할 일은 데이터 이터레이터를 순회하면서, 신경망에 입력을 주고
오 생각해보지 못한 부분이에요 감사합니다 :) ```여기서 할 일은``` 으로 수정하려고 합니다!

2020-09-02 15:04 UTC, codingbowoo commented on recipes_source/recipes/zeroing_out_gradients.py
> +        # 입력 받기; 데이터는 [inputs, labels] 형태의 리스트다.
좋아요!

2020-09-04 10:01 UTC, JaeLee18 requested changes

2020-09-05 16:52 UTC, codingbowoo reviewed
@JaeLee18 @potatochips178 리뷰해주신 것 대부분 반영했습니다. 감사합니다. 👍

2020-09-05 16:52 UTC, codingbowoo commented on recipes_source/recipes/zeroing_out_gradients.py
> +신경망을 학습시킬 때, 경사 하강법을 거쳐 모델 정확도를 높일 수 있습니다. 경사 하강법은 간단히
```요컨대``` 번역할 때 구어체 느낌이 강해서 ```간단히 설명해```로 풀어 설명한 바 있습니다. **In short**는 역시 요컨대로 번역하는 것이 자연스러울까요?

(현재) 경사 하강법은 간단히 설명해 모델의 가중치와 편향을 약간씩 수정하면서 손실(또는 오류)를 최소화하는 과정입니다.
(수정) 요컨대, 경사 하강법은 모델의 가중치와 편향을 약간씩 수정하면서 손실(또는 오류)를 최소화하는 과정입니다.

2020-09-05 16:52 UTC, codingbowoo commented on recipes_source/recipes/zeroing_out_gradients.py
> +뒤따르는 모든 역전파 단계에서도 마찬가지입니다. 이 텐서의 변화도는 ``.grad`` 속성에 누적됩니다.
앞으로 일어날 역전파 단계니까 제안해 주신 ```누적될 것입니다```가 좋을 것 같네요. 아래와 같이 수정하겠습니다.

뒤따르는 모든 역전파 단계에서도 마찬가지로 이 텐서의 변화도는 ``.grad`` 속성에 누적될 것입니다.

2020-09-05 16:52 UTC, codingbowoo commented on recipes_source/recipes/zeroing_out_gradients.py
> +텐서의 변화도를 0으로 만들어 주어야 하는 경우도 있습니다. 예를 들어 학습 과정 전체를 반복하기
이부분 고민을 했었는데, 간결하고 쉽게 전달되는 것 같습니다. 감사합니다.

2020-09-07 16:25 UTC, creduo commented on recipes_source/recipes/zeroing_out_gradients.py
> +신경망을 학습시킬 때, 경사 하강법을 거쳐 모델 정확도를 높일 수 있습니다. 경사 하강법은 간단히
앞에서 경사하강법의 설명이 진지하게 붙었고 그를 요약한다면 요컨대가 맞을 것 같지만, 여기서는 요컨대 보다는 간단히 설명하여 등의 표현이 좀더 자연스러운것 같습니다.

2020-09-07 16:27 UTC, creduo approved these changes
@codingbowoo 님 번역에 수고하셨습니다. @potatochips178 님, @JaeLee18 님 리뷰 감사드립니다.

2020-09-07 16:28 UTC, merged