Beginner source/blitz/neural networks tutorial.py 번역 개선(#81)
9bow/PyTorch-tutorials-kr pull request #150
Opened 2020-09-03 16:36 UTC by codingbowoo

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #81 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [x] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
1. 오탈자 수정이 있습니다.
2. 번역하지 않은 코드블럭 내 주석을 번역했습니다.

2020-09-11 12:26 UTC, itsnamgyu requested changes
표현 너무 깔끄미에여 🐤🐤

2020-09-11 12:26 UTC, itsnamgyu commented on beginner_source/blitz/neural_networks_tutorial.py
> +        # (2, 2) 크기 윈도우에 대해 맥스 풀링(Max pooling)
```suggestion
        # (2, 2) 크기 윈도우에 대해 맥스 풀링(max pooling)
```

고유 명사가 아니므로 영어 문장의 대소문자 법을 따르면 좋을 것 같습니다 🦕

2020-09-12 02:48 UTC, codingbowoo commented on beginner_source/blitz/neural_networks_tutorial.py
> +        # (2, 2) 크기 윈도우에 대해 맥스 풀링(Max pooling)
오 좋습니다! 반영하겠습니다 :>

2020-09-13 14:58 UTC, 9bow requested changes
깔끔한 번역 감사합니다 👍 
기존 문서를 제가 번역했어서, 기존 번역과의 용어 차이를 한 번만 더 검토 부탁드립니다. (_ _)
(변경 없이 반영을 원하실 경우에는 덧글 남겨주시면 반영하도록 하겠습니다~)

2020-09-13 14:58 UTC, 9bow commented on beginner_source/blitz/neural_networks_tutorial.py
> +  ``새로운 가중치(weight) = 가중치(weight) - 학습율(learning rate) * 변화도(gradient)``
👍

2020-09-13 14:58 UTC, 9bow commented on beginner_source/blitz/neural_networks_tutorial.py
> +        # 아핀 연산: y = Wx + b
문서 상에 처음으로 등장하는 용어라, 아래와 같은 식은 어떨까요?
```suggestion
        # 아핀(affine) 연산: y = Wx + b
```

2020-09-13 14:58 UTC, 9bow commented on beginner_source/blitz/neural_networks_tutorial.py
> +target = torch.randn(10)  # 예시를 위한 더미 target
기존에 문서 상에서는 target을 정답으로 번역했었는데요, 여기에서는 target이 변수명이라기보다는 `가짜 정답`을 뜻하는 것 같아서 요 부분도 함께 번역해주시면 어떨까 싶습니다. :)

2020-09-13 14:58 UTC, 9bow commented on beginner_source/blitz/neural_networks_tutorial.py
> +net.zero_grad()     # 모든 파라미터의 변화도 버퍼를 0으로 만듦
기존 문서 상에서는 parameter를 `매개변수`로 번역했었는데요, 한 번 검토 부탁드립니다 (_ _)

2020-09-23 11:13 UTC, codingbowoo commented on beginner_source/blitz/neural_networks_tutorial.py
> +        # 아핀 연산: y = Wx + b
좋습니다! 추가하였습니다 👍

2020-09-23 11:13 UTC, codingbowoo commented on beginner_source/blitz/neural_networks_tutorial.py
> +net.zero_grad()     # 모든 파라미터의 변화도 버퍼를 0으로 만듦
반영하였습니다 :>

2020-09-23 11:20 UTC, codingbowoo commented on beginner_source/blitz/neural_networks_tutorial.py
> +target = torch.randn(10)  # 예시를 위한 더미 target
해당 부분에서 target이 output과 비교해 loss를 비교할 실제 정답에 해당하니까, ```가짜 정답``` 이라는 표현이 조금 애매한 것도 같아요. 
```예시를 위해 임시로 생성한 정답```으로 번역하는 것은 어떨까요?

2020-09-25 05:38 UTC, 9bow commented on beginner_source/blitz/neural_networks_tutorial.py
> +target = torch.randn(10)  # 예시를 위한 더미 target
둘 다 좋은 것 같습니다! 👍

2020-09-25 13:46 UTC, 9bow approved these changes

2020-09-25 13:47 UTC, 9bow commented
`dummy target` 부분만 정리 부탁드립니다. :)

2020-09-27 13:37 UTC, merged

2020-09-27 13:37 UTC, 9bow commented
감사합니다! 👍