Translated ONNXLive Issue #153
9bow/PyTorch-tutorials-kr pull request #154
Opened 2020-09-08 08:44 UTC by JaeLee18

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #153

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_ONNXLive 번역_

2020-09-08 11:12 UTC, kypark7 reviewed
컨트리뷰톤 리뷰 진행하였습니다

2020-09-08 11:12 UTC, kypark7 commented on advanced_source/ONNXLive.rst
> +이제 우리는 미리 훈련된 PyTorch 모델들을 ``.pth`` 파일로 ``saved_models`` 폴더에 가지고 있어서 나중에 저 모델들을 ONNX 형식으로 변환 할 수 있습니다.
```suggestion
이제 우리는 미리 훈련된 PyTorch 모델들을  ``saved_models`` 폴더에 ``.pth`` 파일로 가지고 있어서 나중에 저 모델들을 ONNX 형식으로 변환 할 수 있습니다.
```
는 어떠신가요?

2020-09-08 11:12 UTC, kypark7 commented on advanced_source/ONNXLive.rst
> +위의 과정을 거치면 4개의 파일 ``candy.onnx``\ , ``mosaic.onnx``\ , ``rain_princess.onnx`` 그리고 ``udnie.onnx``\,
```suggestion
위의 과정을 거치면 4개의 파일 ``candy.onnx``\ , ``mosaic.onnx``\ , ``rain_princess.onnx`` 그리고 ``udnie.onnx``\ ,
```

2020-09-08 11:12 UTC, kypark7 commented on advanced_source/ONNXLive.rst
> +이제 실행시켜봅시다.
```suggestion
이제 실행시켜봅시다:
```

2020-09-08 11:12 UTC, kypark7 commented on advanced_source/ONNXLive.rst
> +이 저장소(README.md를 읽고 계시는 현재의 저장소)는 CoreML style transfer 모델들을 핸드폰 카메라로 실시간 카메라 스트림을 이용하여 실행할 수 있는 iOS 앱을 포함하고 있습니다. 이제 저장소를 클론해봅시다.
```suggestion
이 저장소(README.md를 읽고 계시는 현재의 저장소)는 CoreML style transfer 모델들을 핸드폰 카메라로 실시간 카메라 스트림을 이용하여 실행할 수 있는 iOS 앱을 포함하고 있습니다. 이제 저장소를 클론해봅시다:
```

2020-09-10 20:32 UTC, ajin-jng commented
컨트리뷰톤 리뷰하겠습니다 :)

2020-09-10 20:40 UTC, ajin-jng approved these changes
수고하셨습니다 :)

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +ONNX는 AI 개발자들이 최첨단의 도구들과 모델들의 조합을 그들에게 가장 잘 맞는것을 쉽게 선택하도록 해줍니다.
```suggestion
ONNX는 AI 개발자들이 최첨단의 도구들과 모델들의 조합을 그들에게 가장 잘 맞는 것을 쉽게 선택하도록 해줍니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +이번 튜토리얼에서 4가지 중심 사항들을 소개해드리겠습니다.
```suggestion
이번 튜토리얼에서는 4가지 중심 사항들을 소개해드리겠습니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +현재 로컬에 설치되어있는 패키지들과의 충돌을 피하기 위해 virtualenv를 사용하겠습니다.
```suggestion
현재 로컬에 설치되어있는 패키지들과의 충돌을 피하고자 virtualenv를 사용하겠습니다.
```
'피하기 위해' 보다는 '피하고자' 가 더 자연스러운 듯 합니다

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +iOS style transfer 어플리케이션을 iPhone에 작동 시키고 싶다면 XCode 또한 설치 되어야 합니다.
```suggestion
iOS style transfer 어플리케이션을 iPhone에 작동시키고 싶다면 XCode 또한 설치 되어야 합니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +iOS style transfer 어플리케이션을 iPhone에 작동 시키고 싶다면 XCode 또한 설치 되어야 합니다.
```suggestion
iOS style transfer 어플리케이션을 iPhone에 작동 시키고 싶다면 XCode 또한 설치되어야 합니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +모델을 변환하는것은 Linux 에서도 가능하지만 iOS 어플리케이션을 작동시키고 싶다면 Mac이 필요합니다.
```suggestion
모델을 변환하는 것은 Linux 에서도 가능하지만 iOS 어플리케이션을 작동시키고 싶다면 Mac이 필요합니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +이번 튜토리얼 에서는 우리는 https://github.com/pytorch/examples/tree/master/fast_neural_style 에  PyTorch 로 만들어진 style transfer 을 이용하겠습니다.
```suggestion
이번 튜토리얼에서 우리는 https://github.com/pytorch/examples/tree/master/fast_neural_style 에  PyTorch 로 만들어진 style transfer 을 이용하겠습니다.
```
자연스럽게 수정하였습니다

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +이 모델들은 이미지에 style transfer 가 적용되도록 만들어져서 비디오에 적용하기에는 최적화가 되어있지 않아 충분히 빠르지 않습니다.
```suggestion
이 모델들은 이미지에 style transfer 가 적용되도록 만들어져서 비디오에 적용하기에는 최적화가 되어있지 않아 아주 빠르지 않습니다.
```
'충분히 빠르지' 는 조금 부자연스러운 표현인듯 해 '아주 빠르지'로 고쳤는데 다른 단어가 있을까요?

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +하지만 해상도를 어느정도 낮춘다면 비디오에서 충분한 속도에 작동됩니다.
```suggestion
하지만 해상도를 어느 정도 낮춘다면 비디오에서 충분한 속도에 작동됩니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +이렇기 때문에 입력값으로 style transfer 를 적용할 이미지가 입력값으로 필요하며 기본적인 비어있는 이미지여도 됩니다.
```suggestion
이러므로 입력값으로 style transfer 를 적용할 이미지가 입력값으로 필요하며 기본적인 비어있는 이미지여도 됩니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +좋은 퍼포먼스를 얻기 위해 우리는 250x540 의 해상도를 사용할 예정입니다. FPS보다 style transfer의 품질에 더 많이 신경쓰신다면 더 큰 해상도를 사용하셔도 됩니다.
```suggestion
좋은 퍼포먼스를 얻기 위해 우리는 250x540 의 해상도를 사용할 예정입니다. FPS보다 style transfer의 품질에 더 많이 신경 쓰신다면 더 큰 해상도를 사용하셔도 됩니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +가 ``.pth`` 파일들에 각각 대응되어 생성되어있어야합니다.
```suggestion
가 ``.pth`` 파일들에 각각 대응되어 생성되어있어야 합니다.
```

2020-09-10 20:40 UTC, ajin-jng commented on advanced_source/ONNXLive.rst
> +우리는 이러한 값들을 이미지로서 표시해야합니다.
```suggestion
우리는 이러한 값들을 이미지로써 표시해야합니다.
```

2020-10-08 02:09 UTC, creduo requested changes

2020-10-08 02:09 UTC, creduo commented on advanced_source/ONNXLive.rst
> +iOS style transfer 어플리케이션을 iPhone에 작동 시키고 싶다면 XCode 또한 설치 되어야 합니다.
```suggestion
iPhone 에서 iOS style transfer 어플리케이션을 실행하려면 XCode 가 필요합니다.
```

2020-10-08 02:09 UTC, creduo commented on advanced_source/ONNXLive.rst
> +모델을 변환하는것은 Linux 에서도 가능하지만 iOS 어플리케이션을 작동시키고 싶다면 Mac이 필요합니다.
```suggestion
Linux 에서도 모델을 변환할 수 있지만, iOS 어플리케이션을 실행 하려면 Mac 이 필요합니다.
```

2020-10-08 02:12 UTC, creduo approved these changes

2020-10-08 02:14 UTC, merged