Transl static_quantization_tutorial.py (#148)
9bow/PyTorch-tutorials-kr pull request #155
Opened 2020-09-08 12:10 UTC by potatochips178

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #148

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
advanced_source/static_quantization_tutorial.py 번역

2020-09-11 02:24 UTC, JaeLee18 requested changes
Suggested Korean Translations

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +(실험용) PyTorch에서 eager mode로 실행하는 정적 양자화
```suggestion
(실험용) PyTorch에서 Eager Mode로 실행하는 정적 양자화 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +주의: ``MobileNetV2`` 모델 구조 정의하기, 데이터 로더 정의하기 등과 같은 다른 PyTorch 레포지토리에서 공통으로 사용되는 많은 코드를 사용할 예정입니다.
```suggestion
주의: ``MobileNetV2`` 모델 구조 정의하기, 데이터 로더 정의하기 등과 같은 다른 PyTorch 저장소에서 공통으로 사용되는 많은 코드를 사용할 예정입니다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +물론 사용자들이 이것을 읽기 바랍니다. 그러나 만약 양자화 특징을 얻길 원한다면 자유롭게 건너뛰고 "4. 훈련 후 정적 양자화" 부분으로 넘어가면 됩니다.
```suggestion
처음부터 읽으면 좋지만 양자화 특징에 대해 알고싶다면 "4. 훈련 후 정적 양자화" 부분으로 넘어가면 됩니다. 
```

의역을 넣어 좀더 매끄럽게 만들어보았습니다.

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# # warnings 만들기
```suggestion
# # warnings  설정
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 노트: 이 코드는 `이곳에서 <https://github.com/pytorch/vision/blob/master/torchvision/models/mobilenet.py>`_ 가져왔습니다.
```suggestion
# 알림: 이 코드는 `이곳에서 <https://github.com/pytorch/vision/blob/master/torchvision/models/mobilenet.py>`_ 가져왔습니다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +    이 함수는 원본 ts repo에서 가져왔습니다.
```suggestion
    이 함수는 원본 Tensorflow 저장소에서 가져왔습니다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +(실험용) PyTorch에서 eager mode로 실행하는 정적 양자화
```suggestion
(실험용) PyTorch에서 Eager Mode로 실행하는 정적 양자화 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +주의: ``MobileNetV2`` 모델 구조 정의하기, 데이터 로더 정의하기 등과 같은 다른 PyTorch 레포지토리에서 공통으로 사용되는 많은 코드를 사용할 예정입니다.
```suggestion
주의: ``MobileNetV2`` 모델 구조 정의하기, 데이터 로더 정의하기 등과 같은 다른 PyTorch 저장소에서 공통으로 사용되는 많은 코드를 사용할 예정입니다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +물론 사용자들이 이것을 읽기 바랍니다. 그러나 만약 양자화 특징을 얻길 원한다면 자유롭게 건너뛰고 "4. 훈련 후 정적 양자화" 부분으로 넘어가면 됩니다.
```suggestion
사용자들이 처음부터 읽으면 좋지만 양자화 특징에 대해 알고싶다면 "4. 훈련 후 정적 양자화" 부분으로 넘어가면 됩니다. 
```
의역을 추가했습니다.

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# # warnings 만들기
```suggestion
# # warnings 설정
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +    이 함수는 원본 ts repo에서 가져왔습니다.
```suggestion
    이 함수는 원본 tensorflow 저장소에서 가져왔습니다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +        #  반전된 나머지 블락 만들기
```suggestion
        #  반전된 나머지 블락(residual block) 만들기
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +    # 이 연산자는 숫자를 변경하지 않음
```suggestion
    # 이 작업은 수식을 변경하지 않음
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 이것이 비교할 기준이 됩니다. 다음으로, 다른 양자화 방법을 사용해봅시다.
```suggestion
# 이 모델이 비교할 기준이 됩니다. 다음으로, 다른 양자화 방법을 사용해봅시다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 훈련 후 정적 양자화는 동적 양자화처럼 가중치를 실수에서 정수로 변환하는 것을 포함할 뿐 아니라 추가적인 첫 번째 피딩 네트워크를 지나가는 데이터의 배치 단계의 수행과 다른 활성값의 분산 결과 계산이 필요합니다
```suggestion
# 훈련 후 정적 양자화는 동적 양자화처럼 가중치를 실수에서 정수로 변환하는 것을 포함할 뿐 아니라 추가적인 첫 번째 피딩(feeding) 네트워크를 지나가는 데이터의 배치 단계의 수행과 다른 활성값의 분산 결과 계산이 필요합니다
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 중요하게, 이 추가적인 단계는 양자화된 값이 모든 연산 사이에서 실수로 변환하는 것 대신 - 그리고 다시 정수로 돌아감 - 이 값들이 연산들을 지나갈 수 있도록 만들어 상당한 속도 향상을 이룹니다.
```suggestion
# 특히, 이 추가적인 단계는 양자화된 값이 모든 연산 사이에서 실수로 변환하는 것 대신 - 그리고 다시 정수로 돌아감 - 이 값들이 연산들을 지나갈 수 있도록 만들어 상당한 속도 향상을 이룹니다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 첫번째 측정
```suggestion
# 첫번째 보정
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 트레이닝 셋과 대응시키기
```suggestion
# 트레이닝 셋으로 보정하기
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 양자화된 모델을 위해, 같은 300개 이미지에 대해서 62% 이하인 상당히 낮은 정확성을 보겠습니다.
```suggestion
# 양자화된 모델은 같은 300개 이미지에 대해서 62% 이하인 상당히 낮은 정확성을 보입니다.
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 그럼에도 불구하고, 모델의 사이즈를 거의 4x 정도가 줄은 3.6 MB 이하로 감소시켰습니다.
```suggestion
# 그럼에도 불구하고, 모델의 사이즈를 거의 4배 정도가 줄은 3.6 MB 이하로 감소시켰습니다.
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 추가적으로, 단순히 다른 양자화 형태를 사용하면 정확성을 꽤 향살시킬 수 있습니다.
```suggestion
# 추가적으로, 단순히 다른 양자화 형태를 사용하면 정확도를 많이 향상시킬 수 있습니다. 
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# - 활성값의 히스토그램을 모으는 히스그램 옵저버(observer)를 사용해 최선의 방법인 양자화 파라미터를 고릅니다.
```suggestion
# - 활성값의 히스토그램을 모으는 히스그램 옵저버(observer)를 사용해 최선의 방법인 양자화 매개변수를 고릅니다.
```

2020-09-11 02:24 UTC, JaeLee18 commented on advanced_source/static_quantization_tutorial.py
> +# 단지 이 양자화 형태 메소드를 바꾸는 것만으로 76%의 정확성 증가가 나옵니다!
```suggestion
# 단지 이 양자화 형태 메소드를 바꾸는 것만으로 76%의 정확도 증가라는 결과가 나옵니다!
```

2020-09-11 12:23 UTC, itsnamgyu requested changes
띄어쓰기 및 오탈자, 표현 관련해서 피드백 남겨드립니다. 특히 batch norm (배치 정규화)에서 쓰이는 데이터의 평균, 분산 수치에 관한 설명 몇가지 수정했습니다. 수고하셨습니다!!

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +        #  반전된 나머지 블락 만들기
```suggestion
        # 반전된 나머지 블락(residual block) 만들기
```

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +        # 나머지 여러 계층들 만들기
```suggestion
        # 나머지 계층 만들기
```

국문에서는 복수 형태가 조금 부자연스러운 것 같습니다.

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +# 이 튜토리얼에서 만드는 특정한 데이터셋은 ImageNet 데이터에서 1000개의 이미지들을 포함하고 이미지는 각 클래스로부터 옵니다.
```suggestion
# 이 튜토리얼에서 만드는 데이터셋은 ImageNet 데이터 안의 1000개 클래스에 대해, 클래스별로 각각 1장의 이미지를 포함하고 있습니다.
```

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +# 반면에, 전체 ImageNet 데이터셋을 사용해 이 튜토리얼에 있는 코드를 실행하기 위해서는 `여기서 <https://pytorch.org/docs/stable/torchvision/datasets.html#imagenet>`_ ``torchvision`` 을 사용한 데이터를 다운받아야 합니다.
```suggestion
# 반면에, 전체 ImageNet 데이터셋을 사용해 이 튜토리얼에 있는 코드를 실행하기 위해서는 `여기서 <https://pytorch.org/docs/stable/torchvision/datasets.html#imagenet>`_ ``torchvision`` 을 이용하여 데이터를 다운받을 수 있습니다.
```

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +# 다음으로, "모델 혼합"을 하겠습니다; 이것은 정확도를 향상시키는 동시에 메모리 접근을 줄여 모델을 빠르게 만듭니다.
```suggestion
# 다음으로, "모델 혼합"을 하겠습니다. 이것은 정확도를 향상시키는 동시에 메모리 접근을 줄여 모델을 빠르게 만듭니다. 
```

;가 국문에서 자주 사용하기 않은 기호라 마침표로 대체하는 것이 더 자연스러울 것 같습니다.

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +# 모델이 14.0 MB밖에 되지 않는다는 것에 비해 ImageNet의 확실한 기준을 가진 300개의 이미지에서 78%의 정확도를 볼 수 있습니다.
```suggestion
# 모델이 14.0 MB밖에 되지 않는다는 것에 비해 300개의 이미지에서 78%의 정확도를 볼 수 있습니다. ImageNet에서 괜찮은 성능이라고 할 수 있습니다.
```

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +# 즉,  실수 값은 int8 값과 유사하게 반올림되지만 모든 계산들은 부동소수점 수로 진행됩니다.
```suggestion
# 즉, 실수 값은 int8 값과 유사하게 반올림되지만 모든 계산들은 부동소수점 수로 진행됩니다.
```

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +# 높은 정확성을 가진 양자화된 모델을 훈련하기는 추론을 통한 정확한 숫자 모델링을 요구합니다.
```suggestion
# 높은 정확성을 가진 양자화된 모델을 훈련하려면 추론 시에 정확한 숫자 모델링을 요구합니다. 
```

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +# - 추론 수치와 더 많은 일치를 위해 배치 기준을 실행하는 동안 훈련의 마지막을 향하는 평균과 분산을 사용하는 것으로 변경니다.
```suggestion
# - 추론 수치와 더 많은 일치를 위해 훈련의 후반부에는 추론 시와 동일하게 배치 정규화에 쓰이는 평균과 분산 값을 이동 평균으로써 산출합니다.
```

2020-09-11 12:23 UTC, itsnamgyu commented on advanced_source/static_quantization_tutorial.py
> +        # 배치 기준을 평균과 분산 측정으로 고정하기
```suggestion
        # 배치 정규화에 쓰이는 평균과 분산 수치 고정하기
```

2020-09-13 08:01 UTC, potatochips178 commented on advanced_source/static_quantization_tutorial.py
> +# 첫번째 측정
왜 이렇게 수정했는지 알 수 있을까요?

2020-09-13 08:07 UTC, potatochips178 commented on advanced_source/static_quantization_tutorial.py
> +게다가 `여기서 <https://arxiv.org/abs/1806.08342>`_ 보인 발전된 양자화 기술들을 쉽게 적용시키는 법을 볼 수 있을 것이며 양자화된 모델들은 그렇지 않은 모델보다 훨씬 더 적은 정확성 일치를 가집니다.
이 부분을 번역하면서 의미가 전체적인 부분과 반대돼서 이상하다고 생각했는데 좋은 리뷰 감사합니다

2020-09-13 08:11 UTC, potatochips178 commented on advanced_source/static_quantization_tutorial.py
> +        # 나머지 여러 계층들 만들기
원문의 정확한 의미 파악을 위해 복수형으로 번역하는 게 나을 것같습니다.

2020-09-13 08:21 UTC, potatochips178 commented
꼼꼼한 리뷰 감사합니다!

2020-09-21 09:17 UTC, kwonmha reviewed
static_quantization_tutorial 리뷰했습니다.
긴 글 번역하시느라 수고하셨습니다.

2020-09-21 09:17 UTC, kwonmha commented on advanced_source/static_quantization_tutorial.py
> +# 부동소수점 모델과 양자화된 모델을 비교 했습니다.
```suggestion
# 맥북프로에서 로컬로 이것을 실행하면 보통 모델에 대해서 61ms 가, 양자화된 모델에서는 20ms가 걸리며 이는 양자화된 모델을 부동소수점 모델과 비교했을 때 평균적으로 2-4x 정도 속도가 오른 것을 설명합니다. 
```

2020-09-22 04:48 UTC, kwonmha reviewed
몇 개 번역투의 문장을 고쳐봤습니다.
수고하셨습니다.

2020-09-22 04:48 UTC, kwonmha commented on intermediate_source/memory_format_tutorial.py
> +# 가장 중요한 성능 향상은 Tensor Cores 지원과 함께하는 NVidia의 하드웨어에서 관찰됩니다.
```suggestion
# Tensor Cores를 지원하는 NVidia의 하드웨어에서 성능이 가장 많이 향상됩니다. 
```

2020-09-22 04:48 UTC, kwonmha commented on intermediate_source/memory_format_tutorial.py
> +# NVidia https://github.com/NVIDIA/apex 가 지원하는 스크립트를 훈련하는 AMP(Automated Mixed Precision)를 실행시키는 동안 22% 넘는 성능향상을 이룰 수 있습니다.
```suggestion
# NVidia https://github.com/NVIDIA/apex 가 제공하는 AMP(Automated Mixed Precision) 훈련 스크립트를 실행시키는 동안 22% 넘는 성능향상을 이룰 수 있습니다. 
```

2020-09-22 04:48 UTC, kwonmha commented on intermediate_source/memory_format_tutorial.py
> +# ``--channels-last true`` 를 지나가는 것은 22% 성능향상을 보이며 Channels Lasst 형식을 가진 모델을 실행시키는 것을 허용합니다.
```suggestion
# ``--channels-last true`` 를 넘겨주면 22% 성능향상을 보이며 Channels Last 형식을 가진 모델을 실행시킵니다. 
```

2021-11-07 12:58 UTC, hyoyoung commented
feedback이 없어서 pr을 close합니다.
필요할때 열어주시거나 새로 생성하여주세요.

2021-11-07 12:58 UTC, closed without merging