advanced_source/dynamic_quantization_tutorial.py
9bow/PyTorch-tutorials-kr pull request #156
Opened 2020-09-08 14:58 UTC by kypark7

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #136 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
dynamic_quantization_tutorial.py 번역

2020-09-11 11:34 UTC, itsnamgyu commented on advanced_source/dynamic_quantization_tutorial.py
> +추론(inference)할 수 있습니다.
```suggestion
```

2020-09-11 11:50 UTC, itsnamgyu requested changes
몇가지 오탈자 및 띄어쓰기, 그리고 표현 관련해서 수정 사항 남겨드렸습니다! 수고하셨습니다!

2020-09-11 11:50 UTC, itsnamgyu commented on advanced_source/dynamic_quantization_tutorial.py
> +이는 작은 적중률만으로 모델 크기를 줄이고 더 빠르게
```suggestion
적중률에 주는 타격을 최소화하면서 모델 크기를 줄이고 추론(inference) 속도를 높일 수 있습니다.
```

2020-09-11 11:50 UTC, itsnamgyu commented on advanced_source/dynamic_quantization_tutorial.py
> +LSTM 기반 next word-prediction 모델에 가장 쉬운 형태인 -
```suggestion
LSTM 기반 next word-prediction 모델의 가장 쉬운 형태인 -
```

2020-09-11 11:50 UTC, itsnamgyu commented on advanced_source/dynamic_quantization_tutorial.py
> +        # 파일 콘텐츠 토근화
```suggestion
        # 파일 내용 토큰화
```

2020-09-11 11:50 UTC, itsnamgyu commented on advanced_source/dynamic_quantization_tutorial.py
> +# 로드할 것 입니다; 이 가중치는 word language 모델 예제의 기본 설정을
```suggestion
# 로드할 것 입니다. 이 가중치는 word language 모델 예제의 기본 설정을
```

;가 국문에서 자주 쓰이는 기호가 아니라서 마침표로 대체하는 것이 좀더 자연스러울것 같습니다!

2020-09-11 11:50 UTC, itsnamgyu commented on advanced_source/dynamic_quantization_tutorial.py
> +    # 드랍아웃을 비활성화하는 평가모드 키기
```suggestion
    # 드랍아웃을 비활성화하는 평가모드 켜기
```

2020-09-11 11:50 UTC, itsnamgyu commented on advanced_source/dynamic_quantization_tutorial.py
> +# 모델은 동일하게 보입니다; 이것이 어떤 이득을 주는 것일까요? 첫째, 모델 크기가
```suggestion
# 모델은 동일하게 보입니다. 이것이 어떤 이득을 주는 것일까요? 첫째, 모델 크기가
```

위와 동일한 유형입니다.

2020-09-12 08:48 UTC, potatochips178 reviewed
번역하시느라 고생하셨습니다.

2020-09-12 08:48 UTC, potatochips178 commented on advanced_source/dynamic_quantization_tutorial.py
> +    # 데이터셋을 bsz 부분으로 얼마나 깔끔하게 나눌 수 있는지 계산해봅니다.
```suggestion
    # 데이터셋을 bsz 부분으로 얼마나 깔끔하게 나눌 수 있는지 계산합니다.
```
전체적인 어조와 비슷하게 수정했습니다

2020-09-12 08:48 UTC, potatochips178 commented on advanced_source/dynamic_quantization_tutorial.py
> +# 모델은 동일하게 보입니다. 이것이 어떤 이득을 주는 것일까요? 첫째, 모델 크기가
```suggestion
# 모델은 동일하게 보입니다. 이것이 어떻게 이득을 주는 것일까요? 첫째, 모델 크기가
```

2020-09-23 05:12 UTC, Justin-A reviewed
컨트리뷰톤 리뷰 진행하겠습니다. 번역하시느라 고생 많으셨습니다!

2020-09-23 05:16 UTC, Justin-A reviewed
컨트리뷰톤 리뷰 진행하겠습니다. 번역하시느라 고생 많으셨습니다!

2020-09-23 05:16 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +        """텍스트 파일 토큰화"""
토큰화라는 표현도 좋지만, 번역되었다기엔 조금 애매하지 않을까요? 토큰 단위로 나누는 과정 같은 표현은 어떠세요?

2020-09-23 05:16 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +        # 파일 내용 토큰화
토큰화라는 표현도 좋지만, 번역되었다기엔 조금 애매하지 않을까요? 토큰 단위로 나누는 과정 같은 표현은 어떠세요?

2020-09-23 05:16 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +    # 깔끔하게 맞지 않는 추가적인 부분(나머지들)을 잘라냅니다.
잘라낸다는 표현보다는 제거한다는 표현이 어떠세요?

2020-09-23 05:16 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +# 평가 기능
평가 기능보단, 평가 함수 정의가 좋아보입니다!

2020-12-03 08:29 UTC, creduo approved these changes
이 PR을 먼저 머지하고 #173 을 머지할 예정입니다.

2020-12-03 08:30 UTC, merged