Update numpy_extensions_tutorial.py #141
9bow/PyTorch-tutorials-kr pull request #157
Opened 2020-09-08 20:09 UTC by ajin-jng

번역

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #(숫자)
#141 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
번역

2020-09-11 11:33 UTC, itsnamgyu requested changes
띄어쓰기 오류 (혹은 불필요한 경우) 몇가지 수정하고, 좀더 자연스러운 표현 몇가지 추천드립니다. 수고하셨습니다!

2020-09-11 11:33 UTC, itsnamgyu commented on advanced_source/numpy_extensions_tutorial.py
> +이번 튜토리얼에서는 두가지 작업을 수행할 것 입니다:
```suggestion
이번 튜토리얼에서는 두 가지 작업을 수행할 것입니다:
```

2020-09-11 11:33 UTC, itsnamgyu commented on advanced_source/numpy_extensions_tutorial.py
> +# ** 생성 된 레이어의 사용 예시 : **
```suggestion
# **생성된 레이어의 사용 예시:**
```

2020-09-11 11:33 UTC, itsnamgyu commented on advanced_source/numpy_extensions_tutorial.py
> +# 딥 러닝 문헌에서이 레이어는 혼동스럽게도 컨볼 루션이라고하며 실제 연산은 상호 상관입니다.
```suggestion
# 딥러닝 문헌에서 이 레이어는 혼동스럽게도 컨볼루션이라고 칭하지만 실제로는 상호 상관 연산입니다.
```

2020-09-11 11:33 UTC, itsnamgyu commented on advanced_source/numpy_extensions_tutorial.py
> +# (유일한 차이점은 교차 상관의 경우가 아닌 회선에 대해 필터가 뒤집힌다는 것입니다).
```suggestion
# (컨벌루션과 상호 상관의 유일한 차이점은 컨벌루션에서는 필터를 뒤집어서 연산을 한다는 것입니다).
```

2020-09-11 11:33 UTC, itsnamgyu commented on advanced_source/numpy_extensions_tutorial.py
> +# 교차 상관이 가중치를 나타내는 필터 (커널)를 갖는 학습 가능한 가중치가있는 계층의 구현.
```suggestion
# 학습 가능한 가중치를 가진 필터 (커널)을 갖는 교차 상관 연산 계층의 구현
```

2020-09-11 11:33 UTC, itsnamgyu commented on advanced_source/numpy_extensions_tutorial.py
> +# **기울기 :**
```suggestion
# **기울기 확인:**
```

2020-09-11 13:10 UTC, kypark7 reviewed
컨트리뷰톤 리뷰 진행하였습니다!

2020-09-11 13:10 UTC, kypark7 commented on advanced_source/numpy_extensions_tutorial.py
> +# 매개 변수가 없는 예
```suggestion
# 매개 변수가 없는 예시
```
밑부분 번역은 예시라고 쓰여있어서 통일 하면 좋을 것 같습니다!

2020-12-03 14:49 UTC, creduo requested changes

2020-12-03 14:49 UTC, creduo commented on advanced_source/numpy_extensions_tutorial.py
> +# (컨벌루션과 상호 상관의 유일한 차이점은 컨벌루션에서는 필터를 뒤집어서 연산을 한다는 것입니다).
```suggestion
# (컨볼루션과 상호 상관의 유일한 차이점은 컨볼루션에서는 필터를 뒤집어서 연산을 한다는 것입니다).
```

2020-12-03 14:50 UTC, creduo commented on advanced_source/numpy_extensions_tutorial.py
> +numpy 와 scipy 를 이용한 확장 생성
```suggestion
numpy 와 scipy 를 이용한 확장(Extensions) 생성하기
```

2020-12-03 14:50 UTC, creduo approved these changes

2020-12-03 14:51 UTC, creduo commented on advanced_source/numpy_extensions_tutorial.py
>  =========================================
```suggestion
=====================================================
```

2020-12-03 15:24 UTC, 9bow commented
일부 추가 작업이 필요해보입니다. 우선 병합 후 별도로 작업하도록 하겠습니다.

2020-12-03 15:24 UTC, merged