Intermediate source/neural_style_tutorial.py (#159)
9bow/PyTorch-tutorials-kr pull request #162
Opened 2020-09-09 17:40 UTC by jjeamin

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #159

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

Intermediate source/neural_style_tutorial.py 번역

2020-09-10 20:11 UTC, ajin-jng commented
컨트리뷰톤 리뷰하겠습니다 :)

2020-09-10 20:30 UTC, ajin-jng approved these changes
번역하시느라 고생많으셨습니다 :)

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +imsize = 512 if torch.cuda.is_available() else 128  # 만약 GPU를 사용하지 않는다면 작은 크기
```suggestion
imsize = 512 if torch.cuda.is_available() else 128  # 만약 GPU가 없을 경우 작은 크기를 사용
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# -  ``torch``, ``torch.nn``, ``numpy`` (PyTorch로 신경망을 구현하기위한 필수 패키지)
```suggestion
# -  ``torch``, ``torch.nn``, ``numpy`` (PyTorch로 신경망을 구현하기 위한 필수 패키지)
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# -  ``torchvision.models`` (미리 학습 된 모델 불러오기 및 학습)
```suggestion
# -  ``torchvision.models`` (미리 학습된 모델 불러오기 및 학습)
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 계산되고 autograd 때문에 모든 기울기가 계산됩니다.
```suggestion
# 계산되고 autograd 을 통해 모든 기울기가 계산됩니다.
```
직역보다는 autograd 을 통해가 어떠신지요?

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +#    ``backward`` 메소드에서 수동으로 기울기를 다시 계산 / 구현 해야합니다.
```suggestion
#    ``backward`` 메소드에서 수동으로 기울기를 다시 계산 및 구현 해야합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 이렇게하면 입력이미지가 입력될 때마다 Content 손실이 원하는 레이어에서
```suggestion
# 이렇게 하면 입력 이미지가 입력될 때마다 Content 손실이 원하는 레이어에서
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +        # 기울기를 동적으로 계산하는데 사용되는 tree로부터 타겟 Content를 `분리(detach)` 합니다.
```suggestion
        # 기울기를 동적으로 계산하는데 사용되는 tree로부터 타깃 Content를 `분리(detach)` 합니다.
```
target 는 타깃으로 번역되는 듯 합니다

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +#    ``backward`` 메소드에서 수동으로 기울기를 다시 계산 / 구현 해야합니다.
```suggestion
#    ``backward`` 메소드에서 수동으로 기울기를 다시 계산 / 구현 해야 합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# gram 행렬은 주어진 행렬에 전치 행렬을 곱한 결과 입니다.
```suggestion
# gram 행렬은 주어진 행렬에 전치 행렬을 곱한 결과입니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 이 어플리케이션에서 주어진 행렬은 계층 :math:`L` 의 특징 맵 :math:`F_{XL}` 의 재구성 된 버전입니다.
```suggestion
# 이 어플리케이션에서 주어진 행렬은 계층 :math:`L` 의 특징 맵 :math:`F_{XL}` 의 재구성된 버전입니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# :math:`F_{XL}` 는 :math:`K`\ x\ :math:`N` 행렬인 :math:`\hat{F}_{XL}` 을 형성하도록 재구성 되며,
```suggestion
# :math:`F_{XL}` 는 :math:`K`\ x\ :math:`N` 행렬인 :math:`\hat{F}_{XL}` 을 형성하도록 재구성되며,
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# :math:`K` 는 계층 :math:`L` 의 특징 맵의 수이고 :math:`N`는 벡터화 된 특징 맵의 길이입니다.
```suggestion
# :math:`K` 는 계층 :math:`L` 의 특징 맵의 수이고 :math:`N`는 벡터화된 특징 맵의 길이입니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 예를 들어, :math:`\hat{F}_{XL}` 의 첫번째 줄은 벡터화 된 특징 맵 :math:`F_{XL}^1` 에 해당합니다.
```suggestion
# 예를 들어, :math:`\hat{F}_{XL}` 의 첫번째 줄은 벡터화된 특징 맵 :math:`F_{XL}^1` 에 해당합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 예를 들어, :math:`\hat{F}_{XL}` 의 첫번째 줄은 벡터화 된 특징 맵 :math:`F_{XL}^1` 에 해당합니다.
```suggestion
# 예를 들어, :math:`\hat{F}_{XL}` 의 첫 번째 줄은 벡터화 된 특징 맵 :math:`F_{XL}^1` 에 해당합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 마지막으로, gram 행렬은 행렬에서 각 값을 값의 총 개수로 나누어 정규화 해야합니다.
```suggestion
# 마지막으로, gram 행렬은 행렬에서 각 값을 값의 총 개수로 나누어 정규화 해야 합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 이제는 사전 훈련 된 신경망을 가져와야 합니다.
```suggestion
# 이제는 사전 훈련된 신경망을 가져와야 합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 일부 계층은 훈련하는 중 평가와 다른 동작을 하기 때문에, 네트워크를 ``.eval()`` 를 사용해 평가 모드로 설정해야합니다.
```suggestion
# 일부 계층은 훈련하는 중 평가와 다른 동작을 하므로, 네트워크를 ``.eval()`` 를 사용해 평가 모드로 설정해야합니다.
```
'하므로' 표현이 더 자연스러운 듯 합니다

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 이미지를 네트워크로 입력하기 전에 정규화 하는데 사용합니다.
```suggestion
# 이미지를 네트워크로 입력하기 전에 정규화하는데 사용합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +        # B는 배치 크기입니다. C는 채널의 수 입니다. H는 높이고 W는 너비입니다.
```suggestion
        # B는 배치 크기입니다. C는 채널의 수입니다. H는 높이고 W는 너비입니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 올바르게 삽입 된 새로운 ``Sequential`` 모듈을 만들어야 합니다.
```suggestion
# 올바르게 삽입된 새로운 ``Sequential`` 모듈을 만들어야 합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +    # 순차적으로 활성화되어야하는 모듈에 새로운 nn.Sequential을 만듭니다.
```suggestion
    # 순차적으로 활성화되어야 하는 모듈에 새로운 nn.Sequential을 만듭니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +    i = 0  # conv를 볼때마다 증가
```suggestion
    i = 0  # conv를 볼 때마다 증가
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 네트워크의 각 반복 동안, 업데이트 된 입력이 주어지고 새로운 손실을 계산합니다.
```suggestion
# 네트워크의 각 반복 동안, 업데이트된 입력이 주어지고 새로운 손실을 계산합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 마지막으로 뉴럴 변환(neural transfer)을 수행하는 함수를 정의해야합니다.
```suggestion
# 마지막으로 뉴럴 변환(neural transfer)을 수행하는 함수를 정의해야 합니다.
```

2020-09-10 20:30 UTC, ajin-jng commented on advanced_source/neural_style_tutorial.py
> +# 네트워크가 실행될 때마다 입력 값을 0에서 1사이로 수정하여 문제를 해결할 수 있습니다.
```suggestion
# 네트워크가 실행될 때마다 입력값을 0에서 1사이로 수정하여 문제를 해결할 수 있습니다.
```

2020-09-11 01:45 UTC, JaeLee18 commented
컨트리뷰톤 리뷰 진행하겠습니다 :)

2020-09-11 01:52 UTC, JaeLee18 requested changes
Suggested Korean Translations

2020-09-11 01:52 UTC, JaeLee18 commented on advanced_source/neural_style_tutorial.py
> +알고리즘은 입력 이미지, Content 이미지, Style 이미지 3개의 이미지를 가져와서 Content 이미지의 Content와 Style 이미지의 예술적 Style을 닮도록 입력을 변환합니다.
```suggestion
이 알고리즘은 입력 이미지, Content 이미지, Style 이미지 3개의 이미지를 가져와서 Content 이미지의 Content와 Style 이미지의 예술적 Style을 닮도록 입력을 변환합니다.
```

2020-09-11 01:52 UTC, JaeLee18 commented on advanced_source/neural_style_tutorial.py
> +# 그런 다음, 세 번째 이미지인 입력을 가져와서
```suggestion
# 그런 다음, 입력으로 사용되는 세 번째 이미지를 가져와서
```

2020-09-11 01:52 UTC, JaeLee18 commented on advanced_source/neural_style_tutorial.py
> +# 만약 백색 잡음(white noise)을 사용하려면 아래 주석을 제거하세요
```suggestion
# 만약 화이트 노이즈(white noise)을 사용하려면 아래 주석을 제거하세요
```

애매하네요.. 사진이라 잡음은 아닌거같은데 우선 화이트 노이즈로 해봤습니다.

2020-09-11 05:06 UTC, jjeamin commented on advanced_source/neural_style_tutorial.py
> +# 네트워크가 실행될 때마다 입력 값을 0에서 1사이로 수정하여 문제를 해결할 수 있습니다.
전체적으로 띄어쓰기나 그런부분이 많이 부족했군요 꼼꼼한 리뷰 감사합니다!

2020-09-11 05:08 UTC, jjeamin commented on advanced_source/neural_style_tutorial.py
> +# 만약 백색 잡음(white noise)을 사용하려면 아래 주석을 제거하세요
감사합니다 ㅎㅎ 헷갈리는단어 군요,.,.

2020-09-21 05:38 UTC, kwonmha reviewed
번역하시느라 수고하셨습니다.

2020-09-23 05:40 UTC, Justin-A reviewed
컨트리뷰톤 리뷰 진행하겠습니다. 번역하시느라 고생 많으셨습니다! 
번역이 잘 되어있어 일부 표현만 리뷰하였습니다. 수고하셨습니다!

2020-09-23 05:40 UTC, Justin-A commented on advanced_source/neural_style_tutorial.py
> +PyTorch를 사용하여 뉴럴 변환(Neural Transfer)
사용하여보다는 이용하여는 어떠신가요? :)

2020-09-23 05:40 UTC, Justin-A commented on advanced_source/neural_style_tutorial.py
> +# 패키지 가져오기 및 장치 선택
다른 튜토리얼을 번역하신분들은 보통 불러오기라고 표현하시더라구요. 가져오기에서 불러오기는 어떠세요?

2020-09-27 07:13 UTC, jjeamin commented on advanced_source/neural_style_tutorial.py
> +PyTorch를 사용하여 뉴럴 변환(Neural Transfer)
네 감사합니다 ㅎㅎ

2020-09-27 07:14 UTC, jjeamin commented on advanced_source/neural_style_tutorial.py
> +# 패키지 가져오기 및 장치 선택
네 감사합니다 ㅎㅎ

2020-09-27 07:14 UTC, jjeamin commented on advanced_source/neural_style_tutorial.py
>      # (c,d)=dimensions of a f. map (N=c*d)
네 감사합니다 ㅎㅎ

2020-09-27 07:14 UTC, jjeamin commented on advanced_source/neural_style_tutorial.py
>  #
네 감사합니다 ㅎㅎ

2021-11-07 12:51 UTC, hyoyoung approved these changes
looks good to me

2021-11-07 12:53 UTC, merged