beginner_source/dist_overview 번역
9bow/PyTorch-tutorials-kr pull request #169
Opened 2020-09-12 11:57 UTC by JaeLee18

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #167

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
torch.distributed 패키지 튜토리얼 번역

2020-09-12 12:31 UTC, kypark7 reviewed
컨트리뷰톤 리뷰 진행하겠습니다

2020-09-12 12:31 UTC, kypark7 commented on beginner_source/dist_overview.rst
> +PyTorch 1.6.0 버전의  ``torch.distributed`` 는 세개의 주요 부분으로 분류됩니다:
```suggestion
PyTorch 1.6.0 버전의  ``torch.distributed`` 는 세 개의 주요 부분으로 분류됩니다:
```

2020-09-12 12:31 UTC, kypark7 commented on beginner_source/dist_overview.rst
> +  One example would be distributed parameter averaging, where
영어로 된 이 문장은 삭제해야 할 것같습니다!

2020-09-12 12:31 UTC, kypark7 commented on beginner_source/dist_overview.rst
> +   만약 DDP를 처음사용한다면 이 문서부터 보는걸 추천합니다.
```suggestion
   만약 DDP를 처음 사용한다면 이 문서부터 보는걸 추천합니다.
```

2020-09-12 12:31 UTC, kypark7 commented on beginner_source/dist_overview.rst
> +    Note that, DDP can be
이 부분도 삭제 되어야 할 것 같습니다

2020-09-12 12:31 UTC, kypark7 commented on beginner_source/dist_overview.rst
> +   알아두어야할것은 DDP는 `단일-서버 모델 병렬 튜토리얼<../intermediate/model_parallel_tutorial.html>`__
```suggestion
   알아두어야 할 것은 DDP는 `단일-서버 모델 병렬 튜토리얼<../intermediate/model_parallel_tutorial.html>`__
```

2020-09-12 12:31 UTC, kypark7 commented on beginner_source/dist_overview.rst
> +DDP가 모든 프로세스들이 긴밀하게 동기화되어 작동하길 요구하고 또한 다른 프로세스에서 생성된
```suggestion
 DDP가 모든 프로세스들이 긴밀하게 동기화되어 작동하길 요구하고 또한 다른 프로세스에서 생성된
```
앞에 띄어쓰기가 생략되었습니다

2020-09-12 12:31 UTC, kypark7 commented on beginner_source/dist_overview.rst
> +일반적은 분산 학습 시나리오를 지원하는것을 목표로 하고있습니다.
```suggestion
일반적인 분산 학습 시나리오를 지원하는것을 목표로 하고있습니다.
```

2020-09-12 14:41 UTC, codingbowoo requested changes
컨트리뷰톤 리뷰 진행했습니다. 긴 문서 번역하느라 정말 고생 많으셨습니다!

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  DDP를 이용하며 모델은 매 프로세스 마다 복제되며, 복제된 모델들은 다른 입력 데이터 샘플들의 세트에 사용됩니다.
```suggestion
  DDP를 이용할 때, 모델은 매 프로세스 마다 복제되며, 복제된 모델들은 다른 입력 데이터 샘플 세트들에 사용됩니다.
```
```다른```이 수식하는 것이 ```샘플 세트```임이 좀 더 명확해야 할 것 같습니다.

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  DDP 는 변화도 통신을 책임져서 모델 복제품들끼리 동기화되도록 하며 또한 이것을 변화도 계산과 합쳐서 학습을 더 빨리하게 합니다.
```suggestion
  DDP는 변화도 통신(!)을 책임져서 모델 복제본들끼리 동기화되도록 하며 이것(!)을 변화도 계산과 합쳐서 학습을 더 빨리하게 합니다.
```
변화도 통신 이라는 말이 어색한데, 저도 당장은 어떻게 수정하면 좋을지 아이디어가 없어 이 문장은 조금 논의를 해보면 좋겠습니다!
또한 ```이것``` 에 해당하는 것을 (원문에서 비록 ```it```이지만) 좀 더 명확히 하면 좋을 것 같습니다. 우선 수정하면 좋을 것 같은 부분에 표시해두었습니다!

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  DDP와의 결합에 맞지 않는 일반적인 학습 구조를 지원하기 위해 개발되었습니다.
```suggestion
  (RPC) 는 분산 파이프라인 병렬화, 매개변수 서버 패러다임, 다른 학습 패러다임과 DDP의 결합 등 
  데이터 병렬 학습에 맞지 않는 일반적인 학습 구조를 지원하기 위해 개발되었습니다. 
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  또한 단체 통신 API (예,
```suggestion
  또한 단체 통신 API (예를 들어,
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  는 1.6.0 버전 기준으로 c10d를 기반으로 개발되어있으며 DDP 는 단체 통신을 그리고 RPC 는 P2P 통신을 사용합니다.
```suggestion
  는 1.6.0 버전 기준으로 c10d를 기반으로 개발되어 있으며, DDP 는 단체 통신을, RPC 는 P2P 통신을 사용합니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  많은 분산 훈련 시나리오들을 해결할 수 있습니다.
```suggestion
  DDP와 RPC의 위와 같은 특징들로 많은 분산 훈련 시나리오를 해결할 수 있기 때문에, 개발자들은 
  일반적으로 이러한 순수한(raw) 통신 API를 사용하지 않아도 됩니다.
  ```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  도움이 되는 경우중 한 경우는 분산 매개변수 평균내기(averaging)입니다.
```suggestion
  도움이 되는 경우 중 한 가지는 분산 매개변수 평균내기(averaging)입니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  이때 어플리케이션은 역전파 후에 DDP를 사용하여 변화도를 통신하는 대신
```suggestion
  이 때 어플리케이션은 역전파 후에 DDP를 사용하여 변화도를 통신하는 대신
```

개인적으로는 ```이 때```대신 ```분산 매개변수 평균내기에서는```을 사용하거나 앞 문장과 연결할 것 같습니다.

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  이것은 계산에서 통신을 분리하고 무엇과 통신할지 세부적인 제어를 가능하게 해주지만 DDP에 의해 제공되는 성능 최적화를 포기합니다.
```suggestion
  이것은 계산에서 통신을 분리하고, 무엇과 통신할 지에 대한 세부적인 제어를 가능하게 해주지만 DDP에 의해 제공되는 성능 최적화를 포기합니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +점진적으로 간단한것에서 복잡한것으로 또한 프로토타입에서 제품으로 발전해나가는 어플리케이션들의
```suggestion
점진적으로 간단한 것에서 복잡한 것으로 , 또 프로토타입에서 제품으로 발전해나가는 어플리케이션들의
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +1. 한개의 GPU에 데이터와 모델이 들어간다면 단일 장치 훈련이 사용되고 훈련 속도는 큰 걱정이 아닙니다.
```suggestion
1. 한 개의 GPU에 데이터와 모델이 들어간다면 단일 장치 훈련이 사용되고, 훈련 속도는 문제가 되지 않습니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +2. 만약 다중 GPU가 서버에 있다면 서버에서 다중 GPU `DataParallel <https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html>`__,
```suggestion
2. 만약 서버에 GPU가 여러 대 있다면, 단일 머신 다중 GPU에 해당하는 `DataParallel <https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html>`__,
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +2. 만약 다중 GPU가 서버에 있다면 서버에서 다중 GPU `DataParallel <https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html>`__,
뒷 문장에 단일 서버라고 하셨네요! 단일 서버 다중 지피유로 쓰셔도 좋을 것 같아요!

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +   만약 어플리케이션이 서버 경계를 가로질러로 조정될 필요성이 있다면 `launching script <https://github.com/pytorch/examples/blob/master/distributed/ddp/README.md>`__,
```suggestion
   만약 어플리케이션이 서버 경계를 가로질러 확장될 필요성이 있다면 `launching script <https://github.com/pytorch/examples/blob/master/distributed/ddp/README.md>`__,
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +패키지는 단일-서버 다중-GPU 병렬화를 가능하게 해주며 가장 낮은 코딩 난이도를 갖고있습니다.
```suggestion
패키지는 단일 서버 다중 GPU 병렬화를 가능하게 해주며 가장 낮은 코딩 난이도를 갖고 있습니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> + It only requires a one-line change to the application code.
해당 영어문장은 삭제 필요합니다!

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +한 가지 주의할 점은 비록 ``DataParallel`` 은 굉장히 사용하기 쉽지만, 이것은 최상의 성능을 제공하지는 않습니다.
```suggestion
한 가지 주의할 점은 비록 ``DataParallel`` 은 굉장히 사용하기 쉽지만, 이것은 최상의 성능을 제공하지는 않는다는 것입니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +그 이유로는 ``DataParallel`` 의 코드는 매 순방향 패스일때 모델을 복제하고 이것의 단일 프로세스 다중 쓰레드 병렬화는
```suggestion
그 이유로는 ``DataParallel`` 의 코드는 매 순전파 단계에서 모델을 복제하고 이것의 단일 프로세스 다중 쓰레드 병렬화는
```
제가 전에 #glossary 에 올렸을 때 기존에 forward pass를 순전파 단계라고 번역한 적이 있다고 하여 제안드립니다.

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +`DataParallel <https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html>`__ 과 비교했을때
```suggestion
`DataParallel <https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html>`__ 과 비교했을 때
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +는 한가지를 더 요구하는데 이것은 `init_process_group <https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group>`__ 을 호출하는것입니다.
```suggestion
는 한 가지를 더 요구하는데, 이것은 `init_process_group <https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group>`__ 을 호출하는 것입니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +또한 이 모델은 매 순방향 패스일때 복제가 되는게 아니라 DDP가 구축할때 나오기 때문에 학습 속도를 증가시키는데 도움이 됩니다.
```suggestion
DDP는 다중 프로세스 병렬화를 사용하기 때문에 모델 복제본들 사이에선 GIL 문제가 발생하지 않습니다.
또한 이 모델은 매 순전파 단계마다 복제가 되는게 아니라 DDP가 구축할때 나오기 때문에 학습 속도를 증가시키는데 도움이 됩니다.
```

앞서 리뷰한 내용들과 일관성을 주기 위해 코멘트 남깁니다.

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +때때로 DPP를 사용할때 OOM과 같은 에러를 보는것은 필연적이지만 DPP 자체로는 이러한 에러를 복구할수 없으며
```suggestion
때때로 DDP를 사용할때 OOM과 같은 에러를 보는것은 필연적이지만 DDP 자체로는 이러한 에러를 복구할 수 없으며
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> + This is because DDP requires all processes
문장 삭제 필요

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +launched in different processes must match.
문장 삭제 필요

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +만약 그룹에 있는 프로세스들중 하나라도 OOM 에러를 갖는다면 동기화가 되지않는 (일치되지 못하는 ``AllReduce`` 작업들)
```suggestion
만약 그룹에 있는 프로세스들 중 하나라도 OOM 에러를 갖는다면 동기화가 되지않는 (일치하지 않는 ``AllReduce`` 작업들)
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  주어진 함수를 실행하는것을 지원합니다.
```suggestion
  주어진 함수를 실행하는 것을 지원합니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  관리하는것을 도와줍니다. 참조 계산 프로토콜은
```suggestion
  관리하는 것을 도와줍니다. 참조 계산 프로토콜은
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +  에 나와있습니다.
```suggestion
  에 나와 있습니다.
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +   하여 RPC 와 PRef 를 보여줍니다. 그리고 기본적인 분산된 모델 병렬화를 RNN 예시에 적용하여 어떻게 분산된 autograd 와 분산된 옵티마이저
```suggestion
   사용하여 RPC 와 PRef 를 보여줍니다. 그리고 기본적인 분산된 모델 병렬화를 RNN 예시에 적용하여 어떻게 분산된 autograd 와 분산된 옵티마이저
```

2020-09-12 14:41 UTC, codingbowoo commented on beginner_source/dist_overview.rst
> +   튜토리얼은 단일-서버 파이프라인 병렬 예시(`단일-서버 모델 병렬화 튜토리얼 <../intermediate/model_parallel_tutorial.html>`__)
```suggestion
   튜토리얼은 단일 서버 파이프라인 병렬 예시(`단일 서버 모델 병렬화 튜토리얼 <../intermediate/model_parallel_tutorial.html>`__)
```

2020-09-21 03:12 UTC, kwonmha reviewed
긴 문서 번역하시느라 수고 많으셨습니다.

2020-09-21 03:12 UTC, kwonmha commented on beginner_source/dist_overview.rst
> +    튜토리얼은 `HogWild! training <https://people.eecs.berkeley.edu/~brecht/papers/hogwildTR.pdf>`__ 을 빌려왔으며
직역식으로 하면 'HogWild 문서'의 철학을 빌려왔으며 가 정도가 될 것 같습니다.
의역을 좀 더 하면 더 좋을 것 같다는 생각이 드는데, spirit과 borrow 둘 다 의역하기가 쉽지 않네요.
'차용' 이란 단어 어떠신가요?

2020-09-21 03:12 UTC, kwonmha commented on beginner_source/dist_overview.rst
> +  앞서 소개된 튜토리얼 1과 2에서 보여준 비슷한 강화학습과 매개변수 서버를 사용합니다.
```suggestion
  앞서 소개된 튜토리얼 1과 2에서 보여준 것들과 비슷한 강화학습과 매개변수 예제를 사용합니다.
```
서버라는 내용이 없어 보여서 예제로 바꿨습니다.

2020-09-23 05:34 UTC, Justin-A reviewed
컨트리뷰톤 리뷰 진행하겠습니다. 번역하시느라 고생 많으셨습니다! 
다른 분들이 리뷰를 잘 작성해주셔서 표현 하나만 리뷰하였습니다!

2020-09-23 05:34 UTC, Justin-A commented on beginner_source/dist_overview.rst
> +5. 만약 에러(예, OOM)나 교육중에 자원들이 추가되거나 빠질것 같다면
교육이라기보단 모델이 학습된다는 표현을 자주 사용하니까, 학습 과정 속에서 자원들이 추가되거나 빠질 것 같다면 식으로 수정하는것도 좋아보입니다!

2021-11-07 12:59 UTC, hyoyoung commented
feedback이 없어서 pr을 close합니다.
필요할때 열어주시거나 새로 생성하여주세요.

2021-11-07 12:59 UTC, closed without merging