pytorch-cheat-sheet
9bow/PyTorch-tutorials-kr pull request #170
Opened 2020-09-12 12:28 UTC by Gangsss

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [ ] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #168

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
pytorch cheat sheet 번역했습니다.
함수명이나 번역하기 어려운 것들이 있어 많은 리뷰 부탁드립니다!

2020-09-12 15:04 UTC, codingbowoo requested changes
주석을 번역하는 것이 은근 까다로운데 전체적으로 편하게 봤습니다. 코멘트는 많은데, 다 어미를 통일하면 좋겠다는 한가지 이유로 체크(?) 해둔 것입니다. 고생하셨습니다!

2020-09-12 15:04 UTC, codingbowoo commented on beginner_source/ptcheat.rst
> +                                      # Softmax2d 또는 LogSoftmax가 있다.
```suggestion
                                      # Softmax2d 또는 LogSoftmax가 있음
```

2020-09-12 15:04 UTC, codingbowoo commented on beginner_source/ptcheat.rst
> +                                            # LBFGS, RMSProp 또는 Rprop가 있다.
```suggestion
                                            # LBFGS, RMSProp 또는 Rprop가 있음
```

2020-09-12 15:04 UTC, codingbowoo commented on beginner_source/ptcheat.rst
> +													              # ExponentialLR 또는 ReduceLROnPLateau가 있다.
```suggestion
													              # ExponentialLR 또는 ReduceLROnPLateau가 있음
```

리뷰하다보니 ```000가 있음```은 조금 어색한 듯도 하여, 번역자분께서 편한 쪽으로 하시는 것이 좋을 것 같습니다. 
```X의 예: ``` 따위를 시작할 때 달아두고 후에는 나열만 하는 것도 방법일 것 같습니다.

2020-09-12 15:04 UTC, codingbowoo commented on beginner_source/ptcheat.rst
> +DataLoader(dataset, batch_size=1, ...)      # 개별 데이터 지점들의 구조에 관계없이 데이터 배치를 불러온다
```suggestion
DataLoader(dataset, batch_size=1, ...)      # 개별 데이터 지점들의 구조에 관계없이 데이터 배치를 불러옴
```

2020-09-12 15:04 UTC, codingbowoo commented on beginner_source/ptcheat.rst
> +                                            # WeightedRandom 또는 Distributed가 있다
```suggestion
                                            # WeightedRandom 또는 Distributed가 존재
```

2020-09-19 09:24 UTC, jjeamin commented
리뷰 진행하겠습니다.

2020-09-21 02:34 UTC, kwonmha reviewed
수고 많으셨습니다!

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +from torch import Tensor                  # 계산 그래프 안에서 텐서 노드
```suggestion
from torch import Tensor                  # 계산 그래프 안의 텐서 노드
```
'안에 있는', '내의' 같은 표현이 어떨까 합니다.

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +import torch.nn.functional as F           # 계층, 활성화 함수 그 외의 것
```suggestion
import torch.nn.functional as F           # 계층, 활성화 함수와 그 외의 것
```
이어주는 말이 있으면 좋을 것 같습니다.

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +from torch.jit import script, trace       # 하이브리드 프론트엔드 데코레이터 tracing jit
```suggestion
from torch.jit import script, trace       # 하이브리드 프론트엔드 데코레이터, tracing jit
```
명사만 계속 나열되어 있어서 단어가 어떻게 구성되어 있는지 잘 모르겠습니다.
제가 해석한대로 쉼표를 붙여 봤습니다.

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +x.transpose(a,b)                      # a차원과 b차원 간의 변경
```suggestion
x.transpose(a,b)                      # a차원과 b차원 간의 교환
```
좀 더 구체적인 뜻의 단어를 써 봤습니다.

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +x.permute(*dims)                      # 차원들간의 재배열
```suggestion
x.permute(*dims)                      # 차원들 간의 재배열
```

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +torch.cuda.is_available                                 # cuda를 체크합니다.
```suggestion
torch.cuda.is_available                                 # cuda를 체크
```
여기도 명사형 종결어미를 써야할 것 같습니다.

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +																							# 완전연결(fully connected) 레이어
[번역 가이드](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md)에 레이어를 계층으로 번역해놓고 있어서 계층으로 통일하는 것도 좋아 보입니다.

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +                                      # ,CosineEmbeddingLoss가 있다.
```suggestion
                                      # ,CosineEmbeddingLoss가 있음
```
여기도 명사형으로 끝나는 것이 좋아 보입니다.

2020-09-21 02:34 UTC, kwonmha commented on beginner_source/ptcheat.rst
> +scheduler.step()                        # epoch의 시작할 때 학습률 업데이트
```suggestion
scheduler.step()                        # epoch가 시작할 때 학습률 업데이트
```

2020-09-23 05:21 UTC, Justin-A reviewed
컨트리뷰톤 리뷰 진행하겠습니다. 번역하시느라 고생 많으셨습니다!

2020-09-23 05:21 UTC, Justin-A commented on beginner_source/ptcheat.rst
> +torch.jit.trace()         # 모듈이나 함수 그리고 예제 데이터 인풋을 취하고
인풋이라는 표현보다는 입력값이라는 표현은 어떠세요? 입력값으로 이용되는 예제 데이터 등과 같은 표현도 좋아보입니다.

2020-09-23 05:21 UTC, Justin-A commented on beginner_source/ptcheat.rst
> +													# 모델이 진행되는 동안 데이터가 마주하는 계산 단계를 추적
모델이 진행된다기 보다는, '모델이 학습되는 과정 속에서 계산되는 내용을 추적' 이 좋은 표현이라고 생각되는데 어떠신가요?

2020-09-23 05:21 UTC, Justin-A commented on beginner_source/ptcheat.rst
> +scheduler.step()                        # epoch의 시작할 때 학습률 업데이트
새로운 epoch 단계에서 학습률 업데이트는 어떠세요?

2020-11-08 05:47 UTC, 9bow commented
안녕하세요, @Gangsss 님.
이 PR 관련하여 라이선스 동의가 없어 확인 요청을 드리고자 덧글 남깁니다. ^^;
![image](https://user-images.githubusercontent.com/9343724/98458197-5dc4eb80-21d1-11eb-98ce-80ef1f6499a7.png)

본문의 라이선스 동의 관련하여 확인 및 체크 부탁드립니다!

2020-11-08 07:52 UTC, Gangsss commented
> 안녕하세요, @Gangsss 님.
> 이 PR 관련하여 라이선스 동의가 없어 확인 요청을 드리고자 덧글 남깁니다. ^^;
> ![image](https://user-images.githubusercontent.com/9343724/98458197-5dc4eb80-21d1-11eb-98ce-80ef1f6499a7.png)
> 
> 본문의 라이선스 동의 관련하여 확인 및 체크 부탁드립니다!

수정했습니다!

2020-11-18 13:59 UTC, lewha0 reviewed
안녕하세요, 살펴 보고 리뷰 코멘트를 조금 남겨 보았습니다. 한 번 참고 부탁드립니다.

2020-11-18 13:59 UTC, lewha0 commented on beginner_source/ptcheat.rst
> +import torch.optim as optim               # 옵티마이저 (경사 하강법, ADAM, etc.)
24번 행에서는 괄호 앞을 붙이셨는데, 하나로 통일하면 좋을 듯 합니다.

2020-11-18 13:59 UTC, lewha0 commented on beginner_source/ptcheat.rst
> +torch.cuda.is_available                                 # cuda를 체크
cuda 사용 가능 여부 확인, 정도로 좀 더 풀어 써주시면 어떨까요?

2020-11-18 13:59 UTC, lewha0 commented on beginner_source/ptcheat.rst
> +nn.Dropout(p=0.5, inplace=False)              # 아무 차원 입력에 대한 드랍아웃(dropout) 레이어
'아무' 대신에 '임의' 는 어떨까요?

2020-11-18 13:59 UTC, lewha0 commented on beginner_source/ptcheat.rst
> +nn.Dropout2d(p=0.5, inplace=False)            # 2차원 채널별 드롭아웃
바로 앞에서는 '드랍아웃'이라고 하셨는데, 여기서는 '드롭아웃'으로 되어 있습니다. 하나로 통일하면 좋을 듯 합니다.

2020-11-18 13:59 UTC, lewha0 commented on beginner_source/ptcheat.rst
> +                                      # ,CosineEmbeddingLoss가 있음
마지막 쉼표의 위치가 조금 어색해 보입니다.

2020-11-18 13:59 UTC, lewha0 commented on beginner_source/ptcheat.rst
> +opt.step()                                  # 가중치(weights) 업데이트
영문 병기를 weights 대신에 weight로 하면 어떨까요?

2021-07-05 13:28 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +import torch.optim as optim               # 옵티마이저 (경사 하강법, ADAM, etc.)
```suggestion
import torch.optim as optim               # 옵티마이저(경사 하강법, ADAM, etc.)
```

2021-07-05 13:30 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +opt.step()                                  # 가중치(weights) 업데이트
```suggestion
opt.step()                                  # 가중치(weight) 업데이트
```

리뷰 감사합니다.

2021-07-05 13:31 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +                                      # ,CosineEmbeddingLoss가 있음
위의 내용과 맞추다보니 어색하게 되었네요 코멘트 감사합니다!

2021-07-05 13:32 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +                                      # KLDivLoss, MarginRankingLoss, HingeEmbeddingLoss
```suggestion
                                      # KLDivLoss, MarginRankingLoss, HingeEmbeddingLoss, CosineEmbeddingLoss가 있음
```

2021-07-05 13:32 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +                                      # ,CosineEmbeddingLoss가 있음
```suggestion
                                      # 
```

2021-07-05 13:32 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +                                      # ,CosineEmbeddingLoss가 있음
```suggestion
                                     
```

2021-07-05 13:34 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +nn.Dropout(p=0.5, inplace=False)              # 아무 차원 입력에 대한 드랍아웃(dropout) 레이어
리뷰 감사합니다!
```suggestion
nn.Dropout(p=0.5, inplace=False)              # 임의의 차원 입력에 대한 드랍아웃(dropout) 레이어 
```

2021-07-05 13:35 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +																							# 완전연결(fully connected) 레이어
리뷰 감사합니다!
```suggestion
nn.Linear(m,n)                                # m개의 뉴런에서 n개의 뉴런으로 연결되는
																							# 완전연결(fully connected) 계층 
```

2021-07-05 13:35 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +nn.Dropout2d(p=0.5, inplace=False)            # 2차원 채널별 드롭아웃
리뷰 감사합니다
```suggestion
nn.Dropout2d(p=0.5, inplace=False)            # 2차원 채널별 드랍아웃
```

2021-07-05 13:37 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +torch.cuda.is_available                                 # cuda를 체크
리뷰 감사합니다!
```suggestion
torch.cuda.is_available                                 # cuda 사용 가능여부 확인
```

2021-07-05 13:40 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +torch.jit.trace()         # 모듈이나 함수 그리고 예제 데이터 인풋을 취하고
리뷰 감사합니다!
```suggestion
torch.jit.trace()         # 모듈이나 함수 그리고  입력값으로 이용되는 예제 데이터을 불러오고
```

2021-07-05 14:09 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +													# 모델이 진행되는 동안 데이터가 마주하는 계산 단계를 추적
리뷰 감사합니다! torch.jit.trace()같은 경우 학습하는 과정이 아닌 함수에 모델 인스턴스와 인풋값을 전달해주는 과정이어서 학습되는 과정이라고 얘기하는 건 어려울 것 같습니다. 대신 어색한 표현을 조금 더 풀어썼습니다.

```suggestion
													# 데이터가 모델을 통해 가면서 계산되는 단계를 추적합니다.
```

2021-07-05 14:18 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +scheduler.step()                        # epoch의 시작할 때 학습률 업데이트
코멘트 감사합니다 위의 내용 반영하겠습니다.

2021-07-05 14:24 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +scheduler.step()                        # epoch가 시작할 때 학습률 업데이트
```suggestion
scheduler.step()                        # 새로운 epoch 시작 할 때 학습률 업데이트
```

2021-07-05 14:28 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +from torch import Tensor                  # 계산 그래프 안에서 텐서 노드
```suggestion
from torch import Tensor                  # 계산 그래프 안의 텐서 노드
```

2021-07-05 14:33 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +                                            # WeightedRandom 또는 Distributed가 있다
```suggestion
                                            # WeightedRandom 또는 Distributed가 존재
```

2021-07-05 14:35 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +from torch import Tensor                  # 계산 그래프 안에서 텐서 노드
```suggestion
from torch import Tensor                  # 계산 그래프 안에 있는 텐서 노드
```

2021-07-05 14:38 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +from torch import Tensor                  # 계산 그래프 안의 텐서 노드
```suggestion
from torch import Tensor                  # 계산 그래프 안에 있는 텐서 노드
```
@codingbowoo  리뷰 감사합니다

2021-07-05 14:41 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +from torch import Tensor                  # 계산 그래프 안에서 텐서 노드
@kwonmha 감사합니다 반영했습니다!

2021-07-05 14:44 UTC, Gangsss reviewed
everything is fine

2021-07-05 14:54 UTC, Gangsss commented
@9bow 여러 코멘트들을 받아서 번역 마무리 했습니다. PR부탁드려요!

2021-07-05 15:01 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +# Imports(선언)
```suggestion
- Imports(선언)
=========
```

2021-07-05 15:02 UTC, Gangsss commented on beginner_source/ptcheat.rst
```suggestion
******************************
```

2021-07-05 15:03 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +# Imports(선언)
```suggestion
Imports(선언)
=========
```

2021-07-05 15:03 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +---
```suggestion

```

2021-07-05 15:03 UTC, Gangsss commented on beginner_source/ptcheat.rst
> +## General
```suggestion
General
```

2021-07-08 13:34 UTC, 9bow commented
안녕하세요, @Gangsss 님.
수정 감사합니다. 대략 아래와 같은 내용들로 제가 이 PR은 보류를 하고 있었는데요, 확인 부탁드립니다.

1. 해당 파일은 v1.8, v1.9를 거치며 바뀐 내용들이 있습니다. [최신 파일의 blame](https://github.com/9bow/PyTorch-tutorials-kr/blame/master/beginner_source/ptcheat.rst)을 참고하셔서 최근 변경 내역들을 확인하시고 추가해주시기를 부탁드립니다.
2. 전반적으로 결과물의 형태만 보았을 때 원문에서 의도하는 내용들이 잘 표현되지 못한 것 같습니다.
3. 테스트 빌드를 해보시면 아시겠지만, 모든 코드 블럭들이 잘못 번역되어 있습니다. 코드의 들여쓰기 및 주석 부분 등을 참고해주시기를 부탁드립니다.
4. 위 코드 블럭 외에도 원문과 대치되는 문법들이 있습니다. 예를 들어,
  ```
    Also see
    --------
  ```
  위 문단은
  ```
    ## 여기도 참고하세요
  ```
 와 같이 번역되었는데, 빌드를 해보시면 아시겠지만 전체적으로 번역이 잘못 진행되고 있습니다.
5. 튜토리얼 문서 내에 참고용으로 달린 링크들 중 번역이 된 문서들이 있다면 사용자를 고려하여 번역된 결과물로 변경해주시는 것이 맞습니다.

전체적으로 기계적인 번역인 것 같아 미뤄두고 있었는데, 괜찮으시다면 이 PR을 닫아주시고, 위 내용들을 고려하시어 새롭게 PR 진행 부탁드립니다.
감사합니다.

2021-07-09 06:14 UTC, Gangsss commented
@9bow 확인했습니다 PR을 닫고 난 이후 새롭게 PR진행하도록 하겠습니다. 감사합니다.

2021-07-09 06:14 UTC, closed without merging