advanced_source/dynamic_quantization_tutorial.py
9bow/PyTorch-tutorials-kr pull request #173
Opened 2020-09-16 07:53 UTC by kwonmha

## 라이선스 동의
- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
- **이슈 번호**: #172 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
advanced_source/dynamic_quantization_tutorial.py : 번역
intermediate_source/dynamic_quantization_bert_tutorial.rst : 오타, 오류 수정. 파이썬 코드 가독성 향상(줄바뀜 개선)

2020-09-20 08:58 UTC, JaeLee18 commented
컨트리뷰톤 리뷰 진행하겠습니다.

2020-09-20 09:17 UTC, JaeLee18 requested changes
몇번이나 읽어보았지만 너무 매끄럽게 잘해놓으셨네요.. 수고하셨습니다!

2020-09-20 09:17 UTC, JaeLee18 commented on advanced_source/dynamic_quantization_tutorial.py
> +# 튜토리얼입니다. 그래서 우리는 간단히 사전학습된 가중치들을 모델에 불러올
```suggestion
# 튜토리얼입니다. 그래서 우리는 단순히 사전학습된 가중치들을 모델에 불러올
```

2020-09-21 01:55 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +# 튜토리얼입니다. 그래서 우리는 간단히 사전학습된 가중치들을 모델에 불러올
```suggestion
# 튜토리얼입니다. 그래서 단순히, 사전학습된 가중치들을 모델에 불러올
```
'우리는' 은 번역체 느낌이라 이때까지 뺐였는데 여기만 있네요.
그리고 '단순하게 사전학습됐다' 란 느낌이 되지 않도록 쉼표를 추가했습니다.
감사합니다.

2020-09-23 05:08 UTC, Justin-A reviewed
컨트리뷰톤 리뷰 진행하겠습니다.

2020-09-23 05:08 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +양자화는 모델의 크기를 줄이고 추론 속도를 높이면서도 정확도는 별로 낮아지지 않도록,
정확도라는 표현보다, 모델 성능이 낮아지지 않도록으로 표현하는게 좋지 않을까요?

2020-09-23 05:08 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +를 적용할 것입니다.
적용할 것입니다 -> 적용해봅시다의 표현이 좋지않을까 싶습니다!

2020-09-23 05:08 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +        """텍스트 파일을 토큰화 합니다."""
토큰화라는 표현이 조금 모호하지 않나요? 토큰 단위로 나누어 줍니다. 등의 표현은 어떠신가요? :)

2020-09-23 05:08 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +        # 파일 내용을 토큰화 합니다.
토큰화라는 표현이 조금 모호하지 않나요? 토큰 단위로 나누어 줍니다. 등의 표현은 어떠신가요? :)

2020-09-23 05:08 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +# 보겠습니다. 이때까지와 마찬가지로 `이 예제 <https://github.com/pytorch/examples/blob/master/word_language_model/generate.py>`_ 를
이때까지와보다는 지금까지 진행한 내용과 동일한 방식으로 등 표현을 재구성하는건 어떨까요?

2020-09-23 05:08 UTC, Justin-A commented on advanced_source/dynamic_quantization_tutorial.py
> +  """은닉 상태를 기록으로부터 떼어내기 위해 새로운 tensor로 감쌉니다."""
뗴어낸다기보단, 제거한다는 표현이 좋지 않을까요? 새로운 Tensor로 감싸는 표현보다는 재구성한다는 표현도 좋아보입니다 :)

2020-09-23 06:52 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +양자화는 모델의 크기를 줄이고 추론 속도를 높이면서도 정확도는 별로 낮아지지 않도록,
저는 정확도가 더 구체적인 표현이라 좋을 것 같습니다. 원문에서도 accuracy라고 했는데 굳이 바꿀 필요가 없어 보여요.

2020-09-23 06:52 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +이 튜토리얼에서, PyTorch의 `단어 단위 언어 모델 <https://github.com/pytorch/examples/tree/master/word_language_model>`_
```suggestion
이 튜토리얼에서는, PyTorch의 `단어 단위 언어 모델 <https://github.com/pytorch/examples/tree/master/word_language_model>`_
```

2020-09-23 06:52 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +를 적용할 것입니다.
네. 적용해 보겠습니다 로 수정했습니다

2020-09-23 06:52 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +        """텍스트 파일을 토큰화 합니다."""
토큰 단위로 나눈다 가 좀 더 구체적인 표현인 것은 맞습니다. 그렇지만 토큰화 라는 단어를 많이 쓰고 있어서 크게 무리가 없다고 생각했습니다.

2020-09-23 06:52 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +# 보겠습니다. 이때까지와 마찬가지로 `이 예제 <https://github.com/pytorch/examples/blob/master/word_language_model/generate.py>`_ 를
```suggestion
# 보겠습니다. 지금까지 튜토리얼을 진행했던 방식처럼 `이 예제 <https://github.com/pytorch/examples/blob/master/word_language_model/generate.py>`_ 를
```
제안해주신 내용을 참고하여 위와 같이 바꿔봤습니다.

2020-09-23 06:54 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +를 적용할 것입니다.
```suggestion
`동적 양자화 <https://pytorch.org/docs/stable/quantization.html#torch.quantization.quantize_dynamic>`_
를 적용해 보겠습니다.
```

2020-09-23 07:53 UTC, kwonmha commented on advanced_source/dynamic_quantization_tutorial.py
> +  """은닉 상태를 기록으로부터 떼어내기 위해 새로운 tensor로 감쌉니다."""
```suggestion
  """은닉 상태를 변화도 기록에서 제거된 새로운 tensor로 만듭니다."""
```
텐서의 구성이 바뀐다기보단 속성이 바뀌는 느낌이 들어서 함수 이름도 repackage이지만 단순하게 만든다... 라고 했습니다.

2020-09-27 11:49 UTC, kypark7 commented
이 번역은 #136 https://github.com/9bow/PyTorch-tutorials-kr/pull/156 에 제가 이미 했습니다ㅜㅜㅜㅜ 못보신 것 같네요ㅠㅠㅠㅠ

2020-09-27 13:38 UTC, 9bow commented
@kypark7 두 분의 번역을 모두 잘 합쳐서 모아보겠습니다. 👍 
(@creduo 님 도와주세요~ =3=33)

2020-09-28 01:41 UTC, kwonmha commented
헐... 그렇네요 ㅜㅜ 왜 못봤지.. ㅜ

2020-12-03 14:45 UTC, creduo approved these changes

2020-12-03 14:45 UTC, merged