recipes/dynamic_quantization.py 번역
9bow/PyTorch-tutorials-kr pull request #178
Opened 2020-10-18 14:43 UTC by lewha0

## 라이선스 동의
- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
- **이슈 번호**: #132

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [x] 번역되지 않은 튜토리얼을 번역하는 기여

## PR 설명
- recipes/dynamic_quantization.py 를 번역합니다

2021-08-23 13:51 UTC, hyoyoung requested changes

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +우리는 신경망을 설계할 때 여러 트레이드오프를 마주하게 됩니다. 모델을
트레이드오프는 절충으로 바꾸거나
트레이드오프(trade-off)로 원문 병기가 좋을듯 합니다

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +개발하고 학습할 때 순환 신경망의 레이어나 패러미터의 개수를 바꿔볼 수
패러미터는 용어집에는 매개변수로 되어있습니다

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +형태로 만들어야 한다는 부담이 적은 편입니다. 사실 이러한 작업은 LSTM
사실 이라는 단어는 없어도 좋을 듯 합니다

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +모델을 배포용으로 변환할 때 거의 필수적으로 필요한 단계입니다.
거의 필수적 보다는 표준적 혹은 일반적으로 필요한 단계입니다 라고 바꾸는건 어떨까요

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +1. 여러분은 아주 작은 LSTM 네트워크를 가지고 시작할 것입니다
주어는 빼는게 더 자연스러울 것 같습니다.

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +# 에서 영감을 받은 부분입니다
조사만 있을 경우 윗줄에 붙이는게 좋을 듯 합니다

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +  """기초적인 LSTM모델로, 단순히 nn.LSTM 를 래핑한 것입니다.
래핑은 감싸다로 표현하는게 좋을 듯 합니다

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +# 모양(shape)과 관련된 변수
매개변수 다듬기로 바꾸는건 어떨까요

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +# 4. 응답  시간 살펴보기
응답과 시간 사이에 공백이 2개 들어가 있습니다

2021-08-23 13:51 UTC, hyoyoung commented on recipes_source/recipes/dynamic_quantization.py
> +# 크게 다르지 않다는 점을 살펴보는 것은 의미가 있다고 봅니다.
in the same ballpark을 다르지 않다고 번역하셨는데 원본 처럼 "로 감싸서 강조하는 것도 좋을 듯 합니다

2021-09-04 23:43 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +우리는 신경망을 설계할 때 여러 트레이드오프를 마주하게 됩니다. 모델을
트레이드오프라는 표현을 계속 사용했기 때문에 영문 병기하였습니다.

2021-09-04 23:43 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +개발하고 학습할 때 순환 신경망의 레이어나 패러미터의 개수를 바꿔볼 수
수정하였습니다.

2021-09-04 23:44 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +형태로 만들어야 한다는 부담이 적은 편입니다. 사실 이러한 작업은 LSTM
삭제했습니다.

2021-09-04 23:45 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +모델을 배포용으로 변환할 때 거의 필수적으로 필요한 단계입니다.
'변환할 때면 표준적으로 거치는 단계입니다'로 수정했습니다.

2021-09-05 06:02 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +1. 여러분은 아주 작은 LSTM 네트워크를 가지고 시작할 것입니다
주어도 빼고, 이 부분을 전체적으로 다듬어 보았습니다.

2021-09-05 06:02 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +# 에서 영감을 받은 부분입니다
'에서'를 윗줄로 옮기는 게 좋아 보인다는 말씀이시죠? 그렇게 수정했습니다.

2021-09-05 06:03 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +  """기초적인 LSTM모델로, 단순히 nn.LSTM 를 래핑한 것입니다.
수정하였습니다.

2021-09-05 06:04 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +# 모양(shape)과 관련된 변수
말씀해주신 내용으로 수정하고, 원래 작성해 둔 내용은 괄호 안에 추가해 보았습니다.

2021-09-05 06:04 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +# 4. 응답  시간 살펴보기
수정하였습니다.

2021-09-05 06:06 UTC, lewha0 commented on recipes_source/recipes/dynamic_quantization.py
> +# 크게 다르지 않다는 점을 살펴보는 것은 의미가 있다고 봅니다.
수정하였습니다. 다만 우리말에서 큰따옴표에는 그러한 용법이 없기 때문에 작은따옴표로 수정하였습니다.

2021-09-05 06:07 UTC, lewha0 commented
리뷰해주신 내용 반영하였습니다. (여기서 이렇게 뵙네요.. ㅎㅎ)

2021-09-05 06:14 UTC, hyoyoung commented
> 리뷰해주신 내용 반영하였습니다. (여기서 이렇게 뵙네요.. ㅎㅎ)

저도 방금 썸네일 눌러보고 알았습니다. 뵙게되서 반갑네요 ㅎㅎ

2021-09-05 06:17 UTC, hyoyoung approved these changes
수정하시느라 고생 많으셨습니다.
현재 pytorch 튜토리얼 버전이 올라가서, conflict가 나고 있습니다
해당 부분은 크게 바뀐게 아니니 제가 임의로 merge하겠습니다

looks good to me

2021-09-05 06:22 UTC, hyoyoung commented
>>>>>>> committed document
# 이 문서는 빠르고 고수준의 내용입니다. 좀 더 자세하게 보시려면,
# `(beta) Dynamic Quantization on an LSTM Word Language Model Tutorial <https://tutorials.pytorch.kr/advanced/dynamic\_quantization\_tutorial.html>`_
# 방문하여 보시기 바랍니다

>>>>>>> master
# This was a fast and high level treatment of this material; for more
# detail please continue learning with `(beta) Dynamic Quantization on an LSTM Word Language Model Tutorial <https://tutorials.pytorch.kr/advanced/dynamic\_quantization\_tutorial.html>`_.

conflict 병합하고 추가된 내용에 따라 간략히 3줄 추가하였습니다

2021-09-05 09:49 UTC, 9bow commented
👍

2021-09-05 09:49 UTC, merged