advanced_source/torch-script-parallelism.rst
9bow/PyTorch-tutorials-kr pull request #194
Opened 2020-11-27 18:15 UTC by greeeener

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #189

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

2021-04-08 07:41 UTC, Hoseung requested changes
서너 개의 문장은 의미를 이해하기가 어려웠습니다. 
나머지는 의미상 문제가 없지만 조금 더 한글스러운 문장으로 바꾸어 보았습니다.

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +        # 주어진 Future를 호출하면, 계산을 오버랩(overlap)해서 병렬로 실행할 수 있습니다.
```suggestion
        # 계산을 병렬로 수행하기 위해서 "fork()" 와 "wait()" 사이에서 Future를 호출하는 점에 유의하세요.
```
역시 직역에 실패하여 의역해보았습니다.

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +``fork()`` 는 호출 가능한 ``fn`` 과 해당 호출 가능한  ``args`` 및  ``kwargs`` 에 대한 인자를 취하고  ``fn`` 실행을 위한 비동기(asynchronous) 작업을 생성합니다.
아래가 조금 더 정확한 번역인 것 같은데, 'callable'을 우리말로 뭐라고 해야할지 모르겠네요. 

fork()`` 는 callable ``fn`` 과 그에 대한 인자 ``args`` 및  ``kwargs``를 취하고  ``fn`` 실행을 위한 비동기(asynchronous) 작업을 생성합니다.

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +보다 현실적인 예시에 병렬화를 적용하고 어떤 종류의 성능을 얻을 수 있는지 살펴봅시다.
```suggestion
보다 현실적인 예시에 병렬화를 적용하고 어떤 성능을 얻을 수 있는지 살펴봅시다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +    # RNN 용어에서 우리가 관심 갖는 차원:
```suggestion
    # RNN 용어에서는 우리가 관심 갖는 차원들을 아래와 같이 부릅니다:
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +    # 이는 단순히 동일한 시퀀스에 적용된 두 개의 LSTMs이지만 하나는 반대로 적용됩니다.
```suggestion
    # 이는 단순히 동일한 시퀀스에 적용된 두 개의 LSTM이지만 하나는 반대로 적용됩니다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +            # 계층 적용, 그리고 시간 차원에서 출력 flip
```suggestion
            # Backward 계층. 시간 차원(time dimension)(dim 0)에서 입력을 flip (dim 0),
            # 계층 적용, 그리고 시간 차원에서 출력을 flip
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +    # 앙상블의 모듈은 같은 입력에서 하나하나씩 실행되고, 결과들이 누적되고 합산되어 결합된 결과를 반환합니다.
```suggestion
    # `BidirectionalRecurrentLSTM` 모듈의 "ensemble"
    # 앙상블의 모듈은 같은 입력으로 하나하나씩 실행되고, 누적되고 합산된 결과를 반환합니다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +    # 목적을 위해 이 데모에서는 랜덤 데이터를 사용하겠습니다.
```suggestion
    # 일반적으로 임베딩 테이블(embedding table)에서 입력을 가져오지만,
    # 데모를 위해 여기서는 무작위 데이터를 사용하겠습니다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +    # 메모리 할당자(memory allocator)
```suggestion
    # 메모리 할당자(memory allocator) 등을 준비시키기 위해 모델을 먼저 한번 실행합니다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +컴퓨터에서 네트워크가 ``2.05``초에 실행되었습니다. 우리는 더 잘 할 수 있습니다!
```suggestion
제 컴퓨터에서는 네트워크가 ``2.05``초 만에 실행되었습니다. 훨씬 더 빠르게 할 수 있습니다!
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +``BidirectionalRecurrentLSTM`` 내에서 forward, backward 계층들을 병렬화하는 것은 우리가 할 수 있는 아주 간단한 일입니다.
```suggestion
간단하게 할 수 있는 일로는 ``BidirectionalRecurrentLSTM`` 내에서 forward, backward 계층들을 병렬화하는 것이 있습니다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +이를 위해 계산 구조는 고정되어 우리는 어떤 루프도 필요로 하지 않습니다.
```suggestion
이 때, 계산 구조는 고정되어 있으므로 우리는 어떤 루프도 필요로 하지 않습니다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +            # 계층 적용, 그리고 시간 차원에서 출력 flip
```suggestion
            # Backward 계층. 시간 차원(time dimension)(dim 0)에서 입력을 flip (dim 0),
            # 계층 적용, 그리고 시간 차원에서 출력을 flip
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +            # forward 계층에서 출력을 검색.
```suggestion
            # forward 계층에서 출력을 받아 옴.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +이 간단한 수정과 함께 스크립트를 다시 실행하면 ``1.71``초의 런타임으로 ``17%``만큼 향상되었습니다!
```suggestion
이 간단한 수정 후에 스크립트를 다시 실행하면 ``17%`` 향상된 ``1.71``초의 런타임이 나옵니다!
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +우리는 아직 모델을 최적화시키는 것을 끝내지 않았지만 성능 시각화를 위한 도구를 설명해 볼 만 합니다.
```suggestion
아직 모델 최적화가 끝나지 않았지만 이쯤에서 성능 시각화를 위한 도구를 도입해봅시다.
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +Chrome 추적 내보내기 기능(trace export functionality)과 함께 프로파일러를 사용해
```suggestion
Chrome의 추적 내보내기 기능(trace export functionality)과 함께 프로파일러를 사용해
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +만약 당신이 Google Chrome에서 ``chrome://tracing``으로 이동하여 ``Load`` 버튼을 클릭하고
```suggestion
Google Chrome에서 ``chrome://tracing``으로 이동하여 ``Load`` 버튼을 클릭하고
```

2021-04-08 07:41 UTC, Hoseung commented on advanced_source/torch-script-parallelism.rst
> +또는, 만약 당신이 간결함을 중요하게 생각한다면 목록 이해력(list comprehension)를 사용할 수 있습니다.
list comprehension을 '목록 이해력'이라고 번역하나요? 다른 리뷰어께서 적절한 단어로 수정 부탁드립니다.

2021-04-08 12:01 UTC, 9bow commented
@Hoseung 님, 리뷰에 참여해주셔서 대단히 감사합니다!
개인적인 사정으로 이래저래 PR이 쌓이다보니 엄두가 안나서 안절부절하고만 있었는데... 한줄기 빛이 되어주셨습니다 ㅎㅎ
이번 주말 중으로 남겨주신 리뷰부터 시작하여 1.8 튜토리얼 반영(#207)도 진행해볼 수 있도록 하겠습니다. :)
감사합니다!

2021-04-11 13:08 UTC, 9bow commented on advanced_source/torch-script-parallelism.rst
> +        # 병렬 처리를 사용하여 `foo`를 호출:
reST 문법 상 아래와 같이 추가 제안합니다.

```suggestion
        # 병렬로 `foo` 를 호출:
```

2021-04-11 13:11 UTC, 9bow commented
@greeeener 님, 위 @Hoseung 님의 변경 제안들은 검토해보셨는지요?
제 기준으로는, 전체적으로 더 편하게 읽혀지는 부분이 있어 전반적으로 수락해주셨으면 하는 리뷰들이 많았습니다.
먼저 @Hoseung 님의 변경 제안을 받아주시면 (v1.8 반영 후) 추가 리뷰 / 반영할 수 있도록 하겠습니다.
감사합니다.

2021-04-11 13:16 UTC, Hoseung commented
안녕하세요 @9bow 님, @greeeener 님, 제가 review가 처음일 뿐 아니라 사실은 깃헙에서 다른 분과 의사소통을 하는 것 자체가 처음입니다. (맨날 혼자서만 뭘 해서요 ㅠㅠ) 혹시 나중에라도 과정상 제가 뭘 해야하는데 안 하고 있거나 하면 몰라서 그러는 것일테니 미리 조언을 부탁드립니다 ^^;

2021-04-11 13:23 UTC, 9bow commented
안녕하세요, @Hoseung 님. 
참여가 필요하신 경우에는 지금처럼 멘션(@아이디)을 걸어드리겠습니다. ^^
멘션이 있는 경우 별도의 알람(이메일 등)을 받으실테니 참고하시면 좋을 것 같습니다.
감사합니다. :)

2021-11-07 13:01 UTC, hyoyoung commented
feedback이 없어서 pr을 close합니다.
필요할때 열어주시거나 새로 생성하여주세요.

2021-11-07 13:01 UTC, closed without merging