Fsgm tutorial
9bow/PyTorch-tutorials-kr pull request #246
Opened 2021-08-24 11:45 UTC by lsh3163

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #245 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [x] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
아래 컴파일 오류 없애고 정상적으로 작동하도록 수정하였습니다. 
![image](https://user-images.githubusercontent.com/9862424/130610677-e04d237e-b665-4c50-8828-345adcde3fc7.png)

2021-08-24 12:17 UTC, 9bow commented on beginner_source/fgsm_tutorial.py
> +# .. figure:: /_static/img/fgsm_panda_image.png
👍 👍 👍

2021-08-24 12:18 UTC, 9bow approved these changes
감사합니다! 👍👍👍

2021-08-29 15:40 UTC, hyoyoung requested changes
indent 바뀌지 않게 다시 pr 보내주세요

2021-08-29 16:22 UTC, lsh3163 commented
> indent 바뀌지 않게 다시 pr 보내주세요

2021-08-30 13:11 UTC, hyoyoung commented
figure 부분만 커밋된게 맞나요? 브랜치가 왠지 바뀐듯합니다 확인 부탁드립니다

2021-08-30 13:23 UTC, 9bow commented
기존에 heading 부분도 수정해주셨던걸 Slack에 올려주셨었는데요, 그 부분이 사라진 것 같습니다.
@lsh3163 님, 확인 부탁드려도 괜찮으실까요?
![image](https://user-images.githubusercontent.com/9343724/131345710-17e2539b-3cd0-44a0-85fb-213e032cc1cc.png)
![image](https://user-images.githubusercontent.com/9343724/131345733-f7e5a2e6-73da-45cb-9938-84b7b6ade65f.png)

2021-08-30 13:32 UTC, lsh3163 commented
> 기존에 heading 부분도 수정해주셨던걸 Slack에 올려주셨었는데요, 그 부분이 사라진 것 같습니다.
> @lsh3163 님, 확인 부탁드려도 괜찮으실까요?
> ![image](https://user-images.githubusercontent.com/9343724/131345710-17e2539b-3cd0-44a0-85fb-213e032cc1cc.png)
> ![image](https://user-images.githubusercontent.com/9343724/131345733-f7e5a2e6-73da-45cb-9938-84b7b6ade65f.png)

@9bow 그림->figure로 pr 머지 되면 다음 pr 열어서 진행하겠습니다!

2021-08-30 13:57 UTC, hyoyoung requested changes

2021-08-30 13:57 UTC, hyoyoung commented on beginner_source/fgsm_tutorial.py
> +#
newline 넣지 말고 다시 올려주세요

2021-08-30 15:41 UTC, hyoyoung requested changes

2021-08-30 15:41 UTC, hyoyoung commented on beginner_source/fgsm_tutorial.py
> -#
이제 newline은 삭제되었는데 원래 있던 #이 없어졌습니다.
이전에 문제가 되었던게 #(newline)이었는데
아예 #까지 삭제가 된거 같아요 확인 부탁드립니다.

2021-08-30 16:06 UTC, hyoyoung approved these changes
looks good to me

2021-08-31 10:15 UTC, merged