intermediate_source/torchvision_tutorial.rst 스타일 개선
9bow/PyTorch-tutorials-kr pull request #282
Opened 2021-08-27 13:12 UTC by joonkeekim

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #281 (숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [x] 오탈자를 수정하거나 번역을 개선하는 기여
- [ ] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

데이터셋 정의하기의 부자연스러운 부분을 개선해보았습니다.

2021-08-28 05:48 UTC, joonkeekim commented on intermediate_source/torchvision_tutorial.rst
> +리턴을 해야 하는 것입니다:
위에 말씀해주신 데이터셋 클래스와 리턴에 관해선 원번역을 따라가다보니 그렇게 했습니다! 다시 수정해서 올리도록 하겠습니다!

2021-08-28 07:22 UTC, joonkeekim commented
말씀해주신 참고사항을 바탕으로 다시 수정해보았습니다!

2021-08-28 09:10 UTC, hyoyoung requested changes
용어집 pr과 번역 수정 pr이 같이 있으면 안됩니다
1 pr에는 1가지만 담아주시기 바랍니다

2021-08-28 09:43 UTC, joonkeekim commented
넵 바로 수정하였습니다!

2021-08-29 15:49 UTC, hyoyoung approved these changes
looks good to me

2021-08-30 13:12 UTC, 9bow approved these changes
👍

2021-08-30 13:12 UTC, merged