기존 내용 반영 후 웜스타트 용어 수정 및 파라미터를 매개변수로 수정
9bow/PyTorch-tutorials-kr pull request #313
Opened 2021-09-05 08:37 UTC by lewha0

## 라이선스 동의
- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
- **이슈 번호**: #123
- **관련 PR**: #131 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
- 이전 번역에 대한 수정 사항을 반영하고, 새 버전과 관련된 부분도 반영합니다.

2021-09-05 08:39 UTC, lewha0 commented
https://github.com/9bow/PyTorch-tutorials-kr/pull/131 에서 논의되었던 내용의 후속 작업입니다.

웜스타트(warmstart)라는 용어를 빠르게 시작하기라는 용어로 수정하였습니다. 그리고 수정 중 파라미터라는 용어를 매개변수로 수정하였습니다.

현재 버전을 기준으로 작업 시작했고(1.8), 일전에 말씀해주신 것처럼 이 문서는 버전 업에 따른 수정사항이 없어서 아마 버전 관련 문제는 없을 것으로 생각됩니다. 추가 수정 등의 작업이 필요하다면 알려 주세요.

2021-09-05 15:41 UTC, hyoyoung requested changes

2021-09-05 15:41 UTC, hyoyoung commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# - `PyTorch에서 여러 모델을 하나의 파일에 저장하기 & 불러오기 <https://tutorials.pytorch.kr/recipes/recipes/saving_multiple_models_in_one_file.html>`__
아래줄처럼 '저장하고 불러오기'로 맞추면 좋을듯합니다

2021-09-05 15:41 UTC, hyoyoung commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 않는 상황이라고 해 봅시다. 그럴 때는 여러분이 불러오려 하는 state_dict
강조의 의미가 아니면 주어는 생략해주세요

2021-09-05 15:41 UTC, hyoyoung commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 의 매개변수 키의 이름을 바꿔서, 불러온 모델을 저장하려는 모델의 키와
특이한 상황이 아니면 조사는 줄 내림을 하지 않고 붙여주세요

2021-09-05 15:41 UTC, hyoyoung commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 우리는 하나의 예로써 이미지를 학습하는 신경망을 만들어 보려 합니다.
강조의 의미가 아니면 주어는 생략해주세요

2021-09-05 15:41 UTC, hyoyoung commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 참고하시기 바랍니다. 우리는 신경망을 두 개 만들려고 하는데, 신경망 A의
여기도 주어 생략 필요합니다

2021-09-05 15:41 UTC, hyoyoung commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +여러분이 일부 키가 누락된 부분적인 ``state_dict`` 를 불러올 때든, 아니면
강조의 의미가 아니면 주어는 생략해주세요

2021-09-05 15:41 UTC, hyoyoung commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +기존 모델을 부분적으로 불러오거나, 혹은 부분적인 모델을 불러오는
'기존'은 없어도 자연스러울 듯합니다

2021-09-05 20:11 UTC, lewha0 commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# - `PyTorch에서 여러 모델을 하나의 파일에 저장하기 & 불러오기 <https://tutorials.pytorch.kr/recipes/recipes/saving_multiple_models_in_one_file.html>`__
이 내용은 해당 튜토리얼의 제목에서 그대로 가져온 것입니다.

2021-09-05 20:12 UTC, lewha0 commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 않는 상황이라고 해 봅시다. 그럴 때는 여러분이 불러오려 하는 state_dict
'여러분'을 말씀하시는 거죠? 알겠습니다

2021-09-05 20:13 UTC, lewha0 commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 의 매개변수 키의 이름을 바꿔서, 불러온 모델을 저장하려는 모델의 키와
네, 확인하였습니다

2021-09-05 20:14 UTC, lewha0 commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 우리는 하나의 예로써 이미지를 학습하는 신경망을 만들어 보려 합니다.
수정하였습니다.

2021-09-05 20:14 UTC, lewha0 commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +# 참고하시기 바랍니다. 우리는 신경망을 두 개 만들려고 하는데, 신경망 A의
수정하였습니다.

2021-09-05 20:14 UTC, lewha0 commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +여러분이 일부 키가 누락된 부분적인 ``state_dict`` 를 불러올 때든, 아니면
수정하였습니다.

2021-09-05 20:15 UTC, lewha0 commented on recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
> +기존 모델을 부분적으로 불러오거나, 혹은 부분적인 모델을 불러오는
수정하였습니다.

2021-09-05 20:16 UTC, lewha0 commented
말씀해주신 내용 반영하였고, 주어가 남아 있는 부분이 한 곳 더 있어서 수정했습니다. (마지막 부분에 나온 것은 자연스러워 보여 그대로 두었습니다.)

2021-09-06 00:20 UTC, hyoyoung approved these changes
looks good to me

2021-09-07 04:04 UTC, 9bow approved these changes

2021-09-07 14:46 UTC, merged