Translate vt_tutorial.py
9bow/PyTorch-tutorials-kr pull request #319
Opened 2021-09-08 03:12 UTC by Taeyoung96

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #310 

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

[OPTIMIZING VISION TRANSFORMER MODEL FOR DEPLOYMENT](https://tutorials.pytorch.kr/beginner/vt_tutorial.html)의 일부를 번역했습니다.  

- 저자의 이름이 업데이트 되어 있지 않아, 업데이트를 진행  
- 아래 그림 처럼 빌드 후에도 오류가 생기는 부분을 임의로 문단을 나누는 Trick을 활용하여 수정 (Line 23~25 참고)  

![image](https://user-images.githubusercontent.com/41863759/132440265-d0494a72-9ac5-4ed6-93b5-666dea9db42f.png)

2021-09-08 03:37 UTC, puhuk commented on beginner_source/vt_tutorial.py
> +# 1.8.0 이여야 합니다.
Pytorch 버전은 1.8.0 이어야 합니다. 
가 어떨지 의견드립니다.

2021-09-08 10:34 UTC, Taeyoung96 commented on beginner_source/vt_tutorial.py
> +# 1.8.0 이여야 합니다.
너무 직독 직해를 한 것 같네요! 말씀하신대로 수정하는게 더 자연스러울 것 같습니다 ㅎㅎ

2021-09-08 13:05 UTC, hyoyoung requested changes

2021-09-08 13:05 UTC, hyoyoung commented on beginner_source/vt_tutorial.py
> +#
이 트릭은 제거해야할듯 합니다
위에서 문단 분리가 안되어서 문제가 생기는건데, 이렇게 해두면 html로 결과는 비슷하게 보일지 몰라도
빈 문단을 중간에 삽입해서 문서 구조가 바뀌는 문제가 생깁니다

차라리 위의 """ 직전 줄에 빈 공백있는 줄 한칸을 삽입해서 테스트해보세요
위 문단과 아래 문단이 구분되어서 잘 보일것입니다

2021-09-09 05:50 UTC, joonkeekim commented on beginner_source/vt_tutorial.py
> +# DeiT를 사용하여 어떻게 이미지들을 분류하는지 자세한 정보는 DeiT 저장소에 README를 참고하시길 바랍니다.
DeiT를 사용하여 이미지를 분류하는 방법에 대한 자세한 정보는 으로 번역하는게 조금 더 자연스러울것 같습니다!

2021-09-09 05:50 UTC, joonkeekim commented on beginner_source/vt_tutorial.py
> +# 빠른 테스트를 위해선, 첫번째로 요구되는 패키지들을
먼저 필요한 패키지들을 설치해 봅시다 도 괜찮을것 같습니다!

2021-09-13 13:57 UTC, spongebob03 commented on beginner_source/vt_tutorial.py
> +# 이미지 분류를 수행할 때 주요한 모델이였습니다. 그러나 컨벌루션 신경망은 일반적으로
합성곱 신경망(CNNs)은 어떤가요? 현재 파이토치 번역에는 합성곱 신경망으로 쓰는 문서의 빈도가 더 높아보여 의견 드립니다. 합성곱으로 투표되었는데 용어집에는 아직 없는거 같습니다.

2021-09-15 12:23 UTC, puhuk commented on beginner_source/vt_tutorial.py
> +# DeiT 양자화하기
저도 빼는게 자연스러워 보입니다.
DeiT 양자화하기 -> DeiT 양자화

2021-09-30 14:17 UTC, closed without merging