Update fx_conv_bn_fuser.py
9bow/PyTorch-tutorials-kr pull request #370
Opened 2021-11-07 15:44 UTC by kozeldark

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #356

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
fx_conv_bn_fuser.py 파일을 번역하였습니다.

2021-11-11 14:10 UTC, hyoyoung requested changes
수정 부탁드립니다

2021-11-11 14:10 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
>  **Author**: `Horace He <https://github.com/chillee>`_
다른 페이지에서는 author를 보통 저자라고 번역합니다

2021-11-11 14:10 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
> +우리는 다음 링크에 있는 결합기를 구축할 것입니다.
주어는 보통 강조의 의미가 아니면 생략합니다

2021-11-11 14:10 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
> +# FX는 호출된 실제 연산을 상징적으로 추적하여 이 문제를 해결하므로 순차적 모듈 내에 중첩되거나
여기서 symbolic은 기호로 번역하는게 어떨까요?
참조 : https://ko.wikipedia.org/wiki/%EA%B8%B0%ED%98%B8%EA%B3%84%EC%82%B0

2021-11-11 14:10 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
> +    # 단, 이제 우리는 우리의 순전파 단계(forward pass)에 대한 그래프 표현도 가지고 있습니다.
주어는 강조의 의미가 아니면 생략합니다

2021-11-11 14:17 UTC, kozeldark commented on intermediate_source/fx_conv_bn_fuser.py
>  **Author**: `Horace He <https://github.com/chillee>`_
이 부분을 놓치고 있었네요. 감사합니다!

2021-11-11 14:20 UTC, kozeldark commented on intermediate_source/fx_conv_bn_fuser.py
> +우리는 다음 링크에 있는 결합기를 구축할 것입니다.
그렇군요. 이와 관련된 부분 수정하도록 하겠습니다.

2021-11-11 14:24 UTC, kozeldark commented on intermediate_source/fx_conv_bn_fuser.py
> +# FX는 호출된 실제 연산을 상징적으로 추적하여 이 문제를 해결하므로 순차적 모듈 내에 중첩되거나
'상징', '기호' 이렇게 정말 고민을 많이 하던 부분이였습니다. 참조를 보니 기호가 더 적절한 표현같네요. 조언 감사드립니다!

2021-11-13 17:23 UTC, hyoyoung requested changes

2021-11-13 17:23 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
> +(베타) FX에서 합성곱/배치 정규화(Convolution/Batch Norm) 결합기(Fuser) 구축하기
building은 구축하기보다 만들기로 쉬운 단어로 교체하면 어떨까요?

2021-11-13 17:23 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
> +        # FX IR 에는 일반적으로 모듈, 함수 또는 메서드에 대한
method의 음차표기는 메소드로 사용하고 있습니다
TRANSLATION_GUIDE.md 참조

2021-11-13 17:46 UTC, kozeldark commented on intermediate_source/fx_conv_bn_fuser.py
> +(베타) FX에서 합성곱/배치 정규화(Convolution/Batch Norm) 결합기(Fuser) 구축하기
확실히 구축하기보다는 만들기가 좀 더 쉽게 다가오네요. 구축하기는 너무 직역체인 느낌이 없지 않았습니다. 조언 감사드립니다!

2021-11-13 17:50 UTC, kozeldark commented on intermediate_source/fx_conv_bn_fuser.py
> +        # FX IR 에는 일반적으로 모듈, 함수 또는 메서드에 대한
이 부분을 놓치고 있었네요. 감사합니다!

2021-11-14 07:15 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
> +#       여기서는 2D 합성곱만 일치시키는 등 시연 목적으로 몇 가지 단순화를 수행합니다.
단순화 수행이 목적이 아니라, 과정의 일부라 요렇게 바꿔보는건 어떨까요?

여기서는 2D 합성곱만 일치시키는 등 시연 목적으로 약간의 단순화를 하였습니다.

2021-11-14 07:15 UTC, hyoyoung commented on intermediate_source/fx_conv_bn_fuser.py
> +# FX는 아직 베타 버전이기 때문에 FX 사용에 대한 피드백을 들려주시면 감사하겠습니다.
hear를 굳이 들려준다고 직역하지 않아도 될거 같습니다

피드백을 보내주시면 감사하겠습니다. 라고 하면 어떨까요?

2021-11-14 10:29 UTC, kozeldark commented on intermediate_source/fx_conv_bn_fuser.py
> +#       여기서는 2D 합성곱만 일치시키는 등 시연 목적으로 몇 가지 단순화를 수행합니다.
과정의 일부로 생각하고 번역을 했으나 너무 중의적으로 보였네요. 조언 감사드립니다!

2021-11-14 10:30 UTC, kozeldark commented on intermediate_source/fx_conv_bn_fuser.py
> +# FX는 아직 베타 버전이기 때문에 FX 사용에 대한 피드백을 들려주시면 감사하겠습니다.
그 방법이 더 좋아보이네요. 조언 감사드립니다!

2021-11-14 10:49 UTC, hyoyoung commented
리뷰가 바뀌면 pr 에서 오른쪽 리뷰어 메뉴에서 re-request review 한번씩 눌러주세요

2021-11-14 10:51 UTC, hyoyoung approved these changes
looks good to me

2021-11-14 10:51 UTC, merged