advanced/torch_script_custom_classes 번역
9bow/PyTorch-tutorials-kr pull request #372
Opened 2021-11-08 09:08 UTC by JEONTAK

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_

- **이슈 번호**: #359

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._

advanced/torch_script_custom_classes 번역 했습니다.
피드백 주시면 감사하겠습니다.

또한 중간 literalinclude 부분에 들어가는 내용도 따로 번역해야하는지 궁금합니다!

2021-11-13 17:40 UTC, hyoyoung requested changes

2021-11-13 17:40 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +과 매우 유사하며 해당 시스템에 익숙하다면 대부분의 개념이 이전됩니다.
조사 단독으로 줄 내림을 하지 않는게 좋을것 같습니다. 

API는 `pybind11 <https://github.com/pybind/pybind11>`_ 과
매우 유사하며 해당 시스템에 익숙하다면 대부분의 개념이 이전됩니다.

이렇게 바꾸는건 어떨까요

2021-11-13 17:40 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +커스텀 클래스를 사용하여 TorchScript 코드 저장, 로드 및 실행
loading은 읽기로 순화해도 좋을듯합니다

2021-11-13 17:40 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +우리 파일 시스템의 ``foo.pt`` 는 이제 우리가 방금 정의한 직렬화된 TorchScript 프로그램을 포함합니다.
강조의 의미가 아니면 명시적인 주어는 생략합니다

2021-11-13 17:40 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +언제나 그렇듯이, 문제를 맞닥뜨리시거나 질문이 있으시면 저희 `forum <https://discuss.pytorch.org/>`_ 또는
언제나처럼 문제를 마주치거나 질문이 있으면 

이정도로 바꿔보는건 어떨까요

2021-11-14 04:19 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +과 매우 유사하며 해당 시스템에 익숙하다면 대부분의 개념이 이전됩니다.
더 좋은 것 같습니다!

2021-11-14 04:23 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +커스텀 클래스를 사용하여 TorchScript 코드 저장, 로드 및 실행
참고하겠습니다!

2021-11-14 04:24 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +언제나 그렇듯이, 문제를 맞닥뜨리시거나 질문이 있으시면 저희 `forum <https://discuss.pytorch.org/>`_ 또는
그게 더 딱딱하지 않고 유하게 표현된 것 같습니다!

2021-11-14 04:26 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +우리 파일 시스템의 ``foo.pt`` 는 이제 우리가 방금 정의한 직렬화된 TorchScript 프로그램을 포함합니다.
참고하겠습니다!

2021-11-14 04:29 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +언제나 그렇듯이, 문제를 맞닥뜨리시거나 질문이 있으시면 저희 `forum <https://discuss.pytorch.org/>`_ 또는
또한 '우리' 와 같은 대명사도 모두 제거했습니다.

2021-11-14 05:14 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +을 참조하세요.
여기도 조사 '을'은 윗 문장으로 붙여주세요

2021-11-14 05:14 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +이제 이 클래스를 *바인딩* 클래스라고 하는 프로세스인 TorchScript에 표시하는 방법을 살펴보겠습니다:
해석이 약간 다른거 같은데, visible하고 binding에 대한 부분이 모호한것 같습니다
아래 문장처럼 visible하고 binding을 좀 더 명확하게 표시하면 어떨까요?

이제 이 클래스를 어떻게 TorchScript에서 사용가능하게 하는지 살펴보겠습니다. 이런 과정은 클래스를 *바인딩*한다고 합니다.

2021-11-14 05:14 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +를 참조하세요.
조사 '를'은 위의 문장과 붙여주세요

2021-11-14 05:14 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +커스텀 클래스를 바이너리로 빌드할 수 있도록 ``custom_class_project`` 를 이 C++ 프로젝트에 종속성으로 추가할 것입니다.
종속성 대신에 의존성을 추가할 것입니다 라고 하면 어떨까요?

2021-11-14 05:14 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +커스텀 C++ 클래스를 정의한 후에는 해당 클래스를 인수로 사용하거나 커스텀 연산자(free 함수)에서
(free 함수)와 같은 걸 얘기하는 부분이니
(예를 들자면 free 함수) 정도로 넣어주는건 어떨까요?

2021-11-14 05:14 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +에 유용한 정보가 있을 수 있습니다.
조사 '에'는 윗 문장으로 붙여주세요

2021-11-14 05:41 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +이제 이 클래스를 *바인딩* 클래스라고 하는 프로세스인 TorchScript에 표시하는 방법을 살펴보겠습니다:
저도 이 부분이 애매하다고 느꼈는데 훨씬 좋은것 같습니다!

2021-11-14 05:41 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +커스텀 클래스를 바이너리로 빌드할 수 있도록 ``custom_class_project`` 를 이 C++ 프로젝트에 종속성으로 추가할 것입니다.
알겠습니다!

2021-11-14 05:44 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +커스텀 C++ 클래스를 정의한 후에는 해당 클래스를 인수로 사용하거나 커스텀 연산자(free 함수)에서
알겠습니다!

2021-11-14 07:30 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +해당 클래스를 사용하는 방법, 클래스를 사용하여 코드를 저장 및 로드하고 해당 코드를
여기서 load도 읽어들이고 정도로 고쳐도 좋을 것 같습니다

2021-11-14 07:30 UTC, hyoyoung commented on advanced_source/torch_script_custom_classes.rst
> +혼합되어야 하는 다른 사용 사례를 구현할 준비가 되었습니다.
라인 부분을 약간 바꿔보았습니다

이제 타사 C++ 라이브러리와 인터페이스가 있는 C++ 클래스로 TorchScript 모델을 확장하거나,
Python, TorchScript 및 C++ 사이에서 원활하게 혼합된 라인이 있어야하는 다른 사용 사례를 구현할 준비가 되었습니다.

2021-11-14 07:35 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +해당 클래스를 사용하는 방법, 클래스를 사용하여 코드를 저장 및 로드하고 해당 코드를
참고하겠습니다!

2021-11-14 07:36 UTC, JEONTAK commented on advanced_source/torch_script_custom_classes.rst
> +혼합되어야 하는 다른 사용 사례를 구현할 준비가 되었습니다.
참고하여 수정하겠습니다!

2021-11-14 08:43 UTC, hyoyoung reviewed
리뷰가 바뀌면 pr 에서 오른쪽 리뷰어 메뉴에서 re-request review 한번씩 눌러주세요

2021-11-14 08:43 UTC, hyoyoung approved these changes
looks good to me

2021-11-14 10:47 UTC, hyoyoung approved these changes

2021-11-14 10:48 UTC, merged