intermediate/ddp_tutorial 번역
9bow/PyTorch-tutorials-kr pull request #373
Opened 2021-11-09 07:09 UTC by Jo-byung-geun

## 라이선스 동의
_변경해주시는 내용에 BSD 3항 라이선스가 적용됨을 동의해주셔야 합니다._<br />
_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_동의하시면 아래 `[ ]`를 `[x]`로 만들어주세요._<br />

- [x] 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
_이 Pull Request와 관련있는 이슈 번호를 적어주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_ #358

- **이슈 번호**: #(숫자)

## PR 종류
_이 PR에 해당되는 종류 앞의 `[ ]`을 `[x]`로 변경해주세요._<br />
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

## PR 설명
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._
intermediate/ddp_tutorial 번역했습니다.
피드백 주시면 감사하겠습니다.

2021-11-15 13:45 UTC, hyoyoung requested changes

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
>  **Author**: `Shen Li <https://mrshenli.github.io/>`_
author는 저자로 보통 번역합니다

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
>  **Edited by**: `Joe Zhu <https://github.com/gunandrose4u>`_
번역 추가 필요

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +`분산 데이터 병렬 처리 <https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel>`__\(DDP)는 여러 기기에서 실행할 수 있는 데이터 병렬 처리를 모듈 수준에서 구현합니다.
줄이 너무 길어지면 원본과 비슷한 정도로 줄내림을 해주세요

여러 기기에~ 이 부분부터 줄내림을 해도 좋을듯합니다

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +- 첫째, ``DataParallel``\은 단일 프로세스, 멀티쓰레드이며 단일 기기에서만 작동하는 반면, ``DistributedDataParallel``\은 다중 프로세스이며 단일 및 다중 기기 학습을 전부 지원합니다. ``DataParallel``\은 쓰레드간 GIL 경합, 복제 모델의 반복 당 생성, 산란 입력 및 수집 출력으로 인한 추가 오버헤드
줄 내림이 필요합니다

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +- 모델이 여러 대의 기기에 존재해야 하거나 사용 사례가 데이터 병렬화 패러다임에 맞지 않는 경우, 일반적인 분산 학습 지원을 보려면 `the RPC API <https://pytorch.org/docs/stable/rpc.html>`__\를 참조하십시오.
줄 내림이 필요합니다

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +우선 DDP는 0순위 프로세스에서부터 DDP 생성자의 다른 모든 프로세스들에게 모델의 상태를 전달하므로, 다른 모델의 매개 변수 초기값들에서 시작하는 다른 DDP 프로세스들에 대하여 걱정할 필요가 없습니다.
줄 내림이 필요합니다

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +보여지는 바와 같이 DDP는 하위 수준의 분산 커뮤니케이션 세부 사항을 포함하고 로컬 모델처럼 깔끔한 API를 제공합니다. 변화도 동기화 통신(gradient synchronization communications)은 역전파 작업(backward pass)간 수행되며 역전파 계산(backward computation)과 겹치게 됩니다.
줄 내림이 필요합니다

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +        # 0이 이를 의미합니다.
프로세스 0이 저장한후에 프로세스 1이 읽는다는 뜻일까요?

2021-11-15 13:45 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +          run_demo(demo_model_parallel, 4)
원본과 indent가 바뀌었습니다. 코드는 원본과 같은 indent로 해주세요

2021-11-15 13:57 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +          run_demo(demo_model_parallel, 4)
반영하겠습니다.

2021-11-15 13:58 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +        # 0이 이를 의미합니다.
그런 것 같습니다. 그렇게 반영하도록 하겠습니다.

2021-11-15 14:04 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +`분산 데이터 병렬 처리 <https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel>`__\(DDP)는 여러 기기에서 실행할 수 있는 데이터 병렬 처리를 모듈 수준에서 구현합니다.
반영하겠습니다.

2021-11-15 14:43 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
>  **Author**: `Shen Li <https://mrshenli.github.io/>`_
반영했습니다.

2021-11-15 14:43 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
>  **Edited by**: `Joe Zhu <https://github.com/gunandrose4u>`_
반영했습니다.

2021-11-15 14:45 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +          run_demo(demo_model_parallel, 4)
indent 차이를 발견하지 못해서 그런데 혹시 어떤 부분이 변경되야 할까요..?

2021-11-16 13:35 UTC, hyoyoung requested changes

2021-11-16 13:35 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +**편집자**: `Joe Zhu <https://github.com/gunandrose4u>`_
번역자 항목 추가해주세요

2021-11-16 13:35 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> -
소스 코드의 indent는 변경하지 말아주세요

2021-11-16 13:35 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> -
소스 코드의 indent는 변경하지 말아주세요

2021-11-16 13:35 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +그 모델을 모든 프로세스에 작성 오버헤드(write overhead)를 줄이며 읽어오는 것입니다.
여기서는 작성 오버헤드보다 쓰기 과부하 정도는 어떨까요?

2021-11-16 13:35 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +          run_demo(demo_model_parallel, 4)
직접 작업하신 리포에서 살펴보면 차이를 아실수 있습니다
git log -p 등으로 확인해보면 되고요.
원래 파일에 있던 end_of_line 캐릭터가 삭제되었습니다

```
-          run_demo(demo_model_parallel, 4)
+          run_demo(demo_model_parallel, 4)
\ No newline at end of file
```

2021-11-16 14:14 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +**편집자**: `Joe Zhu <https://github.com/gunandrose4u>`_
넵 추가하겠습니다.

2021-11-16 14:15 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +그 모델을 모든 프로세스에 작성 오버헤드(write overhead)를 줄이며 읽어오는 것입니다.
반영하겠습니다.

2021-11-16 14:15 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +          run_demo(demo_model_parallel, 4)
넵 직접 확인해서 수정하겠습니다.

2021-11-17 14:11 UTC, hyoyoung requested changes

2021-11-17 14:11 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +**번역자**: `조병근 <https://github.com/Jo-byung-geun>`_
번역자 말고 번역으로 바꿔주세요
편집자보다는 감수 정도가 좋을것 같습니다

2021-11-17 14:11 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +hook은 역방향 전달에서 해당 변화도(gradient)가 계산될 때 작동합니다.
강조의 의미가 아니면 '변화도(gradient)'는 반복해서 영어 단어를 병기할 필요는 없을듯 합니다
처음에는 '변화도(gradient)'로 쓰시고, 그 뒤에는 '변화도'로 쓰는게 어떨까요

2021-11-17 14:11 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +        # 모델을 생성하고 rank 아이디가 있는 GPU로 전달.
위에서는 rank 0 process를 0순위 프로세스라고 번역했으므로
rank 아이디는 순위 아이디로 하면 어떨까요?

2021-11-17 14:11 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +때때로 비대칭 프로세스(skewed processing) 속도는 다음과 같은 이유로 인하여 불가피하게 발생합니다.
비대칭 프로세스보다는 비대칭 작업 속도 더 읽기 좋을듯합니다.
이 문단에서는 전체적으로 프로세스는 작업으로 고쳐는게 더 좋을듯한데 어떻게 생각하시나요?

2021-11-17 14:55 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +hook은 역방향 전달에서 해당 변화도(gradient)가 계산될 때 작동합니다.
반영하겠습니다. 변화도라는 단어가 많이 나와 매번 영어를 반복해서 작성하는 것에 고민이 있었는데 좋은 것 같습니다.

2021-11-17 14:56 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +**번역자**: `조병근 <https://github.com/Jo-byung-geun>`_
반영하겠습니다.

2021-11-17 14:56 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +        # 모델을 생성하고 rank 아이디가 있는 GPU로 전달.
반영하겠습니다.

2021-11-17 14:58 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +때때로 비대칭 프로세스(skewed processing) 속도는 다음과 같은 이유로 인하여 불가피하게 발생합니다.
프로세스라고 번역하는 것보다 더 자연스러운 것 같습니다. 반영하겠습니다.

2021-11-17 15:18 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +때때로 비대칭 프로세스(skewed processing) 속도는 다음과 같은 이유로 인하여 불가피하게 발생합니다.
일단 이 문단에서 작업으로 수정하고 처음 process에만 '작업(process)'로 쓰고 그 후에는 '작업'으로 수정해두겠습니다.

2021-11-18 13:32 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +때때로 비대칭 프로세스(skewed processing) 속도는 다음과 같은 이유로 인하여 불가피하게 발생합니다.
넵 그 방안도 좋습니다

2021-11-18 13:35 UTC, hyoyoung requested changes

2021-11-18 13:35 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +비대칭 프로세싱 속도
아래에서 비대칭 작업 속도로 바꿨으므로 같이 바뀌어야할듯합니다

2021-11-18 13:35 UTC, hyoyoung commented on intermediate_source/ddp_tutorial.rst
> +각 동기화 지점을 거의 동시에 입력할 것을 요구합니다.
여기서 enter는 입력보다는 진입에 가까울거 같습니다

'각 동기화 지점을 거의 동시에 진입을 요구합니다'

2021-11-18 14:14 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +비대칭 프로세싱 속도
전체적으로 수정하겠습니다.

2021-11-18 14:14 UTC, Jo-byung-geun commented on intermediate_source/ddp_tutorial.rst
> +각 동기화 지점을 거의 동시에 입력할 것을 요구합니다.
반영하겠습니다.

2021-11-18 14:55 UTC, hyoyoung approved these changes
looks good to me

2021-11-18 14:55 UTC, merged